### PR TITLE
Add SegmentationVerification extension

### PR DESCRIPTION
**Pull request by cpinter**
# New extension

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Any known related patents must be mentioned in the extension description.
- [x] LICENSE.txt is present in the repository root. MIT  (https://choosealicense.com/licenses/mit/) or Apache (https://choosealicense.com/licenses/apache-2.0/) license is recommended. If source code license is more restrictive for users than MIT, BSD, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (main, release, ...) instead of a specific git hash to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://raw.githubusercontent.com/user/repo/main/SomeIcon.png)
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [x] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/main/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [x] Content of submitted json file is consistent with the top-level CMakeLists.txt file in the repository (dependencies, etc. are the same)
- Hide unused features in the repository to reduce noise/irrelevant information:
  - [x] Click `Settings` and in repository settings uncheck `Wiki`, `Projects`, and `Discussions` (if they are currently not used)
  - [x] Click the settings icon next to `About` in the top-right corner of the repository main page and uncheck `Releases` and `Packages` (if they are currently not used)

### CODE REVIEW

**Comment by cpinter** [comment]
What is the current procedure @lassoan @jcfr ? Should I check the boxes myself or do I wait for someone to go through the checklist to see if everything is in order? I was assuming the latter but I can go through it myself no problem. Thanks!

**Review by lassoan — COMMENTED** [review]
This is great, this will be a very useful extension!

There are a couple of things to address. They are all trivial, but important to make the extension build and appear correctly in the extensions manager, and to make it easy for users to find and use it.
- scm revision is incorrect (see inline comment)
- icon and screenshot URLs are incorrect - https://github.com/cpinter/SlicerSegmentationVerification/blob/09c5279079e5015bc18f762d03283287434f04be/CMakeLists.txt#L10C1-L11C117
- homepage URL is incorrect - https://github.com/cpinter/SlicerSegmentationVerification/blob/09c5279079e5015bc18f762d03283287434f04be/CMakeLists.txt#L7
- mention the module name in https://github.com/cpinter/SlicerSegmentationVerification/blob/main/README.md
- add a very short tutorial section (link to sample data set that can be used for testing, what to click, why) - 
- Using [centerpoint of bounding box as segment position](https://github.com/cpinter/SlicerSegmentationVerification/blob/09c5279079e5015bc18f762d03283287434f04be/SegmentationVerification/SegmentationVerification.py#L336) is not ideal, because there may be nothing there (e.g., for paired organs), instead, you can use `segmentationNode.GetSegmentCenterRAS(selectedSegmentID)`, which provides a position that is guaranteed to be inside the segment
- Hide unused features in the repository (see checklist)

**Comment by cpinter** [comment]
Thank you very much for the review!

> scm revision is incorrect

I accepted the change and committed it from GitHub. My comment about this is that I don't remember changing it from main to master, and I assume that master is the default. If so, maybe it would be good to change the default, since lately main is the usual default branch name.

> icon and screenshot URLs are incorrect

There used to be a button called "Raw" on the GitHub page but it's not there anymore. I can find two types of download links. One is
`https://github.com/cpinter/SlicerSegmentationVerification/blob/main/SegmentationVerification.png?raw=true`
and the other (permalink) is
`https://github.com/cpinter/SlicerSegmentationVerification/blob/09c5279079e5015bc18f762d03283287434f04be/SegmentationVerification.png`
The first has an argument, and I'm not sure if this is a valid link like this. And the second is fixed to a certain revision, so I'd avoid that if possible. Please let me know.

**Comment by cpinter** [comment]
Everything should be fixed now.

**Comment by lassoan** [comment]
> I don't remember changing it from main to master, and I assume that master is the default.

Where did you get the default from? Was there a template somewhere or you used another json file as an example?

> it's a hassle constructing this manually

This is the download link that you have found:

https://github.com/cpinter/SlicerSegmentationVerification/blob/main/SegmentationVerification.png?raw=true

If you open it in a browser it takes you to the link that should work well (but I think URL arguments should work, too):

https://raw.githubusercontent.com/cpinter/SlicerSegmentationVerification/main/SegmentationVerification.png

This other link that you have found would not work, as it does not link to a .png file but to a .html page:

https://github.com/cpinter/SlicerSegmentationVerification/blob/09c5279079e5015bc18f762d03283287434f04be/SegmentationVerification.png

> Do you know what is the new anternative for the button they removed?

I don't know the specifics, but in general nobody wants to serve content for free, so deep linking like this is often prohibited by policy and made technically difficult/inconvenient to discourage people from doing it. But it might be also just some unfortunate GUI refactoring.

**Comment by cpinter** [comment]
> Where did you get the default from? Was there a template somewhere or you used another json file as an example?

Ah, very good point. I think I didn't find a template and just used another one. There is the source of the error, nevermind.

Thanks for the explanation about the direct link. I didn't notice the change of link in the URL bar. I'll use this method from now on.

It seems that all prerequisites are met. Unless you find any issue in the tutorial or elsewhere.

**Review by lassoan — APPROVED** [review]
This all looks good now, thank you!

**Pull request merged**
