### PR TITLE
ENH: Update ShapePopulationViewer from revision a1116a4a420441a4cb217…

### PR DESCRIPTION
**Pull request by laurapascal**
…9acbd116ab67d23094f to 2e40ae44196afa2bf412bb8d90777665d2446156

https://github.com/NIRALUser/ShapePopulationViewer/compare/a1116a4a420441a4cb2179acbd116ab67d23094f...2e40ae44196afa2bf412bb8d90777665d2446156

### CODE REVIEW

**Comment by fbudin69500** [comment]
@laurapascal : Could you add tests first, and make sure that you can run the tests from the main project build directory. Thanks!

**Comment by jcfr** [comment]
Hi @laurapascal What is the status on this ? Let us know if you have any questions, Thanks

**Comment by laurapascal** [comment]
Hi @jcfr ! 
The project has changed, so I have to modify a lot of things on Shape Population Viewer. So I will make an other pull request as soon as the new version will be ready.

Thank you for asking!

**Comment by jcfr** [comment]
Sounds good :+1:

**Pull request closed without merging**
