### PR TITLE
ENH: Add TorchIO extension [master]

### PR DESCRIPTION
**Pull request by fepegar**
Description:
TorchIO is a Python package containing a set of tools to efficiently
read, preprocess, sample, augment, and write 3D medical images in deep
learning applications written in PyTorch, including intensity and
spatial transforms for data augmentation and preprocessing. Transforms
include typical computer vision operations such as random affine
transformations and also domain-specific ones such as simulation of
intensity artifacts due to MRI magnetic field inhomogeneity or k-space
motion artifacts.

Contributors:
Fernando Pérez-García (University College London)

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click "Manage topics" on your repository's main page, on the left, near the top (just below the repository description). To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [x] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/master/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work.
Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.

### CODE REVIEW

**Comment by lassoan** [comment]
> What do you think of the gifs in the repo?

Those are nice. You could show a few of them in the Slicer extension's repository to make it prettier and more informative.

**Comment by fepegar** [comment]
> Click - no wheels
nibabel - wheel available
Numpy (already included in Slicer)
Python-deprecated - no wheels
SimpleITK (already included in Slicer)
torch - wheels available
torchvision - wheels only available for macOS and Linux with latest release. 0.5.0 release has wheels for all platforms
tqdm - wheel available

@jamesobutler I cleared the pip cache folder, updated Slicer and opened the module and this is the output in the console after clicking OK when prompted about installation. It looks like I can get away with try/catch approach. Do you agree?

```
Python 3.6.7 (default, Jun 10 2020, 23:07:12) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
>>> 
Loading Slicer RC file [/Users/fernando/.slicerrc.py]
Slicer RC file loaded [11/06/2020 15:15:10]
Collecting torchio
  Downloading torchio-0.16.24-py2.py3-none-any.whl (88 kB)
Collecting tqdm
  Downloading tqdm-4.46.1-py2.py3-none-any.whl (63 kB)
Requirement already satisfied: scipy in ./Slicer.app/Contents/lib/Python/lib/python3.6/site-packages (from torchio) (1.4.1)
Collecting Click>=7.0
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting Python-Deprecated
  Downloading Python-Deprecated-1.1.0.tar.gz (2.9 kB)
Collecting torchvision
  Downloading torchvision-0.6.0-cp36-cp36m-macosx_10_9_x86_64.whl (436 kB)
Requirement already satisfied: SimpleITK in ./Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/SimpleITK-2.0.0rc2.dev133-py3.6-macosx-10.11-x86_64.egg (from torchio) (2.0.0rc2.dev133)
Collecting nibabel
  Downloading nibabel-3.1.0-py3-none-any.whl (3.3 MB)
Collecting torch>=1.2
  Downloading torch-1.5.0-cp36-none-macosx_10_9_x86_64.whl (80.5 MB)
Requirement already satisfied: numpy in ./Slicer.app/Contents/lib/Python/lib/python3.6/site-packages (from torchio) (1.18.1)
Requirement already satisfied: pillow>=4.1.1 in ./Slicer.app/Contents/lib/Python/lib/python3.6/site-packages (from torchvision->torchio) (7.0.0)
Requirement already satisfied: packaging>=14.3 in ./Slicer.app/Contents/lib/Python/lib/python3.6/site-packages (from nibabel->torchio) (20.3)
Collecting future
  Downloading future-0.18.2.tar.gz (829 kB)
Requirement already satisfied: pyparsing>=2.0.2 in ./Slicer.app/Contents/lib/Python/lib/python3.6/site-packages (from packaging>=14.3->nibabel->torchio) (2.4.6)
Requirement already satisfied: six in ./Slicer.app/Contents/lib/Python/lib/python3.6/site-packages (from packaging>=14.3->nibabel->torchio) (1.14.0)
Building wheels for collected packages: Python-Deprecated, future
  Building wheel for Python-Deprecated (setup.py): started
  Building wheel for Python-Deprecated (setup.py): finished with status 'done'
  Created wheel for Python-Deprecated: filename=Python_Deprecated-1.1.0-py2.py3-none-any.whl size=3069 sha256=f3bbe614b7a78dd4241147d1ab037587878e7b8985d2a6cd6323f3ea0807737d
  Stored in directory: /Users/fernando/Library/Caches/pip/wheels/7b/77/f4/889fb222210030f42875d19bb55b64ea2b394428066fd3a6f4
  Building wheel for future (setup.py): started
  Building wheel for future (setup.py): finished with status 'done'
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491058 sha256=6c0af1a97d812b3f8634d6d9226dd458d4264e10c949237fa86b73ef4383557b
  Stored in directory: /Users/fernando/Library/Caches/pip/wheels/6e/9c/ed/4499c9865ac1002697793e0ae05ba6be33553d098f3347fb94
Successfully built Python-Deprecated future
Installing collected packages: tqdm, Click, Python-Deprecated, future, torch, torchvision, nibabel, torchio
  WARNING: The script tqdm is installed in '/Applications/Slicer.app/Contents/lib/Python/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts futurize and pasteurize are installed in '/Applications/Slicer.app/Contents/lib/Python/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts convert-caffe2-to-onnx and convert-onnx-to-caffe2 are installed in '/Applications/Slicer.app/Contents/lib/Python/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts nib-conform, nib-dicomfs, nib-diff, nib-ls, nib-nifti-dx, nib-tck2trk, nib-trk2tck and parrec2nii are installed in '/Applications/Slicer.app/Contents/lib/Python/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script torchio-transform is installed in '/Applications/Slicer.app/Contents/lib/Python/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed Click-7.1.2 Python-Deprecated-1.1.0 future-0.18.2 nibabel-3.1.0 torch-1.5.0 torchio-0.16.24 torchvision-0.6.0 tqdm-4.46.1
WARNING: You are using pip version 20.1; however, version 20.1.1 is available.
You should consider upgrading via the '/Applications/Slicer.app/Contents/bin/./python-real -m pip install --upgrade pip' command.
```

**Comment by jamesobutler** [comment]
I attempted to pip install `torchvision`, but it fails on Windows.
```
>>> slicer.util.pip_install("torchvision")
Collecting torchvision
  Using cached torchvision-0.5.0-cp36-cp36m-win_amd64.whl (1.2 MB)
Requirement already satisfied: numpy in c:\users\jamesbutler\appdata\local\na-mic\slicer 4.11.0-2020-06-10\lib\python\lib\site-packages (from torchvision) (1.18.1)
Requirement already satisfied: six in c:\users\jamesbutler\appdata\local\na-mic\slicer 4.11.0-2020-06-10\lib\python\lib\site-packages (from torchvision) (1.14.0)
Requirement already satisfied: pillow>=4.1.1 in c:\users\jamesbutler\appdata\local\na-mic\slicer 4.11.0-2020-06-10\lib\python\lib\site-packages (from torchvision) (7.0.0)
ERROR: Could not find a version that satisfies the requirement torch==1.4.0 (from torchvision) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.4.0 (from torchvision)
WARNING: You are using pip version 20.1; however, version 20.1.1 is available.
You should consider upgrading via the 'C:\Users\JamesButler\AppData\Local\NA-MIC\Slicer 4.11.0-2020-06-10\bin\python-real.exe -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\JamesButler\AppData\Local\NA-MIC\Slicer 4.11.0-2020-06-10\bin\Python\slicer\util.py", line 2424, in pip_install
    logProcessOutput(proc)
  File "C:\Users\JamesButler\AppData\Local\NA-MIC\Slicer 4.11.0-2020-06-10\bin\Python\slicer\util.py", line 2377, in logProcessOutput
    raise CalledProcessError(retcode, proc.args, output=proc.stdout, stderr=proc.stderr)
subprocess.CalledProcessError: Command '['C:/Users/JamesButler/AppData/Local/NA-MIC/Slicer 4.11.0-2020-06-10/bin/../bin\\PythonSlicer.EXE', '-m', 'pip', 'install', 'torchvision']' returned non-zero exit status 1.
```

**Comment by fepegar** [comment]
It looks that it can't install `torchvision` because it can't install PyTorch.

```
ERROR: Could not find a version that satisfies the requirement torch==1.4.0 (from torchvision) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.4.0 (from torchvision)
```

I guess that means I'll need to try the SuperBuild way.

**Comment by jamesobutler** [comment]
More specifically, if you want it available on Windows it looks like you're going to have to set it up to build `torch` from source (see https://github.com/pytorch/pytorch#from-source).

**Comment by lassoan** [comment]
You can download Pytorch wheels for Windows from the official site by using pip install. You can generate the install command on this page: https://pytorch.org/get-started/locally/

For example, this command worked well for installing pytorch within Slicer 4.11.0-2020-06-09 (revision 29122 / a401747) win-amd64:

    pip_install("torch===1.5.0 torchvision===0.6.0 -f https://download.pytorch.org/whl/torch_stable.html")

Bundling Pytorch with the extension package would not be feasible, as the Windows wheel is 900MB, and we don't know which pytorch version users will want to use.

**Comment by jamesobutler** [comment]
`Bundling Pytorch with the extension package would not be feasible, as the Windows wheel is 900MB, and we don't know which pytorch version users will want to use.`

Are you saying this module in Slicer will/should have a user selectable pytorch version? Otherwise it would seem like users won't have an option and it will be up to the version specified in the extension which would be like having the package bundled with the extension by the factory build machine unless the expectation is for users to manually modify the extension files to pick the pytorch version that they will want to use?

**Comment by lassoan** [comment]
> Are you saying this module in Slicer will/should have a user selectable pytorch version?

That's a good idea. But probably it would be enough to offer installation of some default version and in the confirmation popup window tell the user something like: "if you want a different version then click Cancel and install your preferred version before using this module".

**Comment by fepegar** [comment]
Tutorial added in https://torchio.readthedocs.io/slicer.html#usage-example

I've also addressed your suggestions about PyTorch, pip and Windows in https://github.com/fepegar/SlicerTorchIO/commit/4f97b13d07e58165ae560e0ae164816fd43575bc

**Comment by jamesobutler** [comment]
@fepegar If you are using macOS are you using torch without CUDA support? It appears that the wheels for macOS likely don’t have this support since most Apple machines have AMD GPUs instead one from nVidia. I noticed that the Windows download that you are currently using `pip install torch===1.5.0 torchvision===0.6.0 -f https://download.pytorch.org/whl/torch_stable.html` is actually for the torch package that has the CUDA 10.2 support. I’m not sure what would happen if a Windows user doesn’t have a discrete GPU, doesn’t have an nVidia GPU or doesn’t have the nVidia drivers that support 10.2. There is a CPU version `pip install torch==1.5.1+cpu torchvision==0.6.1+cpu -f https://download.pytorch.org/whl/torch_stable.html` and wasn’t sure if this is essentially what you’re using on macOS. It seems like the safe choice would be the CPU only version or support the download of the CUDA versions but with documentation for users about hardware/driver requirements.

**Comment by fepegar** [comment]
The extension shouldn't need CUDA as all operations are performed on CPU. I'll modify the calls to `pip_install`.

**Comment by fepegar** [comment]
Done. Installation should be much lighter now that the CUDA toolkit doesn't need to be downloaded.

**Comment by fepegar** [comment]
Please let me know if there's anything else left to do for me.

**Comment by lassoan** [comment]
This all looks great, I'll merge now.

There is only one thing I've found (but that does not prevent merge): please update https://github.com/fepegar/SlicerTorchIO/blob/master/CMakeLists.txt with the same content (links, description, etc.) as in the submitted s4ext file.

**Comment by fepegar** [comment]
Great, thanks! I've updated that file, but there's a discrepancy in the extension homepage I'll submit a PR here.

Many thanks @lassoan and @jamesobutler for your guidance!

**Pull request merged**
