### PR TITLE
Renaming extension to SlicerPinholeCameras

### PR DESCRIPTION
**Pull request by adamrankin**

### CODE REVIEW

**Review by pieper — APPROVED** [review]
LGTM

**Comment by pieper** [comment]
There's a CI failure but it seems unrelated.  I believe we can override the commit check here.  @lassoan @jcfr do you agree?

**Comment by jcfr** [comment]
Thanks for the ping. Will have a look in 20mins or so.

**Comment by jcfr** [comment]
I rebased the branch against current master and forced push

**Review by jcfr — APPROVED** [review]

**Pull request merged**
