### PR TITLE
Add SlicerFreeSurferImporter extension

### PR DESCRIPTION
**Pull request by Sunderlandkyl**
Description:
>Extension for handling FreeSurfer files in Slicer. Features importer for models, scalar overlay, and segmentations. Handles transformation of models from FreeSurfer to Slicer world coordinates.

Contributors:
> Kyle Sunderland (PerkLab, Queen's University), Andras Lasso (PerkLab, Queen's University)

# TODO list for submitting a new extension

[To make sure users can find your extension, understand what it is intended for and how to use it, please complete the checklist below. You do not need to complete all the item by the time you submit the pull request, but most likely the changes will only be merged if all the tasks are done. See more information about the submission process on the Slicer wiki: https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/BuildTestPackageDistributeExtensions]

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click "Manage topics" on your repository's main page, on the left, near the top (just below the repository description). To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following: (https://github.com/PerkLab/SlicerFreeSurferImporter)
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [x] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/master/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work.
Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.

The eventual goal of this extension will be to contain all FreeSurfer related classes from Slicer (See discussion here: https://discourse.slicer.org/t/moving-freesurfer-support-to-an-extension/9390/5). Currently it just contains some additional file readers and a module for importing multiple files from a FreeSurfer project at a time.

### CODE REVIEW

**Comment by lassoan** [comment]
Thanks a lot Kyle. Sorry for not reviewing this earlier. It all looks good, except the extension name (FreeSurferImporter) is not ideal. I would expect that the extension will handle all kinds of FreeSurfer related things in the future and it would be better if we could keep its name.

Could you rename it to SlicerFreeSurfer? We did this for other extensions, which implement interfaces to other software packages (such as SlicerElastix, SlicerJupyter, SlicerIGSIO, SlicerVMTK).

**Comment by Sunderlandkyl** [comment]
OK, sounds good. Rename should be done shortly.

**Comment by Sunderlandkyl** [comment]
Rename done in a854cd29a9e54af38f812ff90ad6bb7868ba7465 and https://github.com/PerkLab/SlicerFreeSurfer/commit/59c5c94f1f16bb4fa45e7bc0c968bd13cdb0c970.

**Comment by lassoan** [comment]
Perfect, thank you!

If the extension build succeeds on all platforms then the next step could be moving freesurfer model, overlay, and color nodes (and their storage nodes) into this extension.

**Pull request merged**
