### PR TITLE
Added Sequence Registration extension

### PR DESCRIPTION
**Pull request by moselhy**

### CODE REVIEW

**Comment by lassoan** [comment]
SequenceRegistration will be a very useful extension. It would be important to touch up a few things to make sure users will be able find your extension and figure out how to use it:

- [ ] The repository name should be SlicerSequenceRegistration to make it clear for developers that it is an extension for 3D Slicer. 
- [ ] The repository should not contain large binary data sets. SampleData module will contain sample sequence data sets (in the nightly version of Aug 12 and later, see this module: https://github.com/SlicerRt/Sequences/tree/master/SequenceSampleData). You can load the data set in tests/examples like this: ```import SampleData; SampleData.SampleDataLogic().downloadSample('CTPCardio')```
- [ ] Change category to Sequences. For now, not too many operations are directly supported for volume sequences, so it is more likely that users will find 4D features in this category.
- [ ] Fix extension logo (https://github.com/moselhy/SequenceRegistration/blob/master/SequenceRegistration.png)
- [ ] Create basic documentation: add short tutorial (that explains where to get sample data from, how to set up the registration, and what to do with the results), reference documentation (description of module GUI and how to use it) to https://github.com/moselhy/SequenceRegistration/blob/master/README.md
- [ ] Add an automatic test. It should be just a smoke test - to detect if something is completely broken (no output is generated, exception is thrown, etc). It should not be longer than 2-3 minutes, so you may downsample the volume and/or register only 2-3 time points.

**Comment by fedorov** [comment]
> The repository should not contain large binary data sets.

Note that it is not sufficient to delete the files with `git rm`. You actually need to delete them from the history. I have not done this myself, but this guide might be helpful: https://www.clock.co.uk/insight/deleting-a-git-commit.

**Comment by moselhy** [comment]
- [x]  The repository name should be SlicerSequenceRegistration to make it clear for developers that it is an extension for 3D Slicer.
- [x]  The repository should not contain large binary data sets. SampleData module will contain sample sequence data sets (in the nightly version of Aug 12 and later, see this module: https://github.com/SlicerRt/Sequences/tree/master/SequenceSampleData). You can load the data set in tests/examples like this: import SampleData; SampleData.SampleDataLogic().downloadSample('CTPCardio')
- [x]  Change category to Sequences. For now, not too many operations are directly supported for volume sequences, so it is more likely that users will find 4D features in this category.
- [x]  Fix extension logo (https://github.com/moselhy/SequenceRegistration/blob/master/SequenceRegistration.png)
- [ ]  Create basic documentation: add short tutorial (that explains where to get sample data from, how to set up the registration, and what to do with the results), reference documentation (description of module GUI and how to use it) to https://github.com/moselhy/SequenceRegistration/blob/master/README.md
- [ ]  Add an automatic test. It should be just a smoke test - to detect if something is completely broken (no output is generated, exception is thrown, etc). It should not be longer than 2-3 minutes, so you may downsample the volume and/or register only 2-3 time points.

> You actually need to delete them from the history

Thanks @fedorov, I will look into that

**Comment by moselhy** [comment]
Done!

**Comment by lassoan** [comment]
Thanks a lot. Nice work!

**Comment by lassoan** [comment]
@moselhy I've tested the extension on Windows and it worked well, except saving of transforms. There was a bug in Sequences module that I've fixed now, so tomorrow it should all work perfectly. I've touched up the documentation a bit.

Last issue is packaging of SlicerElastix on Mac.

@jcfr - did you have a change to have a look at this problem in SlicerElastix?

**Pull request merged**
