### PR TITLE
Add SlicerLungDensitySegmentation.s4ext

### PR DESCRIPTION
**Pull request by pzaffino**
Thank you for contributing to 3D Slicer!

- **To add a new extension with this pull request**: Please keep content of "TODO list for submitting a new extension" section and put an 'x' character in the brackets for each todo item to indicate that you have accomplished that prerequisite.

- **To update an existing extension with this pull request**: Please delete all text in this template and just describe which extension is updated and optionally tell us in a sentence what has been changed. To make extension updates easier in the future (so that you don't have to submit a new pull request after each change in your extension), you may consider replacing specific git hash in your s4ext file by a branch name (for example: `master` or `release` for nightly version; `(majorVersion).(minorVersion)` such as `4.10` for stable Slicer version).

# TODO list for submitting a new extension

[To make sure users can find your extension, understand what it is intended for and how to use it, please complete the checklist below. You do not need to complete all the item by the time you submit the pull request, but most likely the changes will only be merged if all the tasks are done. See more information about the submission process here: https://slicer.readthedocs.io/en/latest/developer_guide/extensions.html]

- [ ] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [ ] Any known related patents must be mentioned in the extension description.
- [x] If source code license is more restrictive for users than BSD, MIT, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://github.com/user/project/raw/main/path/to/icon.png)
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [ ] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [x] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/master/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [ ] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)

[If you have any questions or comments then please describe them here.]

### CODE REVIEW

**Comment by lassoan** [comment]
Thanks a lot for your contribution. I've tested the extension and it works nicely (I just checked on the DemoChestCT data set it gave meaningful results; it did not separate the trachea and the vessels label included parts of the heart and spine, but I'm not sure if it is a problem for clinical use).

There are a couple of things to improve to make sure that the extension is easy to discover and use and can be maintained with reasonable effort in the long term:

- [ ] Extension has a reasonable name: The current name is not specific enough: it should include CT in its name, as it only applicable to CT, and it should have something distinctive in its name (maybe GMM?). But it would be even better to just add it to https://github.com/rbumm/SlicerLungCTAnalyzer extension. If we have many tiny extensions then we make it harder for users to find them and figure out which one is good for what. In the mid/long term, we should probably merge LungCTAnalyzer and ChestImagingPlatform into a single SlicerLung extension (and make sure the modules are compatible - output of one module can be used as input in other modules).
- [ ] Homepage URL points to valid webpage: We are in the process of retiring the Slicer wiki. We are moving Slicer core documentation to readthedocs and host extension documentation in each extension's repository. It would save is time if you created the documentation to your repository as markdown file(s).
- [ ] Import of packages should not be performed when the module is loaded (https://github.com/pzaffino/SlicerLungDensitySegmentation/blob/main/LungDensitySegmentation/LungDensitySegmentation.py#L16), but at the latest possible time when those external packages are actually needed. If the packages are big then there should be a user prompt. Otherwise it can be a silent install in the module logic. 
- [ ] Module name is mistyped: "Density lung segmentation" (word order is off)
- [ ] The module fails on CTChest data set with an assert (`Slicer-4.13/qt-scripted-modules/LungDensitySegmentation.py", line 229, in bbox    assert coords[1] <= img.shape[0]-1 and coords[3] <= img.shape[1]-1 and coords[5] <= img.shape[2]-1 AssertionError`). At least a meaningful error message should be displayed to the user.
- [ ] Remove the dummy test (preferable replace it with an actual test).
- [ ] Add link to full text of the paper (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7919807/) on the module homepage.
- [ ] Add link to module homepage from the module help text.
- [ ] Set base name for the output node selectors (now output nodes are named as "LabelMapVolume" and 
LabelMapVolume_1" by default, which is not informative)
- [ ] Allow choosing segmentation node as output
- [ ] If you want to keep label volume output option then make sure the label values are set to meaningful values (currently it is vessels, jake, peach, brain, ventricles, ...). For compatibility with LungCT analysis and CIP extensions, use the CIP color table (see how to create a color table with custom values that match CIP values [here](https://github.com/rbumm/SlicerLungCTAnalyzer/blob/master/LungCTSegmenter/LungCTSegmenter.py#L1156-L1166)).
- [ ] Describe the expected computation time (for me it was surprising that segmentation took several minutes; I almost gave up). 
- [ ] Tutorial must provide a data set that the module works with. For example, ask users to install LungCTAnalyzer extension and then use the DemoChestCT data set in Sample Data module (the extension registers additional sample data).

**Comment by pzaffino** [comment]
Thanks @lassoan !

I implemented almost all the comments you made (I updated both my repository and my Extension index fork).
For some of those here my comments/response:

* At least for the moment, I would keep this extension separate.

* Regarding the output I would prefer labelmaps. Since the labeled tissues are not so common, I didn't assign a value fitting the slicer index list for the tissues (ground glass, consolidation, and air are missing).

* I don't know how to create a readthedoc page

All the other points should be fixed.

Thank you again :)

Paolo

**Comment by lassoan** [comment]
> At least for the moment, I would keep this extension separate.

We are trying to prevent proliferation of many small extensions, because it significantly increases the maintenance burden for both extension developers and Slicer core developers. Sharing an extension between multiple groups also promotes collaboration and makes the burden of user support more manageable.

Can you explain what are the main motivations for adding this module into a separate extension? Understanding this could help us removing the potential roadblocks in the infrastructure (e.g., if you want to make it more visible which groups contributed to an extension, search for an extension by contributors, ... these should be all possible to address).

> Regarding the output I would prefer labelmaps. Since the labeled tissues are not so common, I didn't assign a value fitting the slicer index list for the tissues (ground glass, consolidation, and air are missing).

Labelmaps have many issues.

For example, it is clearly impossible to have a single common color table that works across different applications and contains all necessary structures. Segmentation node solves this problem beautifully, by allowing specifying content of a segment using standard terminologies (SNOMED CT, DICOM, etc.). For ground glass opacity, you can use the [(DCM, 112120, Ground glass opacity)](http://dicom.nema.org/medical/Dicom/2016b/output/chtml/part16/sect_CID_6104.html) term) and then you can map this term to any label value when you process or display the segmentation. We will use this approach to make sure that all Slicer modules in all extensions are interoperable, despite they use different color tables internally. You can add terms that are not bundled with Slicer in your extension in a [segmentation terminology json file](https://slicer.readthedocs.io/en/latest/user_guide/modules/terminologies.html#how-to) and load it using `slicer.modules.terminologies.logic().LoadTerminologyFromFile()` method. We can help with this, just let us know if you get stuck.

Labelmap volumes have many other other limitations, such as no support for overlapping labels, difficulty in displaying them in 3D, quickly toggle visibility of segments, ... and of course incompatibility with all other modules that use segmentation nodes.

It is acceptable for legacy modules to keep using labelmap volumes, but new modules should accept/generate segmentations (in addition to optionally support labelmaps, too). Creating segmentation output is really easy to do, for example you can generate a segmentation node by converting your labelmap volume by a [few lines of code](https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#create-a-segmentation-from-a-labelmap-volume-and-display-in-3d).

> I don't know how to create a readthedoc page

You don't need to create documentation on readthedocs. [Slicer core documentation is being moved to readthedocs](https://slicer.readthedocs.io/en/latest/) and the [Slicer wiki](https://www.slicer.org/wiki/Documentation/Nightly) is being phased out. Your extension documentation should be kept with your source code, in the same repository, maintained at one place, together (whenever you update the code, update the documentation as needed). This happens typically by documenting the extension in the README.md file - that you already have [here](https://github.com/pzaffino/SlicerDensityLungSegmentation#readme). Sometimes large extensions create complex page hierarchies that can be rendered more nicely in github pages or readthedocs, but there are only a few of these.

In the future we may include these README.md files into the Slicer documentation on readthedocs so that they can be easily searched for, but it will not require any action from extension developers.

**Comment by pzaffino** [comment]
Thanks @lassoan 

The README.md file is already there, filled with all the required information, so I think/hope this is done.

I edited the code and now the results are segmentation (each segment has a consistent name).

Regarding the extension, I think it's better to keep it separate because it's really for a well precise task/pathology.
It's not for lungs in general, but for lungs with pneumonia (we tested only for covid).
I think it's easier for the user to find it. It could lose visibility if we put into a large project that can be several other tasks,
We want also to keep it strictly linked with the paper that describes its rationale.

Thanks a lot.
Paolo

**Comment by lassoan** [comment]
Things to fix before integration
- [ ] Confirm that there are no related patents that you know of.
- [ ] Update homepage link in CMakeLists.txt tp github (Slicer MediaWiki will go away)
- [ ] Fix [link to homepage in module help text](https://github.com/pzaffino/SlicerDensityLungSegmentation/blob/main/LungCTGMMSegmentation/LungCTGMMSegmentation.py#L31)
- [ ] Update the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc.) to match content of the submitted s4ext file.

Enhancements (not required to fix before the integration, I'll submit all the remaining tasks to the repository's issue tracker):
- [ ] Register a sample data set that downloads a concrete lung CT and use that in the tutorial
- [ ] Add wait cursor when starting the processing
- [ ] Instead of adding "It can take some minutes" to the Apply button, add a label and show some status updates there. You can start out displaying "It can take some minutes", but provide updates as the processing goes.
- [ ] Processing fails for standard CTChest data set. The user needs a meaningful explanation why the processing has failed and what to do about it.

**Comment by pzaffino** [comment]
Thanks @lassoan 
I updated both repositories. Now the points to be fixed before the integration should be all addressed.
I confirm that, as far as I know, there are no patents on this.

Thanks for the suggestions about the enhancements, I'll implement them asap.

Best,
Paolo

**Comment by lassoan** [comment]
Awesome, thank you, you are all set. I'll merge the pull request now.

**Comment by lassoan** [comment]
I've moved the remaining enhancement suggestions to https://github.com/pzaffino/SlicerDensityLungSegmentation/issues/1

**Pull request merged**
