### PR TITLE
Update TrackerStabilizer

### PR DESCRIPTION
**Pull request by lchauvin**
Changed code structure, slightly improved UI, added a MRML node and modified filtering to avoid gimbal lock (Andras)

https://github.com/SlicerIGT/TrackerStabilizer/compare/cae960ae5c2...master

### CODE REVIEW

**Comment by jcfr** [comment]
FYI - There is a Slerp function in vtkQuaternion.
See https://github.com/Kitware/VTK/blob/cdbec3e4f1dfe74556ddf27580b44a86d2ebcc94/Common/Math/vtkQuaternion.h#L190

Would that be helpful ?

**Comment by jcfr** [comment]
Note for later: Make sure to create a branch named `update-TrackerStabilizer` instead of creating the PR directly of master.

**Comment by lchauvin** [comment]
Oh yes, sorry I forgot. Thanks for reminding me.

**Comment by lchauvin** [comment]
Oh yes you're right. I will look into it, and if I got same results (which should be the case), maybe replace it.

Thank you.

**Pull request merged**
