### PR TITLE
Remove unsupported extension CardiacAgatstonMeasures

### PR DESCRIPTION
**Pull request by hjmjohnson**
Remove broken module with no support for updating. 

Related to https://github.com/Slicer/Slicer/pull/4904

### CODE REVIEW

**Comment by jcfr** [comment]
The CI was red, this shouldn't have been merged:

image


Would it be possible to fix it ? :pray:

**Comment by jcfr** [comment]
To mitigate this, I added a rule protecting the master branch and requiring the CI check to be green.

**Comment by jcfr** [comment]
I am working on a fix :smile:

**Comment by fedorov** [comment]
@jcfr I am sorry sorry for ignoring the failing test and causing this problem. I should not have merged it.

**Comment by jcfr** [comment]
No problem at all, tooling has been improved. :) 

@hjmjohnson thanks for creating the archive folder, that is a great idea.

**Pull request merged**
