### PR TITLE
Add SlicerAutomatedDentalTools extension

### PR DESCRIPTION
**Pull request by Maxlo24**
# New extension

- [X] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [X] Repository name is Slicer+ExtensionName
- [X] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [X] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [X] Any known related patents must be mentioned in the extension description.
- [X] If source code license is more restrictive for users than BSD, MIT, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [X] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (main, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [X] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://raw.githubusercontent.com/user/repo/main/SomeIcon.png)
- [X] Screenshot URLs (screenshoturls) are correct, contains at least one
- [X] Homepage URL points to valid webpage containing the following:
  - [X] Extension name
  - [X] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [X] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [X] Description of contained modules: at one sentence for each module
  - [X] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [ ] Publication: link to publication and/or to PubMed reference (if available)
  - [X] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/main/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [X] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)

### CODE REVIEW

**Comment by Maxlo24** [comment]
Deployment of the SlicerAutomatedDentalTools extension

**Comment by jcfr** [comment]
Few preliminary comments:

### Transfer repositories 

* consider transferring the following repositories to the [DCBIA-OrthoLab](https://github.com/DCBIA-OrthoLab) GitHub organization. Doing so will ensure the tools can be maintained over time by allowing members in the organization to grant/revoke access as needed.
  * https://github.com/Maxlo24/SlicerAutomatedDentalTools
  * https://github.com/Maxlo24/ALI_CBCT
  * https://github.com/Maxlo24/AMASSS_CBCT

Attempting to configure the extension is currently failing

### Fix `project()` statement

```
cd /tmp
git clone git@github.com:Maxlo24/SlicerAutomatedDentalTools.git
cmake \
  -DSlicer_DIR:PATH=/home/jcfr/Projects/Slicer-Release/Slicer-build \
  -DCMAKE_BUILD_TYPE:STRING=Release \
  -S /tmp/SlicerAutomatedDentalTools \
  -B /tmp/SlicerAutomatedDentalTool-Release
```

It turns error like the following:

```
CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_Automatic_COMPILER could be found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_Automatic_COMPILER to the full path to the compiler, or to the
  compiler name if it is in the PATH.

```

This is most likely to an incorrect project name.

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 914ea4e..5e65b5c 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,6 +1,6 @@
 cmake_minimum_required(VERSION 3.16.3...3.19.7 FATAL_ERROR)
 
-project(Slicer Automatic Ortho Tools)
+project(SlicerAutomatedDentalTools)
 
 #-----------------------------------------------------------------------------
 # Extension meta-information
```


### Issue with ALI module

After fixing the `project()` statement, the following error is reported:

```
CMake Error at /home/jcfr/Projects/Slicer/CMake/SlicerMacroBuildScriptedModule.cmake:78 (message):
  slicerMacroBuildScriptedModule(SCRIPTS) given nonexistent file or directory
  'UI_fct.py'
Call Stack (most recent call first):
  ALI/CMakeLists.txt:16 (slicerMacroBuildScriptedModule)

```

**Comment by jcfr** [comment]
Looks like there are still issue, doing a clean build report the following:

```
CMake Error at /home/jcfr/Projects/Slicer-Release/SlicerExecutionModel/CMake/SEMMacroBuildCLI.cmake:126 (add_library):
  Cannot find source file:

    AMASSS_CLI.cxx

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
Call Stack (most recent call first):
  AMASSS_CLI/CMakeLists.txt:5 (SEMMacroBuildCLI)


CMake Error at /home/jcfr/Projects/Slicer-Release/SlicerExecutionModel/CMake/SEMMacroBuildCLI.cmake:126 (add_library):
  No SOURCES given to target: AMASSS_CLILib
Call Stack (most recent call first):
  AMASSS_CLI/CMakeLists.txt:5 (SEMMacroBuildCLI)
```

Considering using a command like the following to test:

```
cd /tmp
git clone git@github.com:Maxlo24/SlicerAutomatedDentalTools.git
cmake \
  -DSlicer_DIR:PATH=/home/jcfr/Projects/Slicer-Release/Slicer-build \
  -DCMAKE_BUILD_TYPE:STRING=Release \
  -S /tmp/SlicerAutomatedDentalTools \
  -B /tmp/SlicerAutomatedDentalTools-Release
```

Then the following to build:

```
cmake \
  --build /tmp/SlicerAutomatedDentalTools-Release \
  --config Release
```

**Comment by Maxlo24** [comment]
I have not been able to test, I don't know which slicer I have to download to be able to do this line
```
DSlicer_DIR:PATH=/home/jcfr/Projects/Slicer-Release/Slicer-build 
```
I cant find any folder with " Slicer-Release/Slicer-build " in it 

but I made changes on the cli cmake following other extention, I hope it's working this time.

Also the code as been forked on [DCBIA-OrthoLab](https://github.com/DCBIA-OrthoLab)

**Comment by jcfr** [comment]
> Also the code as been forked on DCBIA-OrthoLab

Consider deleting the forks, transferring the projects to the organization and then forking them from your personal account is what I would strongly recommend.

That way,  the authoritative repositories will be the one from the [DCBIA-OrthoLab](https://github.com/DCBIA-OrthoLab) organization and this would be more accurately represent the collaborative nature of the project. 


> not been able to test [...]

To test, you have to have a build of a recent build of Slicer. The path "
Slicer-Release/Slicer-build" is what I have on my workstation. 

In your case, you should be able to infer the path based on where you built Slicer.

See https://slicer.readthedocs.io/en/latest/developer_guide/extensions.html#build-an-extension

cc: @baptistebaquero

**Review by jcfr — CHANGES_REQUESTED** [review]
Building the extension should be tested against a Slicer build tree and repository transferred to the lab organization.

See https://github.com/Slicer/ExtensionsIndex/pull/1865#issuecomment-1190619121

**Review by jamesobutler — COMMENTED** [review]
You will need to update icon and screenshot urls at places like https://github.com/DCBIA-OrthoLab/SlicerAutomatedDentalTools/blob/a8d0e08dcc31e363160af7809f571208767b5811/CMakeLists.txt#L11-L12
to be of the raw.githubusercontent type link. This makes sure the icon and screenshots are appropriately rendered in the ExtensionsManager. You can go to the link like https://github.com/Maxlo24/SlicerAutomatedDentalTools/blob/main/SlicerAutomaticTools.png?raw=true and it will then redirect and show you the raw.githubusercontent link address.
```diff
- set(EXTENSION_ICONURL "https://github.com/Maxlo24/SlicerAutomatedDentalTools/blob/main/SlicerAutomaticTools.png")
+ set(EXTENSION_ICONURL "https://raw.githubusercontent.com/DCBIA-OrthoLab/SlicerAutomatedDentalTools/main/SlicerAutomaticTools.png")
```

**Comment by Maxlo24** [comment]
Changes made

**Comment by Maxlo24** [comment]
Cmake Updated to correct the build error

The extension should be ready now @jcfr @jamesobutler

**Comment by hina-shah** [comment]
@jcfr : Can you please take a look and merge this pull request?

**Comment by lucanchling** [comment]
@jcfr @allemangD 
I've addressed the additional request to remove the unnecessary pip_install instances
Please review and merge it to deploy this extension

**Comment by allemangD** [comment]
@lucanchling I see you've pushed those changes to your fork (https://github.com/lucanchling/SlicerAutomatedDentalTools), but they aren't present in upstream (https://github.com/DCBIA-OrthoLab/SlicerAutomatedDentalTools).

From what I can see the changes look good, you just need to open a PR to get those changes merged, then I can accept this PR.

**Comment by lucanchling** [comment]
The changes have been merged to the upstream (DCBIA repository)
Please let me know if you can accept this PR @allemangD 
Thanks

**Comment by allemangD** [comment]
Thanks @lucanchling 🚀

**Pull request merged**
