### PR TITLE
Adding SlicerCamera extension

### PR DESCRIPTION
**Pull request by adamrankin**
For nightly release

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for the contribution.

Few comments .. 

Should the extension be renamed `SlicerVideoCamera` ? 
Or should the logo be updated ? 

* [ ] update screenshot (currently link to http://www.example.com/Slicer/Extensions/SlicerCamera/Screenshots/1.png)

As a side note, would it be possible to link a 128x128 version of the logo.

**Comment by lassoan** [comment]
It looks all good except the extension name should be more specific. For example VideoCamera or CameraCalibration would be good extension names. Recommended repository name is the extension name prefixed with "Slicer".

**Comment by adamrankin** [comment]
Would SlicerCameras be ok (extension name "Cameras")? I know not much difference between Webcams and Cameras but in these tools apply to still cameras as well as video cameras.

**Comment by lassoan** [comment]
Camera term is already taken by VTK and Slicer core. For me, VideoCamera term is distinct enough and indicates that it is about optical cameras and not about virtual rendering cameras. Maybe we can find other terms, if you don't like VideoCamera.

**Comment by adamrankin** [comment]
Agreed, sticking with `Webcam`

**Comment by lassoan** [comment]
Sorry for taking so much time with finding a good name, but a good name makes a huge difference, and it is hard to change in the future (it cause errors in dependent extensions, users cannot find it, extension statistics cannot be aggregated, etc).

Are the algorithms specify developed to work on webcams (i.e., low-cost, low-quality video cameras) or they are applicable to high-end optics as well (endoscope, DSLR, etc)?

**Comment by pieper** [comment]
CameraModels or CameraModeling would give me a better idea of what it is.

**Comment by adamrankin** [comment]
Well, the key question is, is SlicerCameras out? Because that is the best name for the extension, as it is focused around calibration, use, and manipulation of cameras. 

Second best would be Webcams, but that incorrectly dissuades from DSLRs, endoscopes, etc... which are valid candidates for the tools within.

**Comment by fedorov** [comment]
Looking from the outside, after reading this discussion, I find the SlicerWebcams name rather misleading.

**Comment by fedorov** [comment]
+1 for CameraCalibration

**Comment by pieper** [comment]
I like CameraCalibration.  Another option might be CameraMathematics

**Comment by adamrankin** [comment]
The extension is more than just calibration though. VideoCameras is also misleading as it works for still cameras as well.

PinholeCameras is not bad.

What about Optics (SlicerOptics repo name)? Or Optical Cameras?

**Comment by adamrankin** [comment]
Ok, final decision of VideoCameras (repo SlicerVideoCameras)?

**Comment by adamrankin** [comment]
@jcfr I think you're the final say on naming.

**Comment by adamrankin** [comment]
Ok, renamed. If possible could this be merged before tomorrow's nightly build?

**Comment by lassoan** [comment]
Icon and screenshot URLs are invalid (for example, correct icon URL would be: https://raw.githubusercontent.com/VASST/SlicerVideoCameras/master/SlicerVideoCameras_128.png). Could you please fix them?

**Comment by lassoan** [comment]
Merged. Thank you for your contribution!

Note that the git hash was hard-coded in the s4ext file, so your latest fixes are not included. I would recommend to replace the git hash by branch name (master) to avoid the need of manually updating the extension index each time you change your extension.

**Pull request merged**
