### PR TITLE
Add AtlasEditor extension

### PR DESCRIPTION
**Pull request by andy9t7**
# New extension

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Any known related patents must be mentioned in the extension description.
- [x] LICENSE.txt is present in the repository root. MIT  (https://choosealicense.com/licenses/mit/) or Apache (https://choosealicense.com/licenses/apache-2.0/) license is recommended. If source code license is more restrictive for users than MIT, BSD, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (main, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://raw.githubusercontent.com/user/repo/main/SomeIcon.png)
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [ ] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/main/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [x] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)

Publication - N/A

### CODE REVIEW

**Comment by lassoan** [comment]
I haven't had a chance to review thoroughly, but it looks great.

Before filling into the details - what is the reason for adding this module into a new extension? We created the SlicerOpenAnatomy extension to host all authoring tools for the OpenAnatomy project. It is important to make it easy for users to find and install OpenAnatomy tools and minimize the overhead for developers, so a single extension would be highly beneficial for everyone. 

You can get direct write access to that repository and we can even move the repository into some OpenAnatomy organization. If you find that the current "OpenAnatomy exporter" module has confusing name because it does not export into the new atlas format yet then we can rename or improve the implementation to generate the correct file content.

**Comment by lassoan** [comment]
We could also enhance your module to work with segmentation nodes, so that you can see the atlas in 3D and allow more segment editing operations. The hierarchy information could be stored as segment tags (tags can store a list of key/value pairs for each segment) or we could just store some ID in the segment tag to link the segment to the OpenAnatomy metadata.

We should probably have a quick meeting about this. Let me know when you are available. We should invite Mike Halle, too.

**Comment by andy9t7** [comment]
Hi Andras,

Thanks for the quick response.

I have been using some python scripts to merge/remove single label structures together because the original atlas had too many structures, especially for a project I am working on (discretising these atlases into finite element meshes). Originally, I wanted to have a way to simplify the brain atlas to contain less structures, by merging them into groups of interest. For example, one larger part of the brain is the cerebellum - however, it does not contain its own label but consists of about 50 labels. A way to merge these 50 labels into one called 'cerebellum' is useful along with other larger parts of the brain. I have been using a specific [JSON schema](https://github.com/stity/atlas-schema) that Open Anatomy atlases uses to group their data in a hierarchal structure. So this extension should work on all their atlases (I've only tested the brain atlas).  

merge-cerebellum

After discussing with Mike at NA-MIC project week, we both agreed that it would be useful in general to have a tool that can merge/union label structures. I decided to move my existing python scripts into a Slicer extension for both my own learning experience but also as a tool that may be useful for others. 

I agree, we should simplify things by having a single extension - I am more than happy to follow to your advice on this. An Open Anatomy organisation sounds like a good idea - I have many ideas/small projects that I would love to work on involving the atlases.

Yes, visualising would help with the user experience and extra features for editing the atlas is a good idea. I was hoping that users can also group these labels in their own way as well, so storing this metadata inside the segment or 'atlas' itself instead of using JSON structure file sounds ideal.

Lets talk more! I will organise a meeting with you and Mike.

Thanks again Andras!!

Andy

**Comment by jcfr** [comment]
A tip when editing markdown:

```diff
- - [ x] Repository name is Slicer+ExtensionName
+ - [x] Repository name is Slicer+ExtensionName
```

| Before | After |
|--|--|
| image | image |

**Comment by jcfr** [comment]
> I will organise a meeting with you and Mike.

@andy9t7 Did you have a chance to move forward with this ? What is the current status ?

**Comment by lassoan** [comment]
The [AtlasEditor module](https://github.com/PerkLab/SlicerOpenAnatomy/blob/master/AtlasEditor/README.md) has been integrated into SlicerOpenAnatomy extension.

**Pull request closed without merging**
