### PR TITLE
EHN: extension description file renamed

### PR DESCRIPTION
**Pull request by leochan2009**

### CODE REVIEW

**Comment by lassoan** [comment]
We cannot merge this as is - we get "This branch cannot be rebased due to conflicts" message.
Also, it seems that you add a new file, while we already have a "OpenIGTLinkIF.s4ext" file in the repository.

Could you please revise this pull request?

**Comment by fedorov** [comment]
@lassoan there are no conflicts in the GitHub GUI

**Comment by fedorov** [comment]
@leochan2009 it is good style to have a single commit, if you can, please squash the 3 commits you have

**Comment by lassoan** [comment]
> there are no conflicts in the GitHub GUI

Yes, if you merge the commits that GitHub can deal with it. However, we should use "Rebase and merge" to avoid polluting the commit history with merge commits.

**Comment by fedorov** [comment]
In the past, we always kept merge commits, you can see from the commit history. @jcfr what is the recommended style? I thought we keep the merge commit.

As aside, it is good to know the merge dropdown has the option to squash commits into 1 before merging, I didn't know that!

**Comment by leochan2009** [comment]
En, I rename the OpenIGTLinkIF.s4ext to SlicerOpenIGTLInkIF.s4ext according to JC's recommendation.  https://github.com/openigtlink/SlicerOpenIGTLink/issues/4
Yes, i could try to merge the commit into one and submit a pull request

**Pull request closed without merging**
