### PR TITLE
Add Segment Geometry extension

### PR DESCRIPTION
**Pull request by jmhuie**
Segment Geometry is an extension/module that iterates slice-by-slice through a segment to calculate the second moment of area and other cross-sectional properties. Results are exported to a table and plotted for quick visualization.

--

Thank you for contributing to 3D Slicer!

- **To add a new extension with this pull request**: Please keep content of "TODO list for submitting a new extension" section and put an 'x' character in the brackets for each todo item to indicate that you have accomplished that prerequisite.

- **To update an existing extension with this pull request**: Please delete all text in this template and just describe which extension is updated and optionally tell us in a sentence what has been changed. To make extension updates easier in the future (so that you don't have to submit a new pull request after each change in your extension), you may consider replacing specific git hash in your s4ext file by a branch name (for example: `master` or `release` for nightly version; `(majorVersion).(minorVersion)` such as `4.10` for stable Slicer version).

# TODO list for submitting a new extension

[To make sure users can find your extension, understand what it is intended for and how to use it, please complete the checklist below. You do not need to complete all the item by the time you submit the pull request, but most likely the changes will only be merged if all the tasks are done. See more information about the submission process here: https://slicer.readthedocs.io/en/latest/developer_guide/extensions.html]

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Any known related patents must be mentioned in the extension description.
- [x] If source code license is more restrictive for users than BSD, MIT, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://github.com/user/project/raw/main/path/to/icon.png)
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [x] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/master/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [x] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)

[If you have any questions or comments then please describe them here.]

### CODE REVIEW

**Comment by jmhuie** [comment]
I'm bumping this in case it got missed. 

Are there any major issues I need to fix? @lassoan

**Comment by lassoan** [comment]
The module looks really useful and could fulfill the need of many users that are interested in morphometry. However, there are a number of roadblocks that would make the module hardly usable for many users.

About half of the issues are mostly due to unclear points in the documentation, which should be easy to fix.

The other half of the issues are all related to resampling of the segmentation along an axis. This is not a complicated operation at all. It can be done fully automatically - all the user needs to do is to specify an axis direction, and you may allow the user to specify a custom resolution. The user should not be concerned about region of interests, transforms, etc. You can take care of all that internally, by specifying a reference image geometry (origin, axis direction, spacing, and extents) and exporting the segmentation into that geometry. See a complete example [here](https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#get-size-position-and-orientation-of-each-segment) for creating oriented bounding box ROI around segments. This ROI can then be used in Crop volume module to get the resampled input volume, and you can use that volume as reference volume for resampling the segmentation, too.

- README.md:
  - [ ] `Segement Editor module` - typo
  - [ ] `You also transform the Volume node` do you mean that the user should apply the transform to both the volume node and the segmentation node?
  - [ ] `note that the Slice Index output will be based on the untransformed Volume node` - for me it is not clear what you mean. Maybe it is too early to talk about this here.
  - [ ] ` or the interactive "Visible in 3D view" tool under display` - this is not clear enough
  - [ ] `Use the rotation sliders...` - why don't we specify the measurement axis with  a markups line or markups plane node? I would also add a button that would automatically create and initialize the measurement axis (you can use Segment Statistics module to very quickly get this axis, based on oriented bounding box or principal axis), which the user can then adjust.
  - [ ] `Navigate to Segment Geometry` -> `Switch to Segment Geometry module`
  - [ ] `Choose whether to compute on the whole segment or sample the segment in increments.` - This is not clear for me. I guess increments refer to the sampling distance along the long axis. But "whole segment" refers to a region size and not related to sampling distance.
  - [ ] `Segment Geometry provides an example dataset` - excellent! Just mention this at the very beginning, as an alternative to load and segment your own data.
  - [ ] ` To measure compactness, the user must provide a separate segment that contains the the whole structure including the vacuities.` - Describe that SurfaceWrapSolidify extension can automatically generate the solid segment (with internal holes filled).
  - [ ] `Slice Index: The corresponding slice number from the untransformed Volume node.` if the segment is rotated then one slice crosses many slice indices. Index of which slice is used?
  - [ ] `feret` - typo (correct: `Feret`)
  - [ ] `Perimeter ... calculation may be incorrect for cross-sections where ... there is more than one island in the section` - this is very often the case, as concavities can easily end up appearing as two separate islands on a cross-section. What would be the ideal behavior then? Providing the sum of perimeters for each island?
  - [ ] `Note that calculating mean brightness is the only parameter requires resampling the Volume node if the Segmentation node is transformed.` - Does the user need to resample the volume? If not, then don't mention it in the user guide section. You can add a developer section where you describe such implementation details.
  - [ ] `Voxels are anisotropic! Resample the volume` - The module should take care of this internally.
  - [ ] `Voxels are anisotropic! Use the red axis`- The module should take care of this internally, too. The user should not be burdened with such complicated things. It is unlikely that a user would understand what you mean and could do the correct steps to resolve the issue.
  - [ ] `It means there is a break in your segment, where some slices don't contain any pixels.` - You could run Island effect - extract largest island by default to avoid burdening the user with such issues. You may add a checkbox in the "Advanced" section (collapsed by default) to disable this, just in case someone wants to analyze an object that consists of multiple islands.
  - [ ] `I got an error that says "The segment is outside of the volume's bounds!". What does that mean?` - The module should take care of this internally. These things would overwhelm most users.
  - [ ] `Warning! The no-shear assumption may not be met. Click OK to proceed.` instead of a popup (that the immediately, unconsciously closes within a tenth of a second, after reading maximum 2-3 words of it), show it as a red or orange label in the output section. You can display the full explanation in a tooltip (it is not very likely that users would spend time with opening the module documentation and find the relevant information about the error)

None of the above issues should block adding this extension, but it would be better to make these improvements before you release it to users.

**Comment by jmhuie** [comment]
Thank you Andras for these very helpful suggestions. I agree that these will all help the user and I have implemented many of the changes already. For others, I could use a bit of help (see below). 

> * README.md:
>   
>   * [x]  `Segement Editor module` - typo
>   * [x]  `You also transform the Volume node` do you mean that the user should apply the transform to both the volume node and the segmentation node?

I changed this to say that both the segmentation and volume should be transformed. In reality, the volume node does not need to be but I figure it can be a bit confusing in the slice view if the segment is rotated but the volume is not.
>   * [x]  `note that the Slice Index output will be based on the untransformed Volume node` - for me it is not clear what you mean. Maybe it is too early to talk about this here.

I agree. Removed.
>   * [x]  ` or the interactive "Visible in 3D view" tool under display` - this is not clear enough

I have provided more explanation as to what this is as does
>   * [ ]  `Use the rotation sliders...` - why don't we specify the measurement axis with  a markups line or markups plane node? I would also add a button that would automatically create and initialize the measurement axis (you can use Segment Statistics module to very quickly get this axis, based on oriented bounding box or principal axis), which the user can then adjust.

I really like these ideas. Unfortunately, I am not really sure how to implement it for a few reasons. First, it is not clear to me what the principal axis output of Segment Statistics actually is. I was expecting RAS coordinates for two points, creating a line. Second, do you have any suggestions for how I would go about transforming a line or the OBB with the XYZ axes? 
>   * [x]  `Navigate to Segment Geometry` -> `Switch to Segment Geometry module`
>   * [x]  `Choose whether to compute on the whole segment or sample the segment in increments.` - This is not clear for me. I guess increments refer to the sampling distance along the long axis. But "whole segment" refers to a region size and not related to sampling distance.

I clarified this. Your assumptions were correct, but I could see how it was misleading.
>   * [x]  `Segment Geometry provides an example dataset` - excellent! Just mention this at the very beginning, as an alternative to load and segment your own data.
>   * [x]  ` To measure compactness, the user must provide a separate segment that contains the the whole structure including the vacuities.` - Describe that SurfaceWrapSolidify extension can automatically generate the solid segment (with internal holes filled).
>   * [x]  `Slice Index: The corresponding slice number from the untransformed Volume node.` if the segment is rotated then one slice crosses many slice indices. Index of which slice is used?

I recognize this was confusing. Segment Geometry now saves a resampled and cropped volume that contains only the segment. The Slice Index will correspond to this volume so that the user may easily compare the computed values of a slice and the actual shape of the slice.
>   * [x]  `feret` - typo (correct: `Feret`)
>   * [ ]  `Perimeter ... calculation may be incorrect for cross-sections where ... there is more than one island in the section` - this is very often the case, as concavities can easily end up appearing as two separate islands on a cross-section. What would be the ideal behavior then? Providing the sum of perimeters for each island?

For the intended users of this module, perimeter will only be relevant if they're analyzing a single closed shape. I am not sure it's worth it to implement something for other use cases unless it is specifically requested.
>   * [x]  `Note that calculating mean brightness is the only parameter requires resampling the Volume node if the Segmentation node is transformed.` - Does the user need to resample the volume? If not, then don't mention it in the user guide section. You can add a developer section where you describe such implementation details.

Nothing is needed on the user's end. I have removed this part from the README for clarity.
>   * [x]  `Voxels are anisotropic! Resample the volume` - The module should take care of this internally.
>   * [x]  `Voxels are anisotropic! Use the red axis`- The module should take care of this internally, too. The user should not be burdened with such complicated things. It is unlikely that a user would understand what you mean and could do the correct steps to resolve the issue.

I totally understand. Resampling has been automated internally when needed.
>   * [x]  `It means there is a break in your segment, where some slices don't contain any pixels.` - You could run Island effect - extract largest island by default to avoid burdening the user with such issues. You may add a checkbox in the "Advanced" section (collapsed by default) to disable this, just in case someone wants to analyze an object that consists of multiple islands.

I figured the easiest thing to do was to enable Segment Geometry to process slices with nothing on them. In the ideal scenario, the user will be analyzing a single bone that may have floating islands inside of it. 
>   * [x]  `I got an error that says "The segment is outside of the volume's bounds!". What does that mean?` - The module should take care of this internally. These things would overwhelm most users.

This is now being resolved internally.  Much easier for the user.
>   * [ ]  `Warning! The no-shear assumption may not be met. Click OK to proceed.` instead of a popup (that the immediately, unconsciously closes within a tenth of a second, after reading maximum 2-3 words of it), show it as a red or orange label in the output section. You can display the full explanation in a tooltip (it is not very likely that users would spend time with opening the module documentation and find the relevant information about the error)
> 

I like this suggestion. I'm not sure how to do it though. Ideally, I'd like to print this warning under the "Apply" button. Do you have any resources or example modules that can point me in the right direction?
> None of the above issues should block adding this extension, but it would be better to make these improvements before you release it to users.

Overall, I think have addressed the majority of your concerns and that the rest are not critical. I definitely would like to get the "no-shear" warning integrated with the GUI before releasing the extension, but the alternative methods of rotating can wait, depending on how easy it'll be to implement.

**Comment by jmhuie** [comment]
Hey @lassoan 

I addressed all of your previous comments. I have clarified the README where needed and increased the accessibility of the module by moving some previous buttons/user actions to be handled internally. I have also provided a new suite of rotation tools to Segment Geometry that allow for automatic alignment with the principal axes (per your suggestion), a button that enables the Interactive in 3D view bounding box, and GUI Sliders that will rotate the segment about its centroid. See my previous post and its edits for a list of all the changes I've made.

At this point, I think that my extension is ready to be published but please look it over and let me know. Thanks!

**Comment by lassoan** [comment]
Sounds good, let's merge this then.

**Comment by jmhuie** [comment]
> The pull request is merged. The extension should show up in the extension manager for the latest Slicer Preview Release from tomorrow. Congratulations for your first extension!

Awesome! Thanks for all of your help Andras. Just curious, when will the extension be available for the latest stable release or how can I prepare it for that?

**Comment by lassoan** [comment]
If the module is compatible with the latest Slicer Stable Release then you can submit a pull request to the 4.11 branch in this repository.

**Comment by jmhuie** [comment]
Great! I just submitted a pull request.

**Comment by jmhuie** [comment]
> The pull request is merged. The extension should show up in the extension manager for the latest Slicer Preview Release from tomorrow. Congratulations for your first extension!

My extension hasn't been showing up in the Preview Release or the Stable Release extension managers. Does that mean I did something wrong on my end?

**Comment by lassoan** [comment]
The problem was that the branch name was `master` instead of `main`. https://slicer.cdash.org/build/2409774/configure

I've fixed it now, so the extension should show up tomorrow.

**Comment by jmhuie** [comment]
Thank you. Apologies for the seemingly trivial questions. Fingers crossed that it'll work tomorrow.

**Comment by jmhuie** [comment]
Looks like it's still failing to build. Yesterday, it failed to configure because I forgot to include a CMake file in the module folder. Today, it looks like it's able to configure but still failing to build for reasons I cannot figure out.

**Comment by lassoan** [comment]
Build is successful - see https://slicer.cdash.org/index.php?project=SlicerPreview&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=SegmentGeometry

What problems do you see?

**Comment by jmhuie** [comment]
I don't see the extension in the Preview Release's extension manager, but maybe that's because there is no Preview Release for today?

It's also not showing up in the Stable Release's extension manager and I'm getting errors there: https://slicer.cdash.org/index.php?project=Slicer4&date=2021-09-25&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=SegmentGeometry

**Comment by lassoan** [comment]
The Slicer Preview Release should work tonight. The Stable Release should be fixed soon, too. You don't need to do anything else on your side, just check the Preview Release tomorrow and let us know if it still does not show up.

**Comment by jmhuie** [comment]
Success! Hopefully the stable release will be fixed soon, but I'm glad to know that everything will probably work when it does. Thank you so much for your help Andras.

**Pull request merged**
