### PR TITLE
add new extension MarginCalculator.

### PR DESCRIPTION
**Pull request by kevinwangcanada**

### CODE REVIEW

**Comment by fedorov** [comment]
Is there a good reason why you are adding this extension to 4.4 branch, but not to the trunk?

**Comment by cpinter** [comment]
Kevin told me the reason is that he has not made the changes necessary to make it compatible with the nightly (i.e. LabelMapVolumeNode), but he would like to publish it as soon as possible.

**Comment by fedorov** [comment]
Sounds like a good reason for testing, even though somewhat confusing since new features are added to the release that are not available in the nightly :) I hope @jcfr will be ok with this...

**Comment by cpinter** [comment]
I don't see any harm in adding it to a soon obsolete stable Slicer version, although I also think that releasing it for the nightly would be better. Thanks for merging!

**Comment by fedorov** [comment]
Agreed.

btw @cpinter it looks like you should have the permissions to merge on ExtensionIndex as well - it looks like you are on the appropriate team.

**Pull request merged**
