### PR TITLE
add TOMAAT

### PR DESCRIPTION
**Pull request by faustomilletari**
add the extension to stable version of slicer (4.8)

### CODE REVIEW

**Comment by faustomilletari** [comment]
this won't build automatically and be available for stable, I guess... what is the procedure in this case?

**Comment by fedorov** [comment]
It did build (see http://slicer.cdash.org/index.php?project=Slicer4&display=project&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=tomaat), but I do not know why it does not show up in ExtensionManager. I suggest you post a question on discourse.

**Comment by faustomilletari** [comment]
for nightly built it shows up beautifully. for stable I couldn't see it yesterday.

**Comment by fedorov** [comment]
I posted a question on discourse: https://discourse.slicer.org/t/new-extension-does-not-show-in-slicer-4-8-extensonmanager/1729

**Comment by faustomilletari** [comment]
Many thanks!

Fausto Milletarì

**Comment by jcfr** [comment]
As soon as we finalize 4.8.1, it will be available.

Should be able to finalize tomorrow in the next few days.

Hth
Jc

**Pull request merged**
