### PR TITLE
Add MassVision extension

### PR DESCRIPTION
**Pull request by jamzad**
# New extension

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [X] Repository name is Slicer+ExtensionName
- [X] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [X] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [X] Any known related patents must be mentioned in the extension description.
- [X] LICENSE.txt is present in the repository root. MIT  (https://choosealicense.com/licenses/mit/) or Apache (https://choosealicense.com/licenses/apache-2.0/) license is recommended. If source code license is more restrictive for users than MIT, BSD, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [X] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (main, release, ...) instead of a specific git hash to avoid re-submitting pull request whenever the extension is updated
- [X] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://raw.githubusercontent.com/user/repo/main/SomeIcon.png)
- [X] Screenshot URLs (screenshoturls) are correct, contains at least one
- [X] Homepage URL points to valid webpage containing the following:
  - [X] Extension name
  - [X] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [X] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [X] Description of contained modules: at one sentence for each module
  - [X] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [X] Publication: link to publication and/or to PubMed reference (if available)
  - [X] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/main/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [X] Content of submitted json file is consistent with the top-level CMakeLists.txt file in the repository (dependencies, etc. are the same)
- Hide unused features in the repository to reduce noise/irrelevant information:
  - [X] Click `Settings` and in repository settings uncheck `Wiki`, `Projects`, and `Discussions` (if they are currently not used)
  - [X] Click the settings icon next to `About` in the top-right corner of the repository main page and uncheck `Releases` and `Packages` (if they are currently not used)

### CODE REVIEW

**Comment by pieper** [comment]
This looks really nice 👍 

One thing I noticed is that your readthedocs image liinks aren't working.  It would be great if you could check that.  E.g.:  https://slicerdesi.readthedocs.io/en/latest/Generating%20a%20Dataset.html

Also it looks like there's a lint check issue with this PR.

**Comment by jamzad** [comment]
Hi Steve
Thank you very much for your email. We've changed the repo name and have to update the image links to the readthedoc. I'll take care of that. I'm not familiar with linting but will look into it as well. Appreciate any guidelines.
Thanks
AMoon

________________________________

**Comment by lassoan** [comment]
Before providing a meaningful review, I would just suggest to consider naming the extension `MassSpecAI` (without the `t`; and `S` of `Spec` capitalized). It may seem like unnecessary nitpicking, but it would be hard to change the extension name later. The current `MassspectAI` name is not optimal because:
- it is almost impossible to pronounce it (the `t` would be silent unless you make extraordinary effort to emphasize it) and mass spectroscopy is universally abbreviated as "mass spec" (not "mass spect")
- having 3 identical `s` characters next to each other makes the word hard to read and even harder to write it properly (without the capitalization I typed just 2 `s` chracters several times while writing this comment)

The name should be updated in the extension name (in CMakeLists.txt file), in the repository name, and in this pull request.

While we are at this, we should also discuss the category name. It would be better to choose a name where we expect to have at least 5-10 extensions in the future. `Quantification` may be a candidate, but maybe that is too broad. Could you suggest something that is a bit more specific then quantification but not quite as specific as mass spectrometry? Maybe something like `ChemicalAnalysis`?

**Comment by jamzad** [comment]
Hi Andras
Thank you very much for your great suggestions.

Regarding the naming, we came with MasspectAI (currently with only 2 S) after careful consideration of the field and applications, and as you recommended previously, with the room for update and improvement in the future

  *
There exists a specific modality of mass spectrometry called "MasSpec Pen", and we don't want the users to associate our software with that platform.
  *
Masspect (single word) is also an accepted terminology but less common
  *
The pronunciation is "mas-pekt" "ay-eye", so the "t" will highlight and separate the AI

Considering these factors, the preference is to either keep the current "MasspectAI", or just remove the "t" and go with "MasspecAI" without capitalizing the second "s". Please let me know what you think.

Regarding the category, we are hoping to have additional supporting module for the main one in the future, for instance for data conversion between different modalities, but that may be limited to 3 to 4, so I'm totally fine with changing it to something more general. I imagine that "chemical analysis" would end up the same as "mass spectrometry" as there are not many chemical modules. These are my suggestions:

  *
Spatio-Spectral is one suggestion that covers all data with spatial and spectral component (mass spectrometry, hyperspectral imaging, spectroscopy imaging, etc.)
  *
We already have a module in Slicer called "TITAN" for mass cytometry in "analysis" category. Although it is still general, we can reuse it to have bioth module in one location.

These are my suggestions but I'm happy to hear what you think.

Lastly, I'm getting an error during pre-commit for linting pointing out that "prettier" and "jasonschema" are failing. I appreciate any comment on that as well

Thank you very much for your help and support
Amoon



________________________________

**Comment by Sunderlandkyl** [comment]
The linting issue was that "Prettier" was converting line endings from CRLF to LF. Not sure why they aren't being committed in LF, but changing them to LF manually fixed the error.

**Comment by jamzad** [comment]
Hi Kyle
Thank you very much for resolving the issue. 

Hi Andras
We've changed the name of the module to MassVision and the category to Spectral Imaging as suggested.

**Comment by lassoan** [comment]
Everything looks quite good, I've managed to package and run the module successfully, but there are a few small things to take care of.
- Most important: I've tried to follow the tutorial - https://slicerdesi.readthedocs.io/en/latest/Importing%20Data.html - but I got stuck, because I don't have data to test with. It is essential to provide sample data for the tutorial. Even if people have their own data, first they probably want to complete the tutorial with the provided sample data set.
- Update this page: https://slicerdesi.readthedocs.io/en/latest/Installation.html
- I've found a few typos. Maybe run the documentation files through a spell checker.
  - `Visulization` - https://slicerdesi.readthedocs.io/en/latest/Visulization.html
  - `Model Deploymenet` - https://slicerdesi.readthedocs.io/en/latest/Model%20Deployment.html

**Comment by jamzad** [comment]
Hi Andras

Thank you very much for the comments. We are in the process of making one of our datasets publicly available, which will eventually be linked to the software as a toy set. However, as you suggested I can prepare a sample data for now. I'll add the link to the data to the "Installation" page on documentation and will also update it (remove the manual addition to the Slicer as it'll be included in the extension manager). I'll also make sure there's no typo in the documentations.

Thanks,
Amoon
________________________________

**Comment by jamzad** [comment]
@lassoan 
The documentation is updated and a sample MSI data and associated pathology annotation is added under the "Installation" tab of the documentation.

**Comment by lassoan** [comment]
I got this error when I tried to follow the tutorial:

```
Traceback (most recent call last):
  File "C:/D/SlicerMassVision-win64rel/_CPack_Packages/win64/ZIP/30987-win-amd64-MassVision-git446a1eb-2024-06-04/lib/Slicer-5.7/qt-scripted-modules/MassVision.py", line 272, in onTextFileSelect
    self.onTextFileLoad()
  File "C:/D/SlicerMassVision-win64rel/_CPack_Packages/win64/ZIP/30987-win-amd64-MassVision-git446a1eb-2024-06-04/lib/Slicer-5.7/qt-scripted-modules/MassVision.py", line 278, in onTextFileLoad
    file_load = self.logic.textFileLoad(self.ui.ImportlineEdit.text)
  File "C:\D\SlicerMassVision-win64rel\_CPack_Packages\win64\ZIP\30987-win-amd64-MassVision-git446a1eb-2024-06-04\lib\Slicer-5.7\qt-scripted-modules\MassVisionLib\Logic.py", line 1526, in textFileLoad
    [peaks, mz, dim_y, dim_x] = self.MSI_csv2numpy(name)
  File "C:\D\SlicerMassVision-win64rel\_CPack_Packages\win64\ZIP\30987-win-amd64-MassVision-git446a1eb-2024-06-04\lib\Slicer-5.7\qt-scripted-modules\MassVisionLib\Logic.py", line 181, in MSI_csv2numpy
    dim_y = int(df.columns[0])
ValueError: invalid literal for int() with base 10: 'y=90'
```

I could not proceed with the rest of the tutorial. Could you please fix this so that I can test the rest?

A few other things that I noted. These are not required for getting the extension into the Extensions Index, but would be nice to fix at some point:
- Documentation is at https://slicerdesi.readthedocs.io/en/latest/ (linked from https://github.com/jamzad/SlicerMassVision?tab=readme-ov-file#documentations) - you may want to rename the site to MassVision
- Instead of `toy data`, it would sound better to call it `demo data` or `test data` (https://slicerdesi.readthedocs.io/en/latest/Installation.html#toy-data)
- Instead of hosting on dropbox, I would recommend to upload it into the github repository as a release asset. Then anybody who has reight to manage releases in this github repository will be able to update the data set. Hosting with your personal dropbox account means that only the person who has access to your personal phone can manage the data or you have to pay monthly fees for some professional dropbox hosting plan - none of them is sustainable in the long term. Download from dropbox folder is slightly annoying (they keep showing me a popup to register to dropbox, add the folder to my account, etc.)
- Module startup is slow. It takes  2-3 seconds, which is about 50x longer than most other modules take. If all the 130+ modules in Slicer would take this much time to initialize then the application startup time would be about 5 minutes. Probably you import a lot at the file scope in `MassVision.py`. It is not a huge issue, since people who download the extension probably want to use it, but still, adding a few seconds to every startup is noticeable and users will know that your module is the culprit (because the name is shown for a relatively long time in the splashwindow). So, I would recommend to only import those libraries at startup that are essential for initializing the module.
- Opening the MassVision module is not part of the Installation (that you do only once), but part of the usage instructions (that you follow whenever you want to do something). So, I would recommend to move it from [this page](https://slicerdesi.readthedocs.io/en/latest/Installation.html#installation) to [this](https://slicerdesi.readthedocs.io/en/latest/Importing%20Data.html)
- It would help users if you marked up screenshots with arrows/labels, like this:

image

Or even better like this if there are many steps in non-trivial order:

image

**Comment by jamzad** [comment]
Hi Andras

Thank you very much for checking. Regarding the error, I noticed the issue last week and fixed it then (https://github.com/jamzad/SlicerMassVision/commit/bb234cf7abdaed78be4e10f502c7698315703683). Please kindly get the latest version and let me know if the issue persists.

Regarding the documentarian, thank you very much for the suggestions. All fair points that will definitely improve the user experience. I'll update and modify gradually.

Thanks again for the support
Amoon


________________________________

**Comment by lassoan** [comment]
Thank you. I've found a couple of things to fix or improve, but none of them are required before adding the extension available in the Extensions Index. So, I'll integrate this pull request now and you can continue working on these improvements.

- Use ctkPathLine edit for selecting an input file (instead of a custom `Select file` button)
- When I click on `Visualize` button, all my slice view setup is lost. I had the histology image as background with field of view, opacity, etc. all set up and just wanted to visualize a different ion, and I would now need to set up everything again. 
- Short video or screenshots could help with https://slicerdesi.readthedocs.io/en/latest/Visualization.html#pixel-spectrum
- Spectrum plot display was flipped for me, because I had view orientation in application settings at "patient right is screen right" mode:
image
- ROI shows up in spectrum plot - would be nice to hide the ROI in this view
- It is not clear how the module knows which ROI and point list to use for visualization. Normally you would allow the user to select these nodes.
- When I clicked `Landmark registration` button, I got this error and I could not continue the tutorial:

```
Traceback (most recent call last):
  File "C:/Users/andra/AppData/Local/slicer.org/Slicer 5.7.0-2024-05-27/bin/../lib/Slicer-5.7/qt-scripted-modules/LandmarkRegistration.py", line 69, in setup
    self.reloadAndTestButton.toolTip = "Reload this module and then run the %s self test." % scenario
AttributeError: 'LandmarkRegistrationWidget' object has no attribute 'reloadAndTestButton'
Traceback (most recent call last):
  File "C:/Users/andra/AppData/Local/slicer.org/Slicer 5.7.0-2024-05-27/bin/../lib/Slicer-5.7/qt-scripted-modules/LandmarkRegistration.py", line 219, in enter
    self.interfaceFrame.enabled = False
AttributeError: 'LandmarkRegistrationWidget' object has no attribute 'interfaceFrame'
```

- Some text snippet remained in the documentation:

```
####as images to your working directory (same directory as where your PCA image was created and the data was loaded in from) allowing you to view them at a later time.####
```

- `Generating a Dataset` is very general. Every processing operation generates a dataset. What kind of dataset are we generating here? The section overview does not give any hint either: `To generate a suitable dataset, the histopathology and MSI visualization must undergo preprocessing and registration prior to ROI selection.`
- Typo:  `whole=-slide MSI data`
- It would be nice to have a very high level description of the complete workflow on a single page.

**Comment by jamzad** [comment]
Thank you very much for the feedback Andras! I'll check and resolve them all.

Regarding the error you've encountered, the button simply calls the "landmark registration" module. In the current stable version of Slicer, this module cannot be loaded in the Developer mode (issue already reported to the Slicer forum). If you want to try the rest of the tutorial, please turn off the developer mode. I'll make sure to include it this in the setup section of the documentation until the issue is resolved. I haven't tried it but assume this is not an issue in the preview release.

Thanks again for your help and support
Amoon
________________________________

**Comment by pieper** [comment]
> the button simply calls the "landmark registration" module. In the current stable version of Slicer, this module cannot be loaded in the Developer mode (issue already reported to the Slicer forum).

Can you add a link to an issue describing this?  It sounds like something that was fixed a while ago.

**Comment by jamesobutler** [comment]
@pieper It appears the same fix as in https://github.com/pieper/CompareVolumes/commit/cb755dda78f726cf9262aa4e1f75122c72a0df2f needs to be applied to LandmarkRegistration module. See outdated usage:
https://github.com/Slicer/LandmarkRegistration/blob/ac114f6c2e9a821c1d942334be003552bcd56255/LandmarkRegistration.py#L69

**Comment by pieper** [comment]
Thanks @jamesobutler yes, that's what I was thinking.  Can someone create a PR?  I'm out of office for a bit but can merge.

**Comment by jamesobutler** [comment]
See https://github.com/Slicer/LandmarkRegistration/pull/37

**Comment by jamzad** [comment]
Hi all
Thanks again for all the support. I tried the current preview version today with my module and received an error regarding SimpleITK library:

    import SimpleITK as sitk
    File "C:\ProgramData\slicer.org\Slicer 5.7.0-2024-06-10\lib\Python\Lib\site-packages\SimpleITK\__init__.py", line 18, in <module>
      from SimpleITK.SimpleITK import *
    File "C:\ProgramData\slicer.org\Slicer 5.7.0-2024-06-10\lib\Python\Lib\site-packages\SimpleITK\SimpleITK.py", line 13, in <module>
    from . import _SimpleITK
    ImportError: DLL load failed while importing _SimpleITK: The specified module could not be found.

I've also tried "Simple Filters" module under Filtering category which uses this library, just to check, and received the same error. Not sure if this is the right place to report it. Please kindly let me know.
Thanks
AMoon

**Pull request merged**
