### PR TITLE
Update "Add SlicerTissueSegmentation extension 5.0"

### PR DESCRIPTION
**Pull request by MarinaSandonis**
Reverts Slicer/ExtensionsIndex#1880

### CODE REVIEW

**Comment by MarinaSandonis** [comment]
If possible, I would like these changes to be integrated. Do I have to create another new pull request for this?

**Comment by jamesobutler** [comment]
> I have made some changes, which consist of updating some URLs in the 'CMakeList.txt' document. I hope this is enough for the images to appear.

Since you have specified to use the `main` branch of your repo, it will be used whenever extensions are built. Since you made these changes about an hour ago 8-9am EDT, they won't go into effect into about 2-6am EDT tomorrow as the extensions won't be built again until tomorrow.

**Comment by jamesobutler** [comment]
In this specific PR (https://github.com/Slicer/ExtensionsIndex/pull/1887/files) you are completely removing SlicerTissueSegmentation from being an available extension with Slicer 5.0.x. Is this what you desire?

**Comment by MarinaSandonis** [comment]
No, my intention isn't to remove the extension. I just wanted to try and fix the images issue. Sorry for opening this pull request, I don't want to remove the extension

**Pull request closed without merging**
