### PR TITLE
EHN: rename the OpenIGTLinkIF.s4ext to SlicerOpenIGTLink.s4ext

### PR DESCRIPTION
**Pull request by leochan2009**

### CODE REVIEW

**Comment by leochan2009** [comment]
#1519 
@lassoan @fedorov

**Comment by lassoan** [comment]
Do we want to keep the IF at the end of the name? I think it would be more appropriate to just call the extension SlicerOpenIGTLink. It would contain only OpenIGTLinkIF module now, but we might add more modules in the future.

**Comment by leochan2009** [comment]
will do so!

**Comment by leochan2009** [comment]
@lassoan SlicerIGT is depending on SlicerOpenIGTLink, so this pull request need to be merged to make slicerigt build succeed.

Best
longquan

**Pull request merged**
