### PR TITLE
add T1Mapping

### PR DESCRIPTION
**Pull request by stevedaxiao**
Add the new version of T1Mapping Module
Thx

### CODE REVIEW

**Comment by stevedaxiao** [comment]
Ownership has already been transferred. So it will automatically connect to qiicr

**Comment by fedorov** [comment]
The way Slicer extensions work, the source code will be checked from the URL defined in the s4ext file scmurl entry. Currently this entry is pointing to the repository under your name, see https://github.com/stevedaxiao/ExtensionsIndex/commit/dce9da315e49606e2ea007ea99fe9b30d1402ebf#diff-a679f2d18c3074fbd4db04e7b7bc59d7R9. You need to update it to pont to the repository under QIICR.

**Comment by stevedaxiao** [comment]
I fully Understand. I don't know how to change it automatically. 
I did git pull to update and did cmake again. The automatically generated s4ext still showed https://github.com/stevedaxiao/T1Mapping.
You want me revise it manually for the s4ext file? 
https://github.com/QIICR/T1Mapping and https://github.com/stevedaxiao/T1Mapping are the same.

**Comment by fedorov** [comment]
I am not sure how to update it automatically. I would modify s4ext file manually, and then commit to the add-T1Mapping branch.

**Comment by jcfr** [comment]
This happen because the remote origin is associated with your fork and not
the qiicr one.
Hth
Jc

**Pull request closed without merging**
