### PR TITLE
Relocate repository to gitlab.

### PR DESCRIPTION
**Pull request by chir-set**
# New extension

- [X] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [X] Repository name is Slicer+ExtensionName
- [X] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [X] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [X] Any known related patents must be mentioned in the extension description.
- [X] LICENSE.txt is present in the repository root. MIT  (https://choosealicense.com/licenses/mit/) or Apache (https://choosealicense.com/licenses/apache-2.0/) license is recommended. If source code license is more restrictive for users than MIT, BSD, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [X] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (main, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [X] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://raw.githubusercontent.com/user/repo/main/SomeIcon.png)
- [X] Screenshot URLs (screenshoturls) are correct, contains at least one
- [X] Homepage URL points to valid webpage containing the following:
  - [X] Extension name
  - [X] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [X] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [X] Description of contained modules: at one sentence for each module
  - [X] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [X] Publication: link to publication and/or to PubMed reference (if available)
  - [X] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/main/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [X] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)
- Hide unused features in the repository to reduce noise/irrelevant information:
  - [X] Click `Settings` and in repository settings uncheck `Wiki`, `Projects`, and `Discussions` (if they are currently not used)
  - [X] Click the settings icon next to `About` in the top-right corner of the repository main page and uncheck `Releases` and `Packages` (if they are currently not used)

### CODE REVIEW

**Comment by jcfr** [comment]
To help inform others, would you mind sharing the motivation to transition the extension hosting from GitHub to GitLab ? 

Cc: @lassoan

**Comment by jamesobutler** [comment]
I'd be curious about the transition as well. From another developer perspective, since GitHub is much more popular than GitLab (specifically within the Slicer community), I'm more likely to fork a repo to issue fixes if it is on GitHub. Since I have less familiarity with GitLab, I'm less likely to contribute there.

**Comment by chir-set** [comment]
> sharing the motivation



> I'd be curious

Github is enforcing 2FA as from sept 15. The rest is personal acceptance of this step.

To put it as Linus says in *other* contexts and about *other* subjects, 2FA 'is being forced down the throat'.

Github should have left it as an option. It's already *always* a pain to validate a bank transaction on my phone every time I buy something online (and we'll be doing that more and more often), while the rationale here is clear and easily acceptable.

For a project that is public (no secret at all, no market value for the developer), 2FA is an overkill. I don't want to play with my phone every time I need to commit some changes, or every time 'some actions are taken' in my repos, as they say in their email messages.

2FA may have a rationale for companies that collaborate worldwide in *private* repositories hosted on github. Not for public bits. Admin access is already protected by a password and by a 'personal access token'.

I'm well aware that gitlab may well make 2FA mandatory at some point. I just hope to be close enough to retirement, and that someone will take on my legacy then.

Regards and thank you for the merge.

**Comment by lassoan** [comment]
I agree, Gitlab is really inconvenient if you get used to Github, so I'm much more likely to give feedback or contribute a project on Github than gitlab. Github also provides unlimited free (including private) repositories for any non-profit lab. 

Choosing gitlab will result in you having to do more work: either to maintain two repositories (gitlab and Github) or because you miss out on collaborations (many people will not bother spending the extra time to deal with gitlab).

**Comment by jamesobutler** [comment]
>  I don't want to play with my phone every time I need to commit some changes, or every time 'some actions are taken' in my repos, as they say in their email messages.

Once I'm signed into GitHub locally with my Visual Studio Code IDE (and I have 2FA), I don't have enter a 2FA code for every commit or any other action. It keeps me signed in. Hopefully this helps you when you are using GitHub. I only ever have to enter a 2FA if I for some reason signed out of GitHub and need to sign back in.

**Comment by lassoan** [comment]
I have the same experience. 2FA rarely comes up - the only situation I recall it is asked when I manage users of a repository. Github never asks for it (after a one-time initial authentication) for any git operations.

Github also offers many authentication options, several of them don't require a phone and they tend to be really easy to use. I use `authy` app to generate a token automatically in every 30sec that I just need to type in before managing critical repository settings. You can also pre-generate tokens that you can use without a phone. 

It is all very reasonable. I had similar concerns before I activated 2FA in github, but it turned out not to be a problem at all. 2FA makes it harder for hackers to inject malicious code into your software, so while there is a tiny extra effort, it is worth it.

Most importantly: do not retire because of 2FA. If you really want to, then there are much better reasons (but hopefully you won't retire for some time).

**Pull request merged**
