### PR TITLE
Create OrthodonticAnalysis.s4ext

### PR DESCRIPTION
**Pull request by OrthodonticAnalysis**
- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [ ] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click "Manage topics" on your repository's main page, on the left, near the top (just below the repository description). To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [ ] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/master/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [x] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)

### CODE REVIEW

**Comment by lassoan** [comment]
Thanks a lot, this will be great! I'll update the code to work with latest Slicer version and use the latest scripts module template. It wipp be ready in 1-2 days. In the meantime, would you mind renaming the repository to Slicer Orthodontic Analysis to match common extension naming convention.

**Comment by lassoan** [comment]
The improvements are ready, see here:

https://github.com/OrthodonticAnalysis/orthodontic-analysis-slicer-extension/pull/1

To accept the changes, simply click on "Merge" button.

**Comment by OrthodonticAnalysis** [comment]
> The improvements are ready, see here:
> 
> [OrthodonticAnalysis/orthodontic-analysis-slicer-extension#1](https://github.com/OrthodonticAnalysis/orthodontic-analysis-slicer-extension/pull/1)
> 
> To accept the changes, simply click on "Merge" button.


Thank you very much for the updates! The requested changes are done.

**Comment by lassoan** [comment]
The OrthodonticAnalysis extension is now added to the extensions index for both latest stable (4.11.20200930) and preview releases. It will show up in the Extensions Manager in Slicer tomorrow or the day after.

Two more things:
1. Please associate your repository with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes".
2. Check if the extension appears in Slicer's Extensions Manager and can be installed and works correctly. If it does, then let people know about it: write about it on [Slicer forum](https://discourse.slicer.org), twitter, etc.

**Pull request closed without merging**
