### PR TITLE
EHN: Extenstion renamed. issue #1556

### PR DESCRIPTION
**Pull request by leochan2009**

### CODE REVIEW

**Comment by leochan2009** [comment]
@jcfr

**Comment by fedorov** [comment]
Should it be `Frame` or `ZFrame`?

**Comment by leochan2009** [comment]
Thanks for your sharp eye!

**Comment by fedorov** [comment]
Let's hold on about this, see discussion in https://github.com/Slicer/ExtensionsIndex/pull/1556#issuecomment-396673107

**Comment by jcfr** [comment]
Closing this PR since it doesn't implement any change (beside of removing a new line)

**Comment by fedorov** [comment]
> Closing this PR since it doesn't implement any change (beside of removing a new line)

@jcfr the change was in the renaming of the file, but as discussed in #1556, we should not rename it, so thanks for closing it!

**Comment by jcfr** [comment]
> was in the renaming of the file

Good point. Not sure why I missed that.

**Pull request closed without merging**
