### PR TITLE
Added Phantom Segmenter Extension

### PR DESCRIPTION
**Pull request by moselhy**

### CODE REVIEW

**Comment by jcfr** [comment]
@lassoan  Did you have a chance to look at this PR ?

**Comment by lassoan** [comment]
I've just had a look at it now. It needs the same kind of cleanup as it was nicely done for SegmentRegistration.

These would be needed to get started (so that I can try the module and give more specific feedback):
- [ ] Short introduction: a few sentences about what kind of phantom it can be used for, how the method works, etc.
- [ ] Basic tutorial: step-by-step instructions about how to use this module on an example data set.
- [ ] 2-3 screenshots (either as part of introduction or tutorial)

**Comment by moselhy** [comment]
Thank you both. I'm waiting for a scan of a phantom to be used as sample data. Will do this when I can.

**Comment by lassoan** [comment]
@moselhy Have you closed this pull request intentionally?

**Pull request closed without merging**
