### PR TITLE
Update SlicerIGT.s4ext

### PR DESCRIPTION
**Pull request by adamrankin**
Updating git url to enable build

### CODE REVIEW

**Comment by lassoan** [comment]
Have you had problems with checking out a repository with https?

**Comment by adamrankin** [comment]
Not with updated Git for Windows. But the build machines are failing to pull any extension defined with https.

**Comment by lassoan** [comment]
77 extensions use `scmurl https://github.com...`. I don't think we should change all of them. What build machines don't have https?

**Comment by jcfr** [comment]
While doing some cleanup, we removed private SSH keys that should not be on that machine.  I will locally generate a pair of key for that machine and it should allow anonymous https checkout to complete without asking credentials.

**Pull request closed without merging**
