### PR TITLE
Add Slicer-MusculoskeletalAnalysis extension

### PR DESCRIPTION
**Pull request by jszatkowski116**
# New extension

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Any known related patents must be mentioned in the extension description.
- [x] LICENSE.txt is present in the repository root. MIT  (https://choosealicense.com/licenses/mit/) or Apache (https://choosealicense.com/licenses/apache-2.0/) license is recommended. If source code license is more restrictive for users than MIT, BSD, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (main, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://raw.githubusercontent.com/user/repo/main/SomeIcon.png)
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [x] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/main/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [x] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)
- Hide unused features in the repository to reduce noise/irrelevant information:
  - [x] Click `Settings` and in repository settings uncheck `Wiki`, `Projects`, and `Discussions` (if they are currently not used)
  - [x] Click the settings icon next to `About` in the top-right corner of the repository main page and uncheck `Releases` and `Packages` (if they are currently not used)

### CODE REVIEW

**Comment by pieper** [comment]
This looks like a nice extension not overlapping with other extensions as far as I can see.  But it looks like only bone analysis now.  Is your intent to fill it out with more modules later?  I ask because when you pick a broad extension name it typically means trying to foster a community around the topic with many contributors and functions, like SlicerRT or SlicerCMF.  If this is a more focused effort then a more specific name would be appropriate.

**Comment by jszatkowskiwustl** [comment]
The plan is to continuously develop new modules.  I'm working as part of the WashU Musculoskeletal Research Center, so we wanted to make sure that the name could cover anything in that area.

**Comment by pieper** [comment]
> The plan is to continuously develop new modules

That's great - welcome!

Have you had a look at this extension?  https://github.com/Kitware/BoneTextureExtension. It's not my field so I don't know if it makes sense to combine or if these are complementary.

**Comment by jszatkowskiwustl** [comment]
Thank you! I'll be sure to check it out and mention it to the rest of the lab.

**Comment by jszatkowskiwustl** [comment]
I've checked out some related extensions in the extension manager, the only one I found that was close was ABLTemporalBoneSegmentation. It's not an exact match as we don't have a temporal bone analysis module, but anything similar that helps with segmentation would be very complimentary.  The analysis modules are all designed to perform calculations and generate a report based on a DICOM and segmentation, so having accurate segmentations to feed into it is important.

**Comment by jcfr** [comment]
Thanks for the contribution :pray: 

To move forward, I suggest you consider addressing the following:
* https://github.com/WashUMusculoskeletalCore/Slicer-MusculoskeletalAnalysis/issues/1
* https://github.com/WashUMusculoskeletalCore/Slicer-MusculoskeletalAnalysis/issues/2
* https://github.com/WashUMusculoskeletalCore/Slicer-MusculoskeletalAnalysis/issues/3
* https://github.com/WashUMusculoskeletalCore/Slicer-MusculoskeletalAnalysis/issues/4
* https://github.com/WashUMusculoskeletalCore/Slicer-MusculoskeletalAnalysis/issues/5
* https://github.com/WashUMusculoskeletalCore/Slicer-MusculoskeletalAnalysis/issues/6
* https://github.com/WashUMusculoskeletalCore/Slicer-MusculoskeletalAnalysis/issues/7
* https://github.com/WashUMusculoskeletalCore/Slicer-MusculoskeletalAnalysis/issues/8
* https://github.com/WashUMusculoskeletalCore/Slicer-MusculoskeletalAnalysis/issues/9

**Comment by jszatkowskiwustl** [comment]
All issues have been taken care of. Please have a look and let me know if there's anything else.

**Comment by jszatkowskiwustl** [comment]
I am currently working on an additional module to add an intervertebral disc analysis function. If it is complete before the current version is approved, would it be preferable to add it immediately, or wait until after the approval?

**Comment by jszatkowskiwustl** [comment]
Hi, I haven't heard anything back in a while. Is there something I need to do to remove the Awaiting Response tag?

**Comment by jcfr** [comment]
Thanks for your patience.

Here are some following pull requests to review:
* https://github.com/WashUMusculoskeletalCore/Slicer-MusculoskeletalAnalysis/pull/13
* https://github.com/WashUMusculoskeletalCore/Slicer-MusculoskeletalAnalysis/pull/15
* https://github.com/WashUMusculoskeletalCore/Slicer-MusculoskeletalAnalysis/pull/11

.. and few other issues:
* https://github.com/WashUMusculoskeletalCore/Slicer-MusculoskeletalAnalysis/issues/14
* https://github.com/WashUMusculoskeletalCore/Slicer-MusculoskeletalAnalysis/issues/16
* https://github.com/WashUMusculoskeletalCore/Slicer-MusculoskeletalAnalysis/issues/17
* https://github.com/WashUMusculoskeletalCore/Slicer-MusculoskeletalAnalysis/issues/10

**Comment by jszatkowskiwustl** [comment]
A new update has been added that should address all issues.

**Comment by jszatkowskiwustl** [comment]
Hi, I wanted to check in again as I haven't heard anything in a while. Is there anything else needed?

**Comment by jcfr** [comment]
Unable to force push changes onto [WashUMusculoskeletalCore/ExtensionsIndex@main](https://github.com/WashUMusculoskeletalCore/ExtensionsIndex/tree/main), the updated changes are published here https://github.com/Slicer/ExtensionsIndex/compare/main...jcfr:ExtensionsIndex:WashUMusculoskeletalCore-main

Consider running the following command to update this pull request:

```
git clone git@github.com:WashUMusculoskeletalCore/ExtensionsIndex.git
cd ExtensionsIndex
git checkout main
git remote add jcfr https://github.com/jcfr/ExtensionsIndex.git
git fetch jcfr
git reset --hard jcfr/WashUMusculoskeletalCore-main
git push origin main --force
```

**Comment by lassoan** [comment]
I would suggest to accept this as a tier 1 extension (we can upgrade the tier if maintainers request it; we may archive the extension if there are errors that don't get resolved).

**Comment by lassoan** [comment]
Merged as https://github.com/Slicer/ExtensionsIndex/pull/2130

**Pull request closed without merging**
