### PR TITLE
Add flywheelcaseiterator

### PR DESCRIPTION
**Pull request by joshicola**
# SlicerFlywheelCaseIterator

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Any known related patents must be mentioned in the extension description.
- [x] LICENSE.txt is present in the repository root. MIT  (https://choosealicense.com/licenses/mit/) or Apache (https://choosealicense.com/licenses/apache-2.0/) license is recommended. If source code license is more restrictive for users than MIT, BSD, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (main, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://raw.githubusercontent.com/user/repo/main/SomeIcon.png)
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [x] ~~Publication: link to publication and/or to PubMed reference (if available)~~
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/main/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [x] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)
- Hide unused features in the repository to reduce noise/irrelevant information:
  - [x] Click `Settings` and in repository settings uncheck `Wiki`, `Projects`, and `Discussions` (if they are currently not used)
  - [x] Click the settings icon next to `About` in the top-right corner of the repository main page and uncheck `Releases` and `Packages` (if they are currently not used)

Flywheel has this repository on GitLab. The repository is listed under the [`3d-slicer-extension`](https://gitlab.com/explore/projects/topics/3d-slicer-extension) topic on GitLab.

### CODE REVIEW

**Comment by deepakri201** [comment]
Hi Joshua, 

I'm a postdoc working at Brigham and Women's Hospital with @fedorov, where I'm working on a Slicer module for multi-parametric annotation of DICOM files. I'm therefore motivated and interested in trying out your extension, however, I do not have access to a flywheel instance. Is is possible to get access to a test instance to try your extension? 

Thank you!

Deepa

**Comment by joshicola** [comment]
@deepakri201 , I will check on access to an instance.

**Comment by joshicola** [comment]
@deepakri201 , please email me at joshuajacobs@flywheel.io with a Google-enabled account and I will enable it on a specific Flywheel instance.

**Comment by deepakri201** [comment]
Thank you! I've e-mailed you.

**Comment by deepakri201** [comment]
Hi @joshicola, 

Thank you for access to the test Flywheel instance -- I'm able to export the results as a csv file and install the extension in Slicer. In Flywheel I generated an API key, and copied this key into the appropriate space in the extension. However, I seem unable to connect to the Flywheel instance:

image

Thanks!

**Comment by joshicola** [comment]
Thank You, @deepakri201 ,

- I just did a Merge to the `main` branch from `develop` that brings the deployment branch up-to-date
- I was able to reproduce the error above when I pasted in an invalid api-key
  - By accident, I pasted in a URL to the [Google Installation Folder](https://drive.google.com/drive/u/5/folders/13MZ5DUShqhP9nc0hGGihKcKEBLiOBqTk).
  - I also altered a valid api-key (url portion and key portion) and reproduced the error.
- Once a valid API-Key was used, I was able to log in.
- If you are able to log in with the flywheel CLI, that API-Key will be stored in an accessible manner to the Extension.
  - Could you try this (without pasting in the api-key)?

**Comment by deepakri201** [comment]
Hi @joshicola, 

Thanks for your response. I tried again with and without pasting in the api-key, and unfortunately ran into the same error:

image

In the Slicer console, if I do the following: 
`import flywheel`
`fw_client = flywheel.Client(my_api_key)`
`fw_client.get_current_user() # this prints out my information correctly, however 'api_key' is None` 
`fw_client.get_current_user()["api_key"]["key"]`

I get the same error: 
image

Thanks again! 

Deepa

**Comment by joshicola** [comment]
Hello @deepakri201,

I apologize for the long delay.  I was pulled away on other commitments.

We had this error come up in another extension due to changes in a dependency.

This is now fixed in the [slicerflywheelcaseiterator](https://gitlab.com/flywheel-io/scientific-solutions/app/Slicerflywheelcaseiterator) repository.

Josh J.

**Comment by deepakri201** [comment]
Hi Josh, 

No problem at all! 

I was able to successfully connect to the flywheel instance :) 

However, when I load the table (from the csv file) and select `Start Batch` , I get the following error: 

flywheel_case_iterator_error

I've confirmed that the csv file has the `parent._id` and `file.name` fields. 

Thanks! 

Deepa

**Comment by joshicola** [comment]
@deepakri201 ,

The Flywheel instance we are using is a release candidate. It is without certain functionality that would make this process easier. 

I have put a `Case_Iterator_Files.csv` on the Information Tab of the Project we are collaborating with.  Please use this, and we can troubleshoot from there.

**Comment by deepakri201** [comment]
Hi @joshicola, 

I apologize for the delay. Could you please provide me the URL of the  `Case_Iterator_Files.csv`? I would be happy to test with that. 

Deepa

**Comment by deepakri201** [comment]
Hi @joshicola, 

Thank you for the `Case_Iterator_Files.csv`. I can connect to the flywheel instance and load the table, but when I click `Start Batch` it looks like it is unable to download the image from the container: 

image

Deepa

**Comment by joshicola** [comment]
@deepakri201 ,

Coming into focus after vacation.

The error you experienced is consistent with needing "[Developer Mode](https://gitlab.com/flywheel-io/scientific-solutions/app/Slicerflywheelcaseiterator#windows-requirements)" in Windows.

Recent changes to the repository include a modal popup notifying the user of this requirement with a link to the relevant portion of the README.md that suggests solutions.

**Comment by deepakri201** [comment]
Hi @joshicola, 

Thank you for that info -- after enabling Developer Mode and running Slicer as Administrator, I was able to use `Start Batch ` :) 

It worked for 4 out of the 5 patients, where I was able to add new segmentations and save out the corresponding nifti files. For the 5th patient though, the nifti file was able to load and I could draw a segmentation, however the segments were not able to be saved. 

image

Everything else worked as expected though, so I would recommend that this extension be accepted. 

Deepa

**Comment by joshicola** [comment]
@deepakri201 ,

Thanks for the recommendation.

I have confirmed that the error you are seeing is from a known issue with Python and [Long Paths in Python on Windows](https://stackoverflow.com/questions/29557760/long-paths-in-python-on-windows).  This fix will be included in a future release.

**Comment by joshicola** [comment]
@deepakri201 ,
Do you know of the next steps for this Slicer Extension?

**Comment by fedorov** [comment]
@joshicola it's not a concern for merging, but you might want to double check the first line in the license - might be a carry-over from another repo?

https://gitlab.com/flywheel-io/scientific-solutions/app/Slicerflywheelcaseiterator/-/blob/develop/LICENSE.txt?ref_type=heads#L1

**Comment by fedorov** [comment]
Given thorough review by @deepakri201 and quick check of license, docs and repo, loooks good, and I am merging it!

Thank you for the contribution @joshicola and for the review @deepakri201 👍

**Pull request merged**
