### PR TITLE
ENH: Add SlicerOpenCV

### PR DESCRIPTION
**Pull request by naucoin**
The SlicerOpenCV extension provides the OpenCV library for other extensions to build
against and use. It also provides the ITK module Video Bridge OpenCV.

### CODE REVIEW

**Comment by jcfr** [comment]
Niceee.

Would it make sense to address https://github.com/SBU-BMI/SlicerOpenCV/issues/13 before integrating ? 

Before moving forward, would it also make sense to have a working prototype of SlicerPathology extension first ?   

I just wonder if, at that stage, it makes sense to give more work to the factory (build machine).

**Comment by naucoin** [comment]
Yes, let me address that issue first and do a new pull request. 
We'll discuss options on this afternoon's tcon for going forward, I wanted to get this up so that it would go into the factory mechanism so I could fix any lingering cross platform issues, but yes, that would put more work on the factory.

**Comment by naucoin** [comment]
I'm also working on a simpler extension to provide usage examples of building against SlicerOpenCV and using opencv functionality.

**Comment by fedorov** [comment]
> I just wonder if, at that stage, it makes sense to give more work to the factory (build machine).

@jcfr at this point, this is a choice of giving more work to a human, or to a factory machine. I didn't think that it would add too much work that could break things on the factory side by adding a new extension. Can you explain what is the concern?

**Comment by naucoin** [comment]
I updated the module to include some logos that can be referenced, but hid the GUI. I can collapse the commits to the Extension index as well.

**Comment by naucoin** [comment]
@jcfr updated the extension to disable finding java and squashed all the commits, this is ready to merge from my side.

**Comment by jcfr** [comment]
:+1:

**Comment by fedorov** [comment]
:+1:

**Comment by naucoin** [comment]
@jcfr: when should I expect to see build / test reports in the Extensions-Nightly section of the dashboard for SlicerOpenCV?

**Comment by jcfr** [comment]
It is missing `CTestConfig` ... 

Seems it is an issue with https://github.com/Slicer/Slicer/blob/97f63eef2642f8e56c6a3e4c879b5f53202676bc/Extensions/CMake/SlicerBlockBuildPackageAndUploadExtension.cmake#L101-L114

If it doesn't exist, it should be created.

Note: Ideally, CMake/CTest should be improved to make this an optional requirements.


```
kitware@factory-south-ubuntu:~/Dashboards/Nightly/S-0-E-b$ make SlicerOpenCV
[100%] Performing update step for 'SlicerOpenCV'
[100%] No configure step for 'SlicerOpenCV'
[100%] No forcebuild step for 'SlicerOpenCV'
[100%] Performing build step for 'SlicerOpenCV'
* Extra verbosity turned on
Reading Script: /home/kitware/Dashboards/Nightly/Slicer-0/Extensions/CMake/SlicerBlockBuildPackageAndUploadExtension.cmake
-- Setting EXTENSION_CATEGORY ..................: Libraries
-- Setting EXTENSION_CONTRIBUTORS ..............: Nicole Aucoin (BWH), Andrey Fedorov (BWH), Jean-Christophe Fillion-Robin  [...]
-- Setting EXTENSION_DESCRIPTION ...............: This extension provides a wrapper around OpenCV libraries
-- Setting EXTENSION_HOMEPAGE ..................: http://slicer.org/slicerWiki/index.php/Documentation/Nightly/Extensions/S [...]
-- Setting EXTENSION_ICONURL ...................: https://raw.githubusercontent.com/SBU-BMI/SlicerOpenCV/master/SlicerOpenC [...]
-- Setting EXTENSION_SCREENSHOTURLS ............: 
-- Setting EXTENSION_STATUS ....................: 
-- Found Git: /usr/bin/git  
SetCTestConfiguration:SourceDirectory:/home/kitware/Dashboards/Nightly/S-0-E-b/SlicerOpenCV
SetCTestConfiguration:BuildDirectory:/home/kitware/Dashboards/Nightly/S-0-E-b/SlicerOpenCV-build
Run dashboard with model Nightly
   Source directory: /home/kitware/Dashboards/Nightly/S-0-E-b/SlicerOpenCV
   Build directory: /home/kitware/Dashboards/Nightly/S-0-E-b/SlicerOpenCV-build
   Track: Extensions-Nightly
Cannot locate CTest configuration: in BuildDirectory: /home/kitware/Dashboards/Nightly/S-0-E-b/SlicerOpenCV-build/CTestConfig.cmake
Cannot locate CTest configuration: in SourceDirectory: /home/kitware/Dashboards/Nightly/S-0-E-b/SlicerOpenCV/CTestConfig.cmake
SetCTestConfigurationFromCMakeVariable:Site:CTEST_SITE
SetCTestConfiguration:Site:factory-south-ubuntu
SetCTestConfigurationFromCMakeVariable:BuildName:CTEST_BUILD_NAME
SetCTestConfiguration:BuildName:24963-SlicerOpenCV-git419589a-g++-64bits-Qt4.8-Release
   Site: factory-south-ubuntu
   Build name: 24963-SlicerOpenCV-git419589a-g++-64bits-Qt4.8-Release
WARNING: No nightly start time found please set in CTestConfig.cmake or DartConfig.cmake
CMake Error at /home/kitware/Dashboards/Nightly/Slicer-0/Extensions/CMake/SlicerBlockBuildPackageAndUploadExtension.cmake:122 (ctest_start):
  ctest_start unknown error.


SetCTestConfiguration:BuildDirectory:/home/kitware/Dashboards/Nightly/S-0-E-b/SlicerOpenCV-build
SetCTestConfiguration:SourceDirectory:/home/kitware/Dashboards/Nightly/S-0-E-b/SlicerOpenCV
SetCTestConfiguration:ConfigureCommand:"/home/kitware/Dashboards/Support/cmake-3.5.0-rc3-Linux-x86_64/bin/cmake" "-DCMAKE_BUILD_TYPE:STRING=Release" "-GUnix Makefiles" "/home/kitware/Dashboards/Nightly/S-0-E-b/SlicerOpenCV"
Configure project
Current Tag empty, this may mean NightlyStartTime / CTEST_NIGHTLY_START_TIME was not set correctly. Or maybe you forgot to call ctest_start() before calling ctest_configure().
Cannot open configure file
make[3]: *** [SlicerOpenCV-prefix/src/SlicerOpenCV-stamp/SlicerOpenCV-build] Error 255
make[2]: *** [CMakeFiles/SlicerOpenCV.dir/all] Error 2
make[1]: *** [CMakeFiles/SlicerOpenCV.dir/rule] Error 2
make: *** [SlicerOpenCV] Error 2
```

**Pull request merged**
