### PR TITLE
ENH : add new extension SlicerConda

### PR DESCRIPTION
**Pull request by GaelleLeroux**
# New extension

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Any known related patents must be mentioned in the extension description.
- [x] LICENSE.txt is present in the repository root. MIT  (https://choosealicense.com/licenses/mit/) or Apache (https://choosealicense.com/licenses/apache-2.0/) license is recommended. If source code license is more restrictive for users than MIT, BSD, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (main, release, ...) instead of a specific git hash to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://raw.githubusercontent.com/user/repo/main/SomeIcon.png)
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [x] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/main/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [x] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)
- Hide unused features in the repository to reduce noise/irrelevant information:
  - [x] Click `Settings` and in repository settings uncheck `Wiki`, `Projects`, and `Discussions` (if they are currently not used)
  - [x] Click the settings icon next to `About` in the top-right corner of the repository main page and uncheck `Releases` and `Packages` (if they are currently not used)

### CODE REVIEW

**Comment by GaelleLeroux** [comment]
@allemangD @jcfr @pieper @lassoan  

Could you give me a review on this pull request or accept it if it seems right to you? 

Thank you :)

**Review by pieper — CHANGES_REQUESTED** [review]
I tried to review this but since I didn't have a windows or linux machine easily available I tried porting this to mac.  The patch below should work to get the correct miniconda installation file, but after that it wasn't clear to me how to use the module at all.

What's the difference between the "Miniconda/Anaconda-Path" and the "Folder install" ?  This should be made clear in the documentation.  I tried setting these to fresh temp directories but when I tried clicking the "Installation" button I got this error message:
```
[FD] /bin/sh: /private/tmp/conda/miniconda3/bin/conda: No such file or directory
```

This may be something specific to mac, but it's also possible that it has something to do with the expectations for what these folders should contain so maybe this indicates that better error detection is needed.

Also I noticed that some of the strings in the source file are in French.  These should be converted to English since that's the main reference language for the application.  If you want to consider providing French feedback to users, please consider internationalizing the extension as described here (https://github.com/Slicer/SlicerLanguagePacks).  But for this kind of utility it's probably not expected that a translation is available so all strings in English is the convention.

Also as a general comment it's still not clear to me how this module simplifies the process for end-users.  If they need to work with conda environments they will typically need to operate in a command shell of some kind, where relatively simple command line options already exist.  It would help for the documentation or example use cases to clarify how this module gets close to a pure gui environment to accomplish user tasks.


```
(base) pieper@flake SlicerConda % git diff
diff --git a/CondaSetUp/CondaSetUp.py b/CondaSetUp/CondaSetUp.py
index a0ff5e0..c28b148 100644
--- a/CondaSetUp/CondaSetUp.py
+++ b/CondaSetUp/CondaSetUp.py
@@ -1262,6 +1262,11 @@ class CondaSetUpCall():
                 filename = "Miniconda3-latest-Linux-x86_64.sh"
             else:
                 filename = "Miniconda3-latest-Linux-x86.sh"
+        elif system == "Darwin":
+            if machine == "x86_64":
+                filename = "Miniconda3-latest-MacoOSX-x86_64.sh"
+            elif machine == "arm64":
+                filename = "Miniconda3-latest-MacOSX-arm64.sh"
         else:
             raise NotImplementedError(f"Unsupported system: {system} {machine}")

```

**Comment by GaelleLeroux** [comment]
@allemangD @jcfr @pieper @lassoan

Would it be possible to have a second with the new changes I made on this pull request please?

Thank you :)

**Review by allemangD — APPROVED** [review]
I have a few nitpicks but I do not think they should prevent the extension from deploying so you can use it to manage environment in your teams other projects. Instead I'll approve and merge this PR, and open issues for those nitpicks directly on the DCBIA-OrthoLab/SlicerConda repository.

**Pull request merged**
