### PR TITLE
ENH: Add Thickness Mapping extension

### PR DESCRIPTION
**Pull request by e-simpson**
## Description:

This extension calculates the bone thickness of a volume and visualizes it with a gradient map overlay on the rendered volume.

## Contributors:

Evan Simpson (Western University)

# TODO list for submitting a new extension

- [x] Extension has a reasonable name
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic
- [x] Extension description summarizes in 1-2 sentences what the extension is usable
- [x] Extension URL and revision (scmurl, scmrevision) is correct
- [x] Extension icon URL is correct
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [ ] Publication: link to publication and/or to PubMed reference (if available)
  - [x] BSD-3-Clause License

### CODE REVIEW

**Comment by pieper** [comment]
LGTM 👍

**Comment by lassoan** [comment]
- [Project name](https://github.com/Auditory-Biophysics-Lab/SlicerBoneThicknessMappingExtension/blob/master/CMakeLists.txt#L3) must not contain spaces. It should be BoneThicknessMapping
- [Extension homepage](https://github.com/Auditory-Biophysics-Lab/SlicerBoneThicknessMappingExtension/blob/master/CMakeLists.txt#L7) should be the repository URL
- [Icon URLs](https://github.com/Auditory-Biophysics-Lab/SlicerBoneThicknessMappingExtension/blob/master/CMakeLists.txt#L11) are mandatory

**Comment by e-simpson** [comment]
Thanks for the feedback and thorough analysis! I have completed the items checked below and noted the commits. Great catch on the dimensions/spacing usage, I will re-implement this and reply/edit this list when completed.

- [x] Project name must not contain spaces
**Commit:** https://github.com/Auditory-Biophysics-Lab/SlicerBoneThicknessMappingExtension/commit/9b85b14f4e82d82a7be9b1e7a92404d4ab408821
- [x] Extension homepage should be repository URL
**Commit:** https://github.com/Auditory-Biophysics-Lab/SlicerBoneThicknessMappingExtension/commit/9b85b14f4e82d82a7be9b1e7a92404d4ab408821
- [x]  Icon URLs are mandatory
**Commit:** https://github.com/Auditory-Biophysics-Lab/SlicerBoneThicknessMappingExtension/commit/9b85b14f4e82d82a7be9b1e7a92404d4ab408821
- [x] Make the module Python3 (Slicer-4.11) compatible
**Commit:** https://github.com/Auditory-Biophysics-Lab/SlicerBoneThicknessMappingExtension/commit/cab3754bf43094dba3295fabbb81627801916593
- [x] Use ctk.ctkAxesWidget instead of hard-coded directions
**Commit:** https://github.com/Auditory-Biophysics-Lab/SlicerBoneThicknessMappingExtension/commit/9ef7f36d8d4489192595b1874901a76bdf25a520
- [x] Why vtkUnsignedCharArray used
**Commit:** https://github.com/Auditory-Biophysics-Lab/SlicerBoneThicknessMappingExtension/commit/60980946784b04858030c95877d4820c96179c39
- [ ] Usage of "dimensions", image spacing should be taken into account
- [ ] Create a very simple tutorial

**Comment by lassoan** [comment]
Note that often images axes are permutated (first voxel array axis may not the same as first physical coordinate system axis), so to get from voxel space to physical space, you need to multiply homogeneous coordinates by IJKToRAS matrix.

**Comment by e-simpson** [comment]
The list items are now complete.

In response to: 
> Note that often images axes are permutated (first voxel array axis may not the same as first physical coordinate system axis), so to get from voxel space to physical space, you need to multiply homogeneous coordinates by IJKToRAS matrix.

The thickness values are calculated based on the points found in the rendered segmentation. I ran a few tests (different image spacing values, different volumes) and compared the module's calculation 
 and that of the Ruler distance tool in Slicer. The values were the same and correctly updated when the image spacing was manipulated. So in this way, the thickness calculations are accurate?

**Comment by e-simpson** [comment]
Is there anything I can do to help this module merged to the Slicer Extension Index?

**Comment by lassoan** [comment]
Thank you. Merged.

**Pull request merged**
