### PR TITLE
Submitting a new extension LesionSimulatorExtension.

### PR DESCRIPTION
**Pull request by fsimozo**
# Submitting a new extension

Multiple Sclerosis multimodal lesion simulation tool (MS-MIST)

This extension offers a set of tools for brain lesion simulation, based on MRI images. At the moment, the modules MS Lesion Simulator and MS Longitudinal Lesion Simulator are available, where it can simulate both baseline scan lesion volumes (given a lesion load) and longitudinal image simulations, respectively. In summary, a statistical lesion database is generated based on a set of manual lesion mark-ups, being non-linearly registered to MNI152 space (isotropic 1mm of voxel resolution). Using a small set of parameters (lesion load, lesion homogeneity, lesion intensity independence and lesion variability), it is possible to generate a broad range of MS lesions patterns in multimodal MRI imaging techniques (at moment, T1, T2, T2-FLAIR, PD, DTI-FA and DTI-ADC images are provided). For more details about this project, please see the original paper (DOI: 10.1088/2057-1976/ab08fc ) and the wiki page.

### CODE REVIEW

**Comment by pieper** [comment]
LGTM!

**Comment by lassoan** [comment]
Thank you for contributing to 3D Slicer! This will be awesome.

To make sure users can find your extension, understand what it is intended for and how to use it, please complete the checklist below. Most likely your pull request will only be merged if all the items in the checklist are addressed.

- [ ] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for) => there are many kind of lesions, include multiple sclerosis, for example SlicerMSLesionSimulator
- [ ] Repository name is Slicer+ExtensionName => no need for a dash, no need to include "Extension", for example this would work: SlicerMSLesionSimulator
- [ ] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts) => Remove this incomplete sentence from the extension's README.md file: "At the moment, the Modules available …"
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct => very nice!
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [ ] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [ ] Publication: link to publication and/or to PubMed reference (if available) => please also consider adding a link to the manuscript (many people do not have access to the journal)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/master/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work.
Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.

See more information about the submission process on the Slicer wiki: https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/BuildTestPackageDistributeExtensions

**Comment by acsenrafilho** [comment]
Thanks @lassoan for the commentaries. 
We made the following corrections:

- [x]  Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts) => Remove this incomplete sentence from the extension's README.md file: "At the moment, the Modules available …" ==> **The README.md file was corrected regarding this meaningless phrase and also improved about the paper information**

- [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set ==> **A simple tutorial informing the most usual simulation procedure was added in the [wiki page](https://www.slicer.org/wiki/Documentation/4.10/Extensions/LesionSimulator#Tutorials)**

- [x] Publication: link to publication and/or to PubMed reference (if available) => please also consider adding a link to the manuscript (many people do not have access to the journal) ==> **We decided to highlight the [possibility to get a private copy of our paper by an email contact](https://www.slicer.org/wiki/Documentation/4.10/Extensions/LesionSimulator#References) instead, mainly because of journal publication policies**

There are another two questions that will be addressed in the following days.

**Comment by lassoan** [comment]
Thank you, I've merged this pull request now. If your extension is also compatible with latest stable (4.10.x) then submit a pull request in the `4.10` branch of this repository.

> We decided to highlight the possibility to get a private copy of our paper by an email contact instead, mainly because of journal publication policies

I agree that you should not upload the published version of the paper (that is processed by the journal and made available on the journal's website). However, if you want users to read and cite your paper then you need to make the _manuscript_ easily accessible. You are allowed to make the original manuscript publicly available on your website and after the embargo period expires (typically 12 months) you can upload the accepted manuscript as well. See https://publishingsupport.iopscience.iop.org/questions/what-green-open-access-options-does-iop-offer/.

**Pull request merged**
