### PR TITLE
ENH: Add Dental Segmentator

### PR DESCRIPTION
**Pull request by Thibault-Pelletier**
* Fully automatic AI segmentation tool for Dental CT and CBCT scans based on DentalSegmentator nnU-Net model.

# New extension

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Any known related patents must be mentioned in the extension description.
- [x] LICENSE.txt is present in the repository root. MIT  (https://choosealicense.com/licenses/mit/) or Apache (https://choosealicense.com/licenses/apache-2.0/) license is recommended. If source code license is more restrictive for users than MIT, BSD, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (main, release, ...) instead of a specific git hash to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://raw.githubusercontent.com/user/repo/main/SomeIcon.png)
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [x] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/main/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [x] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)
- Hide unused features in the repository to reduce noise/irrelevant information:
  - [x] Click `Settings` and in repository settings uncheck `Wiki`, `Projects`, and `Discussions` (if they are currently not used)
  - [x] Click the settings icon next to `About` in the top-right corner of the repository main page and uncheck `Releases` and `Packages` (if they are currently not used)

### CODE REVIEW

**Comment by pieper** [comment]
I took a quick look and the extension looks really nice 👍 

One easy request: 

> "AP-HP, Arts et metiers and financed by the FFO (Fédération Française d'Orthodonthie"

Could you include hyperlinks in your readme file to the homepages related to the organizations involved?  (I'm not personally familiar with them).

Also, I'm not an expert here, but there seems to be synergy with [the SlicerCMF work](https://github.com/DCBIA-OrthoLab) so is it possible to integrate the extensions?  Maybe @bpaniagua can have a look?

**Comment by Thibault-Pelletier** [comment]
Hi  @pieper, thanks for your comments! I just added the hyperlinks to the documentation.
Regarding the integration with the SlicerCMF work, I will let the developers of the AI model chip in on our end!

**Comment by lassoan** [comment]
The extension indeed looks nice. It would be great if you would switch to SlicerPyTorch extension for installing PyTorch to reduce maintenance and user support for both your extension and Slicer core developers (less code to maintain and troubleshoot).

We would probably also need to add an extension for installing and launching nnunet inference, because more and more extensions use nnunet (TotalSegmentator, MEMOS, HD-BET, ...) and they either need to implement all the nnunet installation patches or they will just not work on many user's computers. Currently, TotalSegmentator has the most robust nnunet installation logic, so that could be moved out into an extension that all the other nnunetv2-based extensions could use.

An alternative would be to train MONAI Auto3DSeg with the same training data. Auto3DSeg has a few advantages, such as faster training, cleaner implementation, cleaner installation, less dependencies, better documentation; and similar overall performance.

**Comment by Thibault-Pelletier** [comment]
Thanks for the feedback @lassoan !

Regarding the nnUNet install, do you want me to go ahead and extract the total segmentator code in a separate extension to be reused by nnUNet based modules down the line (including this one)?

I think we could also provide the same type of runner for nnUNet based models as what we have in the Auto3DSeg extension / MONAI bundles and point to a folder containing the nnUNet folds and allow to run it in 3D Slicer on a given volume node.

What do you think?

**Comment by GauthierDot** [comment]
> Also, I'm not an expert here, but there seems to be synergy with [the SlicerCMF work](https://github.com/DCBIA-OrthoLab) so is it possible to integrate the extensions? Maybe @bpaniagua can have a look?

Hello @pieper, thank you for your input! Indeed this module is close to SlicerCMF work, and more particularly AMASS module from Slicer Automated Dental Tools. The main difference between the two modules are the segmentation classes: our model delineates upper & lower teeth, while AMASS model delineates maxilla & cranial base & cervical vertebra. 

Due to these differences, we believe the 2 extensions would have different publics, with SlicerCMF targeting primarily CMF radiologists and maxillofacial surgeons, while our module is targeting primarily dentists working with digital workflows. 

Of course, we would be glad to discuss more about integration possibilities if you think it would be beneficial for the users!

**Comment by Thibault-Pelletier** [comment]
@lassoan and @GauthierDot for information, I just started the following Github repository for the SlicerNNUNet Install and Run logic : https://github.com/KitwareMedical/SlicerNNUnet

I moved the install logic which was in TotalSegmentator there. The install logic was a little lacking (if a sub depedency was installing torch, it was installed anyway) which I have fixed in the repository.

This is still a work in progress. It should be operational sometimes next week. I plan to create a new PR for it in the SlicerExtensionIndex and refactir the DentalSegmentator to make use of the install / run components.

**Comment by lassoan** [comment]
@Thibault-Pelletier thanks a lot for working on this. The nnUnet Slicer extension is very nice, I added some comments to make it a bit simple, more reusable, and more consistent with some of the Slicer extension conventions.

**Comment by Thibault-Pelletier** [comment]
@lassoan Thanks for your review! I'll be working on it starting tomorrow and let you know when I have fixed everything :)

**Comment by Thibault-Pelletier** [comment]
@lassoan I have updated this PR to leverage the work done on [the NNUNet module](https://github.com/Slicer/ExtensionsIndex/pull/2023). Let me know if I need to change things in this module or the NNUNet one!

**Comment by lassoan** [comment]
I've tested it on Windows. Segmentation by a single click worked flawlessly. Nice job!

image

**Comment by Thibault-Pelletier** [comment]
Thank you very much for the merge!

**Pull request merged**
