### PR TITLE
Add SlicerANTs

### PR DESCRIPTION
**Pull request by simonoxen**
# TODO list for submitting a new extension

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Any known related patents must be mentioned in the extension description.
- [x] If source code license is more restrictive for users than BSD, MIT, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://github.com/user/project/raw/main/path/to/icon.png)
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [x] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/master/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [x] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)

### CODE REVIEW

**Comment by lassoan** [comment]
Thanks a lot for working on this!

One quick observation: it seems that ANTs rebuilds entire ITK, while it is already available in the Slicer build tree. This would result in very long build time and larger package size (and maybe even some ITK version conflicts). Please use USE_SYSTEM_ITK CMake flag and pass ITK_DIR to ANTs to make it use Slicer's ITK. If for testing on your own computer you want to preserve the ability to build the extension without building ITK as part of Slicer then you can add a flag to your project to choose between the two behaviors.

Have you tested building and packaging on windows, mac, and linux? Especially mac has some tricky issues with rpaths, etc. that require testing.

Instead of using low-level QTableView widgets, you could consider using `slicer.qMRMLTableView()`. It takes care of storing the table's content in the scene.

I see that there is a Slicer CLI module in the ANTs repository (antsRegistrationCLP). Have you considered using/updating that? The main advantage of a CLI module (as opposed to calling an executable using Python exec) that it can be executed in the background (and input/output parameters are automatically written to files and read from files by Slicer).

Have you looked at https://github.com/ANTsX/ANTsPy? If you only plan to use ants from Python modules (not from C++) then it could be a low-maintenance option (you don't need to deal with building and packaging of ants). We created SlicerElastix module before Elastix had any kind of Python wrapper, but since most algorithm packages are now available in Python, we have the option to leverage them.

**Comment by simonoxen** [comment]
Ah true, I didn't try using system ITK, I think there was an error at first so disabled it. Will give it a try.

Did test building on win and mac. I should test the package - I didn't get the documentation at first but now I think I understand.

Wasn't aware of antsRegistrationCLP. CLI makes sense for executing in the background, but would it constrain me of how I customise the widget? It is defined from the xml, right? 

Didn't think of using ANTsPy directly, I'm used to using the executable from command line. Not sure if I would dig into ANTs code base but I like the idea that am able to. But it's true that is it more straightforward for maintenance and so on.

Perhaps we can find a good way of implementing the CLI option. Run it in the background and integrate well without blocking Slicer

Thanks for the feedback!

**Comment by lassoan** [comment]
> Wasn't aware of antsRegistrationCLP. CLI makes sense for executing in the background, but would it constrain me of how I customise the widget? It is defined from the xml, right?

You would keep the current, nice and convenient GUI, but there would be an automatically generated GUI (that users would not use, maybe developers could use for testing). You would call that CLI module from your Python scripted module.

> Didn't think of using ANTsPy directly, I'm used to using the executable from command line. Not sure if I would dig into ANTs code base but I like the idea that am able to.

There could be indeed good reasons why it could be useful to build your own ANTs (such as building a modified version of it), but it may or may not worth the extra maintenance effort. Since you already implemented the extension this way, you can keep it like this (especially if everything works well on all platforms).

> Did test building on win and mac. I should test the package - I didn't get the documentation at first but now I think I understand.

Yes, you need to build the package and then test it on a different computer (or on the same computer, but moving your build tree somewhere else, to make sure that the installed files do not rely on any content of the build tree). Mac is tricky because of the rpath (binaries need to be fixed up before packaging). Packaging on Linux is not particularly difficult, it just slightly differs from the other platforms, so you need to make sure that library names and install locations are correct.

**Comment by simonoxen** [comment]
I looked a bit into ANTsPy, but there's not Windows package and build fails.

I'm now able to use system ITK (adding a few modules to ITK - I just made a PR for this) and it's building on mac and win. I'll work on the packages next.

> but there would be an automatically generated GUI 

Is there an example of this?

I know this PR was soon for merging but helped to think about this things, thanks for the comments!

**Comment by simonoxen** [comment]
Hi @lassoan, packages for mac and win seem to be working. 

[29935-win-amd64-SlicerANTs-git8801192-2021-06-03.zip](https://github.com/Slicer/ExtensionsIndex/files/6591163/29935-win-amd64-SlicerANTs-git8801192-2021-06-03.zip)
[29937-linux-amd64-SlicerANTs-git8801192-2021-06-03.tar.gz](https://github.com/Slicer/ExtensionsIndex/files/6591164/29937-linux-amd64-SlicerANTs-git8801192-2021-06-03.tar.gz)
[29939-macosx-amd64-SlicerANTs-git8801192-2021-06-03.tar.gz](https://github.com/Slicer/ExtensionsIndex/files/6591165/29939-macosx-amd64-SlicerANTs-git8801192-2021-06-03.tar.gz)

Not sure if testing correctly, Should we give it a try?

**Comment by lassoan** [comment]
Sounds good. I'm building the extension now.

In the meantime, would you mind finishing these tasks:
- Description of contained modules: at one sentence for each module => just provide the module name and a one-sentence description
- Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set => just a bullet-point list of 3-4 items, what sample data to use, what parameters to set
- At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot. => just show the screenshot of the tutorial segmentation result (maybe two screenshots - before and after registration)

**Comment by lassoan** [comment]
>  Publication: link to publication and/or to PubMed reference (if available)

For this, you can just add a link to the paper that ANTs developers designated to cite ANTs.

**Comment by simonoxen** [comment]
Done 👍. is there an example of an automatically generated GUI for CLI module? I usually encounter the xml definitions.

Thanks!

**Comment by lassoan** [comment]
You can open any of the [CLI modules](https://github.com/Slicer/Slicer/tree/master/Modules/CLI) to see how they look. There is limitation in how flexible these auto-generated GUIs are (e.g., there are no conditional display or enable/disable of a widget based on another widget's value), so usually Python scripted modules are more user-friendly. But these GUIs are sufficient for some simple cases and convenient for testing (and it allows background execution, etc.).

**Comment by lassoan** [comment]
Could you create an icon for the module? Using the default icon suggests that it is a work-in-progress or it is a low-quality module (that was just quickly hacked together to try something) - which is clearly not the case.

**Comment by lassoan** [comment]
I've tested the extension and it works amazingly well! Once I figured how to specify input images, it worked great. Registration results with the built-in presets were very good. The registration pipeline editor is very powerful, it exposes a lot of options and registration experts should be able to figure out how to adjust the parameters. There are just a few small but essential usability improvements to make the module usable for average users.

- A few files were missed from the packaged extension - sent a [pull request with the fix](https://github.com/simonoxen/SlicerANTs/pull/1). You can test locally by building the PACKAGE target in the inner-build project and install the generated zip file in the Extensions manager.
- There are 800MB of example applications built (c:\D\SlicerANTs_R\ants-build\ANTS-build\Examples). They are not included in the package. I guess they are really just examples. It would be better to disable building them by default to keep build time and disk space usage unnecessarily high.
- Put the Stages selector/editor into an advanced section (collapsed by default) and just make the preset selector visible by default. Only very few people would be capable of designing good registration pipelines, and most people would have no idea what to do with the very powerful but very complicated registration pipeline editor.
- It took me 10 minutes to find where to set input volumes!!! Add a fixed and moving image selector in the non-advanced (visible by default) section of the module. If necessary, use a heuristic to figure out which input fields they correspond to.
- It is hard to know if the registration is still in progress or not:
  - Show the wait cursor while registration is running (`setOverrideCursor`)
  - Change the "Run registration" button to "Cancel" and implement cancelling of the registration. as it is done in SlicerElastix.
- Make sure the application remains responsive. I added a bspline transform step, which made the entire application hang. I don't remember having this issue with Elastix (maybe because Elastix does not go for very long time without logging anything). Instead of `process.stdout.readline`, switch to the safer (non-infinitely-blocking) `subprocess.communicate()`. This allows keeping the loop in Slicer alive and give a chance to kill the registration process.
- Show total elapsed time in non-scientific format (currently it is hard to read this: "Total elapsed time: 3.6012e+01")
- Add an option to save the current preset.

**Comment by simonoxen** [comment]
Thanks a lot for the comments and PR! Will work on this.

Yes, the ui is probably complicated for average users. With the design I wanted to make the point that multiple metrics with multiple images can be used to guide registration. And this is the main advantage that I see integrating with Slicer: you can for example segment structures of interest in source and target images and use the segmentations as a metric as well (and perhaps with more metric weight). (or also source and target markups - although I realised ANTs doesn't have csv input - will have to add this).

But just having a visible fixed and moving for most cases makes total sense.

It's weird, actually in Examples is where the main apps of ANTs are. There are still some that can be disabled.

Thanks!

**Comment by simonoxen** [comment]
I moved the subprocess call to a scripted cli module _antsCommand_. This might be also useful for other users wanting to use ants. Only disadvantage is that I don't see the command output as before.

Removed unnecessary parts of the build and now it's around 420mb.

Made changes in the gui to have the input more straightforward and the advanced section collapsed.

Also made possible to cancel the process and save presets.

Probably still some testing necessary and some work to make it more robust.

**Comment by lassoan** [comment]
Great improvements! However lack of process output would be a major regression. At least return the complete output as a table node. The Python scripted CLI could write a .csv file with two columns: first column containing output type (info or error); second column containing the output text. CLI modules can also do continuous progress reporting but that may be implemented later.

**Comment by simonoxen** [comment]
Hi, I was testing the CLI continuous reporting and not sure if I understand how it works

I tested the example in the [python FAQ](https://www.slicer.org/wiki/Documentation/Nightly/Developers/FAQ) and the [Create DICOM Series](https://github.com/Slicer/Slicer/blob/0094e9a35bd266cc8b0e677858dabce797c9928f/Modules/CLI/CreateDICOMSeries/CreateDICOMSeries.cxx) Module. Both of which contain the `<filter-start>`, `<filter-comment>` and `<filter-progress>` XML commands. The progress bar does gets updated but no comments are seen in the window. Is this the expected behaviour?

**Comment by lassoan** [comment]
See progress reporting specification here: https://www.slicer.org/wiki/Documentation/Nightly/Developers/SlicerExecutionModel#Showing_Progress_in_an_Application

I've captured the output of Model Maker CLI module, which correctly reports progress (you can see details reported):

```text
<filter-progress>0.128965</filter-progress>
<filter-stage-progress>0.750899</filter-stage-progress>
<filter-progress>0.129109</filter-progress>
<filter-stage-progress>0.800959</filter-stage-progress>
<filter-progress>0.129254</filter-progress>
<filter-stage-progress>0.851019</filter-stage-progress>
<filter-progress>0.129398</filter-progress>
<filter-stage-progress>0.901079</filter-stage-progress>
<filter-progress>0.129542</filter-progress>
<filter-stage-progress>0.951139</filter-stage-progress>
<filter-progress>0.129683</filter-progress>
<filter-stage-progress>1</filter-stage-progress>
<filter-end>
<filter-name>vtkStripper</filter-name>
</filter-end><filter-start>
<filter-name>vtkPolyDataWriter</filter-name>
<filter-comment> "Write Model_17_semitendinosus_muscle" </filter-comment>
</filter-start>
<filter-progress>0.129683</filter-progress>
<filter-stage-progress>0</filter-stage-progress>
<filter-start>
<filter-name>vtkPolyDataWriter</filter-name>
<filter-comment> "Write Model_17_semitendinosus_muscle" </filter-comment>
</filter-start>
<filter-end>
<filter-name>vtkPolyDataWriter</filter-name>
</filter-end><filter-progress>0.132565</filter-progress>
<filter-stage-progress>1</filter-stage-progress>
<filter-end>
<filter-name>vtkPolyDataWriter</filter-name>
</filter-end>Skipping marching cubes...
<filter-start>
<filter-name>vtkDecimatePro</filter-name>
<filter-comment> "Decimate Model_18_gracilis_muscle" </filter-comment>
</filter-start>
<filter-progress>0.135447</filter-progress>
<filter-stage-progress>0</filter-stage-progress>
<filter-progress>0.135447</filter-progress>
<filter-stage-progress>0</filter-stage-progress>
<filter-progress>0.136167</filter-progress>
<filter-stage-progress>0.25</filter-stage-progress>
<filter-progress>0.138329</filter-progress>
<filter-stage-progress>1</filter-stage-progress>
<filter-end>
<filter-name>vtkDecimatePro</filter-name>
</filter-end><filter-start>
<filter-name>vtkTransformPolyDataFilter</filter-name>
<filter-comment> "Transform Model_18_gracilis_muscle" </filter-comment>
</filter-start>
<filter-progress>0.14121</filter-progress>
<filter-stage-progress>0</filter-stage-progress>
<filter-progress>0.141787</filter-progress>
<filter-stage-progress>0.2</filter-stage-progress>
<filter-progress>0.142939</filter-progress>
<filter-stage-progress>0.6</filter-stage-progress>
<filter-progress>0.143516</filter-progress>
<filter-stage-progress>0.8</filter-stage-progress>
<filter-progress>0.144092</filter-progress>
<filter-stage-progress>1</filter-stage-progress>
<filter-end>
<filter-name>vtkTransformPolyDataFilter</filter-name>
</filter-end><filter-start>
<filter-name>vtkPolyDataNormals</filter-name>
<filter-comment> "Normals Model_18_gracilis_muscle" </filter-comment>
</filter-start>
<filter-progress>0.144092</filter-progress>
<filter-stage-progress>0</filter-stage-progress>
<filter-progress>0.14438</filter-progress>
<filter-stage-progress>0.1</filter-stage-progress>
<filter-progress>0.145052</filter-progress>
<filter-stage-progress>0.333</filter-stage-progress>
<filter-progress>0.145052</filter-progress>
<filter-stage-progress>0.333</filter-stage-progress>
<filter-progress>0.145175</filter-progress>
<filter-stage-progress>0.375725</filter-stage-progress>
<filter-progress>0.145298</filter-progress>
<filter-stage-progress>0.41845</filter-stage-progress>
<filter-progress>0.145421</filter-progress>
<filter-stage-progress>0.461176</filter-stage-progress>
<filter-progress>0.145544</filter-progress>
<filter-stage-progress>0.503901</filter-stage-progress>
<filter-progress>0.145668</filter-progress>
<filter-stage-progress>0.546626</filter-stage-progress>
<filter-progress>0.145791</filter-progress>
<filter-stage-progress>0.589351</filter-stage-progress>
<filter-progress>0.145914</filter-progress>
<filter-stage-progress>0.632076</filter-stage-progress>
<filter-progress>0.146398</filter-progress>
<filter-stage-progress>0.8</filter-stage-progress>
<filter-progress>0.146974</filter-progress>
<filter-stage-progress>1</filter-stage-progress>
<filter-end>
<filter-name>vtkPolyDataNormals</filter-name>
</filter-end><filter-start>
<filter-name>vtkStripper</filter-name>
<filter-comment> "Strip Model_18_gracilis_muscle" </filter-comment>
</filter-start>
...
```

image

**Comment by lassoan** [comment]
I've debugged into this and found that the problem is that the text is only displayed if the filter stage progress is non-zero. I'll submit a fix tomorrow but until then you can set the filter stage progress to 1 as a workaround to make the filter comment appear in the GUI.

**Comment by simonoxen** [comment]
Great, thanks! I'm able now to report progress from CLI. Currently showing % of levels completed (as filter progress) and % of iterations for the current level completed (as filter stage progress). Also showing the Stage name that is running.

thanks 👍

**Comment by lassoan** [comment]
Sounds great. It looks like everything is in order, so I'll merge this pull request now.

**Comment by lassoan** [comment]
Please check tomorrow if the extension shows up in the extension manager in Slicer and works correctly. Thanks a lot for this excellent contribution!

**Pull request merged**
