### PR TITLE
ENH: Add AnomalousFiltersExtension extension

### PR DESCRIPTION
**Pull request by acsenrafilho**
Description:
This extension aims to provide several approaches in order to apply the
anomalous spatial filters on medical images. The methods provided here
are numerical solution of the generalized anomalous diffusion proposed
by Constantino Tsallis, which, in other words, provide a numerical
solution to the porous media equation (Fokker-Planck anomalous heat
equation). At the moment, the Modules available are suppose to be used
on scalar volumes, mainly MRI strucutral images namely T1 and T2
weighted images. Future developments will add new functionalities in
order to attenuate image noise in other imaging modalities, such as
diffusion weighted images (DWI and DTI). More details could be found in
the wiki page.

Contributors:
Antonio Carlos Senra Filho (University of Sao Paulo), Luiz Otavio Murta
Junior (University of Sao Paulo)

### CODE REVIEW

**Comment by acsenrafilho** [comment]
Hi,

I just want to add my AnomalousFiltersExtension to the stable Slicer branch (4.6)
Thanks

**Comment by fedorov** [comment]
Your extension repository does not have a license file. Can you please add?

**Comment by acsenrafilho** [comment]
Hi @fedorov 

I've added the license file into the repository and also did a minor edit in the README.md file.
Thanks

**Comment by jcfr** [comment]
@fedorov If you don't have any other comment, are  you ok for integrating ?

**Comment by jcfr** [comment]
I will integrate this Pr and the following one

**Pull request merged**
