### PR TITLE
T2mapping module addition

### PR DESCRIPTION
**Pull request by gattia**
I've created a Python module that creates T2 relaxation maps from multi-echo MRI data. The module has simple inputs that can be used to tweak the output(s).

### CODE REVIEW

**Comment by pieper** [comment]
Looks good to me - thanks for the contribution! 👍 

Nitpick: could remove .DS_Store and .pyc files from repository.

**Comment by gattia** [comment]
Thanks for the quick feedback. I've removed .DS_Store from throughout and the one .pyc file.

**Comment by cpinter** [comment]
Nice, thanks!

The code looks good to me.

About the removal of DS_Store files, there's one more of those left: https://github.com/gattia/Slicer-T2mapping/blob/master/T2mapping/Resources/.DS_Store

**Comment by lassoan** [comment]
Thanks a lot for your contribution!

A few suggestions that would make your module easier to discover and use:
- Rename T2mapping_documentation.md to README.md (or add a README.md file that gives a short summary of the module and has a link to T2mapping_documentation.md) so that when someone opens your repository webpage can see a summary of your module.
- Add 1-2 screenshots to your documentation (you need that for the extension description anyway)
- Can you add a link to a sample data set that people can use to try your module? (if somebody has trouble using your module it is always very useful to have a data set that is known to work well)
- Update extension information in CMakeLists.txt (EXTENSION_HOMEPAGE, EXTENSION_ICONURL, EXTENSION_SCREENSHOTURLS)

**Comment by gattia** [comment]
Thanks for all the quick feedback.  I believe I've now removed all of the .DS_store files and have included a .gitignore to prevent it being uploaded in the future - I think this is the best approach, let me know if there is another suggestion. 

I've also: 
1) changed the name of the documentation file to README.md and have updated it with screenshots, and an explanation about sample data. 
2) added screenshots - referenced in README
3) added sample data - referenced in README
4) updated the CMakeLists.txt 

Let me know if there is anything else.

**Comment by pieper** [comment]
LGTM

**Comment by lassoan** [comment]
Merged, it should show up in the extension manager tomorrow. Thank you for your contribution.

**Pull request merged**
