### PR TITLE
remove mpReview

### PR DESCRIPTION
**Pull request by fedorov**

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for taking care of this.

Could you add an entry to https://github.com/Slicer/ExtensionsIndex/blob/master/ARCHIVE/README.md ?

**Comment by jcfr** [comment]
Based on the check, the following error is reported:

```
mpReview extension is not found. It is required by extension: SliceTracker.
```

Since following https://github.com/Slicer/ExtensionsIndex/commit/d5b53aa3ff3d71c2c12a39a692a0fde7ed2a917f, `SliceTracker` was updated to include a dependency on `SegmentEditorExtraEffects`, may it could be as simple as updating `SliceTracker` to remove dependency on the legacy editor and relying only on the segment editor ?

**Comment by fedorov** [comment]
Unfortunately, SliceTracker is relying on some other components in mpReview, and will need to be removed as well.

**Comment by fedorov** [comment]
@tokjun FYI - I don't know if you are relying on SliceTracker in the nightly build, but it will not be available anymore.

**Pull request merged**
