### PR TITLE
BreastImplantAnalyzer submission

### PR DESCRIPTION
**Pull request by lancelevine**
# TODO list for submitting a new extension

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click "Manage topics" on your repository's main page, on the left, near the top (just below the repository description). To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [ ] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/master/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work.
Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.

[If you have any questions or comments then please describe them here.]
I added the ImplantSizer.s4ext. Any other commits are from a previous extension I submitted and I do not want to modify them now.

### CODE REVIEW

**Comment by lassoan** [comment]
Thank you for your contribution, it will be great to have this feature available for Slicer!

There are just a few things to clarify and tune before we add this extension.
- What is the current and expected scope of the application? As I see, it is currently used for measuring volumes of breast implants. If you don't plan to change this (don't plan to add tools for a wide range of other implants) then it would be better to reflect it in the name. If you think you may consider adding (or accept other contributors to add) other quantitative analysis features, not just implant size measurement (for example, detection of texture changes, ruptures, other anomalies in the implant or surrounding structures) then it would make sense to reflect it in the name, too. Something like **BreastImplantAnalysis** could be a more specific and more future-proof name.
- Can you share an example data set of an MRI that the module can be tested with? The simples if you can find something in a public data repository, but an anonymized data set would work, too. It is important because without that Slicer developers and new users will have difficulty testing the extension. For example, I could not test the module because of this.
- The pull request contains s4ext file of drrgenerator extension, too. I guess this was not intentional. If would be great if you could remove that, squash all the commits, and force-push the commit to update this pull request.

**Comment by lancelevine** [comment]
-I would like to add quantitative features in the future potentially, so I have changed the name to reflect this.
-I added an anonymized sample data set. I will provide info about the sample data in the readme.
-I hope I did this right. I apologize I am not very familiar with git.
-Done.

**Comment by lancelevine** [comment]
Hi I closed this pull request in order to remove past commits. Can you please verify that it is still open and valid? Thank you.

**Comment by lassoan** [comment]
Thanks a lot for the updates. I was able to test the module with the sample data set that you provided. It works very nicely. I've sent a pull request with some proposed changes, it would be great if you could merge it (let me know if you have any questions about what changes were made and why).

**Comment by lancelevine** [comment]
Changes look great, I merged them. Thanks!

**Comment by lancelevine** [comment]
Merged again, thank you!

**Comment by lassoan** [comment]
All looks good then. I'll merge this now, so tomorrow the extension should show up in the extension manager. I would suggest to add a note in the documentation (https://github.com/lancelevine/SlicerBreastImplantAnalyzer#tutorial section) that to try the module, "MRBreastImplant" sample data set can be used.

**Comment by lassoan** [comment]
If extension appears correctly in the extension manager tomorrow then please consider posting a message on https://discourse.slicer.org/c/support/ to let others know about this new extension.

**Pull request merged**
