### PR TITLE
Slicer RegQA extension

### PR DESCRIPTION
**Pull request by gsi-kanderle**
We have developed a registration quality assurance extension for Slicer, which uses different tools to asses registration quality.

### CODE REVIEW

**Comment by pieper** [comment]
Looks really interesting - thanks for contributing 👍 

A couple questions:

- there doesn't seem to be any user documentation about what the extension provides or how to use it.   The github wiki is only about installation.  Are there screenshots or other information available?  Right now the extension is pretty hard to understand for an outsider.

- there is no license file that I could find.  Under what license is the code available?  Maybe the Slicer license?

- are there any tests that will run on the factory so we will know the extension is working?

**Comment by lassoan** [comment]
This is awesome, thank you for your contribution! There are a couple of things that we would need to do to ensure users can find your extensions and can use it:

- Rename project to RegistrationQA and GitHub repository name to SlicerRegistrationQA (and make this rename consistent everywhere; for example on the wiki you still use the old dirqa name)
- Screenshots are missing! It is very important to make it easy for users to find out what your extension can do and one of the best ways to do it is to add a few screenshots. Add at least one screenshot for each module.
- Module documentation is missing! It is great that you provide these tools but users need to be able to use them. Add at least a screenshot, minimum 1-2 paragraphs describing what the module is for, what are the inputs, what are the outputs, and preferable add links to sample data that user can try your module with (before they try with their own data).
- Download URL must be specified for icons and screenshots. For example, for extension icon: https://raw.githubusercontent.com/gsi-biomotion/Slicer-RegQA/master/RegQA/Resources/Icons/RegQAIcon.png
- Add link to homepage (https://github.com/gsi-biomotion/Slicer-RegQA/wiki) from README.md file and as website URL (people may not discover that you have wiki pages)
- Status field: It should explain how stable and reliable the code is (in development, stable, etc). Current content of the status field would be better to move to description field.

I'll give more feedback once I've built and tested your extension.

**Comment by gsi-kanderle** [comment]
Got it. I'll add everything that is missing data and update the necessary fields.

**Comment by lassoan** [comment]
- I had build errors on Windows, with latest nightly version of Slicer. I've sent a pull request with the fixes: https://github.com/gsi-biomotion/Slicer-RegQA/pull/6
- Update help text in CLI module xml files.
- RegQA module should be listed in RegistrationQA category. Or you can put CLI modules in a Quality Assurance subcategory within Registration (Registration.Quality Assurance)
- I have no idea how to use RegQA module. Is it a frontend for all modules, so I should only use this module? What is the role of "Read registration node" module? I have many years of experience with Slicer and registration QA, so if I cannot figure this out then probably other users will struggle, too. Having some sample data sets that you've used these module with would help a lot, too.

**Comment by gsi-kanderle** [comment]
My idea was to use the build machine first and when everything was fixed upload the final documentation. I guess I should have done it the other way. The documentation is incoming and I'll try to make it clear how to use it.

The RegistrationQA is the main module all others are auxiliary.

Is there any chance I could get the windows build version? I don't have Slicer built on Windows but would need the module.

On 1 Mar 2018 4:29 p.m., Andras Lasso <notifications@github.com> wrote:

  *   I had build errors on Windows, with latest nightly version of Slicer. I've sent a pull request with the fixes: gsi-biomotion/Slicer-RegQA#6<https://github.com/gsi-biomotion/Slicer-RegQA/pull/6>
  *   Update help text in CLI module xml files.
  *   RegQA module should be listed in RegistrationQA category. Or you can put CLI modules in a Quality Assurance subcategory within Registration (Registration.Quality Assurance)
  *   I have no idea how to use RegQA module. Is it a frontend for all modules, so I should only use this module? What is the role of "Read registration node" module? I have many years of experience with Slicer and registration QA, so if I cannot figure this out then probably other users will struggle, too. Having some sample data sets that you've used these module with would help a lot, too.

**Comment by fedorov** [comment]
> Is there any chance I could get the windows build version? I don't have Slicer built on Windows but would need the module.

It is not uncommon to merge an extension before it is confirmed to build without errors on all platforms. Not all developers have access to all platforms to debug build issues. But you should provide minimum documentation before merging, and resolve other issues, as possible - such as adding a license file.

**Comment by lassoan** [comment]
> My idea was to use the build machine first and when everything was fixed upload the final documentation.

It makes sense. It is normal that documentation (and code) is constantly being changed and improved. There is just some minimal level that should be reached before publishing.

**Comment by gsi-kanderle** [comment]
I've written the first draft of documentation, which should make it clear on how to use the module [link](https://github.com/gsi-biomotion/SlicerRegistrationQA/blob/master/Introduction/RegistrationQA%20Introduction.pdf). Could I get read/write permission to kitware to upload test data there?
I've also implemented the rest of the comments, apart from testing files, on which I'll start working now.

**Comment by lassoan** [comment]
We are transitioning our data storage from Midas to Girder. I'm not sure if Kitware can create user accounts yet.

However, you should be able to upload some amount of sample data (up to 10-20MB should be no problem) to your Github repository. If sample data sets are larger then you can create a separate repository just for the data or you can upload it to https://zenodo.org/ or similar free scientific data hosting services.

**Comment by lassoan** [comment]
The documentation is really helpful, nice and detailed. I would recommend to upload it as a markdown (.md) file into the repository to allow search indexing, easy referencing, updates through web interface, change tracking, etc. You can still have a word or ppt file in the repository where you keep editable versions of the figures.

**Comment by pieper** [comment]
The documentation is really nice - this is a great contribution, thanks!  I agree that .md would be more useful and maintainable (deep linkable, version controlled, etc).

You could put the sample data on github in a release for your repo and that would keep it all in one place.

**Comment by gsi-kanderle** [comment]
I've converted the documentation to an md [file](https://github.com/gsi-biomotion/SlicerRegistrationQA/blob/master/Documentation.md).

The sample data is rather large (300 MB) due to containing vector fields and github complains. I could try with github lfs.

**Comment by pieper** [comment]
Did you look at the github release option?  It may be easier than lfs.
 
https://help.github.com/articles/distributing-large-binaries/

**Comment by gsi-kanderle** [comment]
An excellent idea. I've migrated the sample data there and updated the documentation.

**Comment by lassoan** [comment]
LFS requires clients to set up LFS in git, which is an extra step that can be forgotten or go wrong. Github releases or other hosting solutions would be probably less error-prone.

**Comment by lassoan** [comment]
Downloading 300MB is a bit more than usual. It could  be nice to make available a downscaled or cropped version as well that is not more than a few 10MB.

**Comment by gsi-kanderle** [comment]
I've already downscaled it, but I guess I could also crop it. I'll see what I can do.

Should I include the data in tests as well? Are there any guidelines how the tests should be done?

On 8 Mar 2018 6:35 p.m., Andras Lasso <notifications@github.com> wrote:

Downloading 300MB is a bit more than usual. It could be nice to make available a downscaled or cropped version as well that is not more than a few 10MB.

**Comment by lassoan** [comment]
You can add a very simple smoke test (just to see if the module runs at all) like this: https://github.com/lassoan/SlicerElastix/blob/caa4d67d930361166fee3b93999c843f93f947a4/Elastix/Elastix.py#L619-L667

You can add more thorough tests, with data download, etc:
https://github.com/SlicerRt/SlicerRT/blob/master/DicomRtImportExport/Testing/Python/DicomRtImportTest.py

**Comment by gsi-kanderle** [comment]
Ok, I've added some basic tests. Could you tell me how to execute them?

**Comment by lassoan** [comment]
To run your tests, build RUN_TESTS target or run ctest in the build directory.

**Comment by lassoan** [comment]
Some of the changes that are needed to be able to build your extension on Windows with latest nightly version have not been integrated yet. I've sent a pull request with the necessary changes:
https://github.com/gsi-biomotion/SlicerRegistrationQA/pull/9

I haven't tested it on Linux or Mac.

**Comment by pieper** [comment]
I was able to build and run on mac if I stubbed out SlicerRT (didn't have a local build to test with).

**Comment by gsi-kanderle** [comment]
I am not able to build it on Linux with current changes. I get errors from plastimatch libraries. I must admit I don't know how to solve this. Here's my build attempt: [Build.log](https://github.com/Slicer/ExtensionsIndex/files/1933348/Build.log)
Any ideas how to solve this?

**Comment by lassoan** [comment]
It would be great if it was possible to build it on Linux as well, but I think it is not a blocking issue.

If you merge my pull request that fixes the build on Windows (https://github.com/gsi-biomotion/SlicerRegistrationQA/pull/9) then we can add it to the extension manager.

**Comment by gsi-kanderle** [comment]
Ok, I've merged your pull request.

**Comment by lassoan** [comment]
Sorry for the long delay, I've just merged this pull request. While there are always things to improve, make sure the extension builds on all platforms, etc., your extension is already a very valuable addition.

I hope we will be much faster with integrating any further updates to your extension. However, you may choose to set _master_ as scmrevision in the s4ext file, which would update your extension with the latest version in your master branch every night (without the need for any further pull requests).

**Comment by gsi-kanderle** [comment]
Thanks! Will my extension now be added to extension manager or do I have to do something else?

**Pull request merged**
