### PR TITLE
ENH: Add CUDAProbe extension [master]

### PR DESCRIPTION
**Pull request by gregsharp**
Description:
This extension queries your computer for its CUDA capabilities.  It also
serves as an example of how to use CUDA in your Slicer Extension.

Contributors:
Gregory Sharp (Massachusetts General Hospital)

### CODE REVIEW

**Comment by jcfr** [comment]
Following our discussion, next step would be to:
* [ ] document how to install cuda on the different build machine. See https://www.slicer.org/wiki/Documentation/Nightly/Developers/Factory
* [ ] update docker image `qt5-centos7` used to build linux package. See https://github.com/Slicer/SlicerBuildEnvironment

**Comment by gregsharp** [comment]
Done and done!

**Comment by lassoan** [comment]
@jcfr @gregsharp What is the status of this? We should either finalize this or if this is not relevant anymore then close the pull request.

**Comment by lassoan** [comment]
@jcfr @gregsharp What is the status of this? We should either finalize this or if this is not relevant anymore then close the pull request.

**Comment by lassoan** [comment]
Closing due to no response. Feel free to reopen if the extension is ready for submission.

**Pull request closed without merging**
