### PR TITLE
SlicerSegReview - new extension

### PR DESCRIPTION
**Pull request by zapaishchykova**
# New extension

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Any known related patents must be mentioned in the extension description.
- [x] LICENSE.txt is present in the repository root. MIT  (https://choosealicense.com/licenses/mit/) or Apache (https://choosealicense.com/licenses/apache-2.0/) license is recommended. If source code license is more restrictive for users than MIT, BSD, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (main, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://raw.githubusercontent.com/user/repo/main/SomeIcon.png)
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [x] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/main/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [x] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)
- Hide unused features in the repository to reduce noise/irrelevant information:
  - [x] Click `Settings` and in repository settings uncheck `Wiki`, `Projects`, and `Discussions` (if they are currently not used)
  - [x] Click the settings icon next to `About` in the top-right corner of the repository main page and uncheck `Releases` and `Packages` (if they are currently not used)

### CODE REVIEW

**Review by pieper — APPROVED** [review]
I didn't try running it, but this looks fine to me.

**Comment by jamesobutler** [comment]
@zapaishchykova I see that you renamed the extension from `SlicerLikertDLrating` to `SlicerSegReview` in this PR. Do you mind updating the GitHub repository name to match?

@pieper Do you prefer "SlicerSegReview" over "SlicerLikertDLrating"? Is "SlicerSegReview" name specific enough?

Also as seen at https://slicer.cdash.org/build/3013323/configure, the .s4ext specifies `scmrevision master` when it should be `scmrevision main` to match https://github.com/zapaishchykova/Slicer-Likert-DL-rating/tree/main.

**Comment by zapaishchykova** [comment]
just updated it, thanks for the notice! I really like the SlicerSegReview, but I'll leave it up to you :)

**Comment by pieper** [comment]
I do like SlicerSegReview as well.  I would think more people would get the idea from that since the term Likert might not be widely known.  I suppose SlicerSegRater or SlicerSegmentationRater would be a bit more specific but I wouldn't be picky about that

**Comment by lassoan** [comment]
`SegmentationReview` is good if you plan to add more review features, such as allowing fixing up segmentations, adding comments, markups, etc.

If you never intend to add other feature than rating then the extension name should be a bit more specific, narrowed down. `SegmentationRater` could be appropriate.

Note that `Slicer` is not part of the extension's name. The `Slicer` prefix is only used in the repository name. (if all extension names would start with `Slicer...` then it would be harder to find extensions)

**Comment by zapaishchykova** [comment]
I like the "SegmentationReview" - we have already added a field for adding comments, and fixing segmentations is also possible by exporting the segmentation editor tools! I wonder what would be a potential use case for adding markups ... 

I was thinking to add also an option to compute the differences "before" and "after" reviewing by the clinician (eg volumetrics/dice/iou scores)

**Comment by pieper** [comment]
Those sound like great additions and it would be excellent if you kept developing and improving the extension.  We're happy to have any useful extension, but we're even more enthusiastic to see developers extend and maintain their work over time in response to user feedback.

**Comment by jamesobutler** [comment]
The filename of SlicerSegReview.s4ext at https://github.com/Slicer/ExtensionsIndex/tree/main can then be renamed to just "SegmentationReview.s4ext".

**Comment by zapaishchykova** [comment]
https://github.com/Slicer/ExtensionsIndex/pull/1936

**Comment by zapaishchykova** [comment]
quick question: I don't see the extension in the latest Slicer3D extensions; is there a way to check why the build might be failing?

**Comment by jcfr** [comment]
Current build result are available on the Quality Dashboard.

For convenience, [here](https://slicer.cdash.org/index.php?project=SlicerPreview&date=2023-05-08&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=SegReview) is a link including the filter by name and date.

**Comment by jcfr** [comment]
Fix of the  current error was suggested by @jamesobutler in https://github.com/Slicer/ExtensionsIndex/pull/1936#discussion_r1180773354

After the associated pull-request is integrated, issue should be addressed. 

In the meantime, I will continue the conversation at:
* https://github.com/Slicer/ExtensionsIndex/pull/1936

**Pull request merged**
