### PR TITLE
Propose ExtraMarkups extension.

### PR DESCRIPTION
**Pull request by chir-set**
# New extension

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Any known related patents must be mentioned in the extension description.
- [x] If source code license is more restrictive for users than BSD, MIT, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (main, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://raw.githubusercontent.com/user/repo/main/SomeIcon.png)
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [x] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/main/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [x] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)

### CODE REVIEW

**Comment by lassoan** [comment]
Thanks a lot for your contribution. Here are a few things, mainly to make it easier for users to find your extension and figure out how to use it:

- [ ] Need a more detailed description than "Set of custom markups." in the CMakeLists.txt (and generated s4ext file). Describe in a few sentences the overall goal and mention each new markup types.
- [ ] Show all the new markup types in the screenshots. You can add a single screenshot that shows all the new types.
- [ ] Add a short summary to the main README.md file. It can be the same as the few-sentence description in the CMakeLists.txt.
- [ ] Add a short sentence to describe the goal of each module (label, shape, stenosis), without that the user needs to click each link, scroll down, just to figure out if the module is relevant for him or not
- [ ] License file is missing
- [ ] Icon does not look bad but does not really suggest what the extension is about. Also, its background should be transparent.

---

I would recommend you to give the "Cardiac device simulator" module a try (in [SlicerHeart extension](https://github.com/SlicerHeart/SlicerHeart)). It allows automatic/manual placement of a stent (and other vascular and cardiac devices) and measure its fit qualitatively and quantitatively. The module has no documentation/tutorial, so it may be a bit difficult to figure it out, but if you have any questions then you can post it to the Slicer forum. A few screenshots:

image

image

image

image

**Comment by chir-set** [comment]
> Here are a few things, mainly to make it easier...

Yes, it's reasonable, I'll do that over the weekend.

I have a specific question about 'Stenosis measurement : 3D' module. It's here for convenience, as an application of the Shape::Tube markups. I think it's natural place would be in SlicerVMTK, as in [this](https://github.com/chir-set/SlicerExtension-VMTK/tree/WithStenosisMeasurement3D) branch. How do you contemplate this ?


> the "Cardiac device simulator" module

Nice suggestion, thanks. I'll look into it ASAP.

**Comment by lassoan** [comment]
> I have a specific question about 'Stenosis measurement : 3D' module. It's here for convenience, as an application of the Shape::Tube markups. I think it's natural place would be in SlicerVMTK, as in [this](https://github.com/chir-set/SlicerExtension-VMTK/tree/WithStenosisMeasurement3D) branch. How do you contemplate this ?

I agree, it would make sense to have Stenosis measurement in VMTK. SlicerVMTK could have a "soft dependency" on ExtraMarkups extension (it would not need to automatically install when SlicerVMTK is installed, but only when the user opens the Stenosis measurement module).

**Comment by chir-set** [comment]
Hi @lassoan,

I updated both the repository and this PR, I think the checklist should be complete.



> it would make sense to have Stenosis measurement in VMTK

And I just saw your last reply. StenosisMeasurement3D is still in ExtraMarkups. It is quite easy to move it to SlicerVMTK. Please allow one more day for moving it there.

Thank you for your interest in this work.

**Comment by chir-set** [comment]
> "soft dependency"

Yes of course, I'll make the necessary changes.

**Comment by chir-set** [comment]
@lassoan,

I have removed 'StenosisMeasurement3D' module from this extension, and will propose it in SlicerVMTK when this PR gets merged. So now, this extension provides Label and Shape extra markups. All the changes you pointed above have been completed. Thank you.

**Comment by lassoan** [comment]
The extension fails to build on Windows and macOS.

https://github.com/chir-set/SlicerExtraMarkups/pull/2 fixes some of the build errors, but there are some remaining problems that need Slicer core developments (create a wrapper functions or class around rapidjson). I'll try to get to those within a few days.

**Comment by lassoan** [comment]
https://github.com/chir-set/SlicerExtraMarkups/pull/3 fixes the build errors. If that is integrated then this pull request can be merged.

**Comment by chir-set** [comment]
> [chir-set/SlicerExtraMarkups#3](https://github.com/chir-set/SlicerExtraMarkups/pull/3) fixes the build errors. If that is integrated then this pull request can be merged.

@lassoan 
Your patch is merged in SlicerExtraMarkups. I built, checked and found no problems on Linux.

I did not see how to precise you are the author of the patch in git's fields, after fixing a file conflict on github's web interface. I added that precision in the commit's comment.

**Comment by lassoan** [comment]
Merged! Thanks a lot for your contribution. Please check the dashboard tomorrow and report back if there are any errors.

**Comment by chir-set** [comment]
> Merged! Thanks a lot for your contribution. Please check the dashboard tomorrow and report back if there are any errors.

Thanks for the merge.

I am seeing a crash with 'Sphere', 'Ring' and 'Disk' shapes, with 'Stack smashing detected
' error in console.

I usually build everything with clang (14.0.6 now) on Arch Linux, and everything works fine. I rebuilt Slicer and ExtraMarkups with gcc (12.2.0) and could reproduce the crash.

lldb gives this output :

```
* thread #1, name = 'SlicerApp-real', stop reason = signal SIGABRT
  * frame #0: 0x00007ffff5aa164c libc.so.6`___lldb_unnamed_symbol3503 + 268
    frame #1: 0x00007ffff5a51958 libc.so.6`raise + 24
    frame #2: 0x00007ffff5a3b53d libc.so.6`abort + 215
    frame #3: 0x00007ffff5a957ee libc.so.6`___lldb_unnamed_symbol3401 + 686
    frame #4: 0x00007ffff5b309ba libc.so.6`__fortify_fail + 42
    frame #5: 0x00007ffff5b30986 libc.so.6`__stack_chk_fail + 22
    frame #6: 0x00007ffedd81cf44 libvtkSlicerShapeModuleVTKWidgets.so`vtkSlicerShapeRepresentation2D::UpdateSphereFromMRML(vtkMRMLNode*, unsigned long, void*) + 5588
    frame #7: 0x00007ffedd82008d libvtkSlicerShapeModuleVTKWidgets.so`vtkSlicerShapeRepresentation2D::UpdateFromMRML(vtkMRMLNode*, unsigned long, void*) + 1085
    frame #8: 0x00007ffeee80cf98 libvtkSlicerMarkupsModuleMRMLDisplayableManager.so`vtkMRMLMarkupsDisplayableManager::ProcessMRMLNodesEvents(vtkObject*, unsigned long, void*) + 200
    frame #9: 0x00007fffe1e2890e libMRMLLogic.so`vtkMRMLAbstractLogic::MRMLNodesCallback(vtkObject*, unsigned long, void*, void*) + 318
    frame #10: 0x00007fffb17511d9 libvtkCommon-9.1.so.1`vtkCallbackCommand::Execute(vtkObject*, unsigned long, void*) + 25
    frame #11: 0x00007fffe11c7dda libMRMLCore.so`vtkEventBroker::InvokeObservation(vtkObservation*, unsigned long, void*) + 506
    frame #12: 0x00007fffe11cb7b1 libMRMLCore.so`vtkEventBroker::ProcessEvent(vtkObservation*, vtkObject*, unsigned long, void*) + 401
    frame #13: 0x00007fffb17511d9 libvtkCommon-9.1.so.1`vtkCallbackCommand::Execute(vtkObject*, unsigned long, void*) + 25
    frame #14: 0x00007fffb18504ba libvtkCommon-9.1.so.1`___lldb_unnamed_symbol57757 + 1786
    frame #15: 0x00007ffef14a9320 libvtkSlicerMarkupsModuleMRML.so`vtkMRMLMarkupsNode::AddControlPoint(vtkMRMLMarkupsNode::ControlPoint*, bool) + 240
    ...

```
    
And valgrind : 

```
...
==262532== Process terminating with default action of signal 6 (SIGABRT): dumping core
==262532==    at 0x1C5E564C: __pthread_kill_implementation (pthread_kill.c:44)
==262532==    by 0x1C595957: raise (raise.c:26)
==262532==    by 0x1C57F53C: abort (abort.c:79)
==262532==    by 0x1C5D97ED: __libc_message (libc_fatal.c:155)
==262532==    by 0x1C6749B9: __fortify_fail (fortify_fail.c:26)
==262532==    by 0x1C674985: __stack_chk_fail (stack_chk_fail.c:24)
==262532==    by 0x89860CA9: vtkSlicerShapeRepresentation2D::UpdateSphereFromMRML(vtkMRMLNode*, unsigned long, void*) (vtkSlicerShapeRepresentation2D.cxx:766)
==262532==    by 0x88CB3346: vtkMRMLMarkupsDisplayableManager::ProcessMRMLNodesEvents(vtkObject*, unsigned long, void*) (vtkMRMLMarkupsDisplayableManager.cxx:265)
==262532==    by 0x10CA54F6: MRMLNodesCallback (vtkMRMLAbstractLogic.cxx:212)
==262532==    by 0x10CA54F6: vtkMRMLAbstractLogic::MRMLNodesCallback(vtkObject*, unsigned long, void*, void*) (vtkMRMLAbstractLogic.cxx:182)
==262532==    by 0x1BC529E8: vtkCallbackCommand::Execute(vtkObject*, unsigned long, void*) (vtkCallbackCommand.cxx:41)
==262532==    by 0x10F5A5B8: vtkEventBroker::InvokeObservation(vtkObservation*, unsigned long, void*) (vtkEventBroker.cxx:841)
==262532==    by 0x10F5DB50: vtkEventBroker::ProcessEvent(vtkObservation*, vtkObject*, unsigned long, void*) (vtkEventBroker.cxx:693)
==262532== 
==262532== HEAP SUMMARY:
==262532==     in use at exit: 146,753,558 bytes in 675,291 blocks
==262532==   total heap usage: 3,252,582 allocs, 2,577,291 frees, 763,362,434 bytes allocated
==262532== 
==262532== 0 bytes in 1 blocks are possibly lost in loss record 6 of 189,764
==262532==    at 0x4843798: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==262532==    by 0x3391338E: ??? (in /usr/lib/dri/radeonsi_dri.so)
==262532==    by 0x33874ADE: ??? (in /usr/lib/dri/radeonsi_dri.so)
==262532==    by 0x33828A19: ??? (in /usr/lib/dri/radeonsi_dri.so)
==262532==    by 0x33774EC7: ??? (in /usr/lib/dri/radeonsi_dri.so)
==262532==    by 0x337752AC: ??? (in /usr/lib/dri/radeonsi_dri.so)
==262532==    by 0x337F95CF: ??? (in /usr/lib/dri/radeonsi_dri.so)
==262532==    by 0x602E6E8: ??? (in /usr/lib/libQt5Gui.so.5.15.8)
==262532==    by 0x5FA21C8: ??? (in /usr/lib/libQt5Gui.so.5.15.8)
==262532==    by 0x5F7FB9E: QOpenGLShaderProgram::link() (in /usr/lib/libQt5Gui.so.5.15.8)
==262532==    by 0x5F953ED: ??? (in /usr/lib/libQt5Gui.so.5.15.8)
==262532==    by 0x5F96AB6: QOpenGLTextureBlitter::create() (in /usr/lib/libQt5Gui.so.5.15.8)
==262532== 
...

```
These don't point to where the real problem is. I am investigating and it will certainly be a lengthy process.

So I think it may be better to suspend this Extension temporarily.

I'll let you know when it's fixed, of course.

Regards.

**Comment by chir-set** [comment]
The problem described above is fixed in this [commit](https://github.com/chir-set/SlicerExtraMarkups/commit/0793277ffeee22b9a43a0f004911f92bb9e7f45a). No problems were found after building with gcc and clang.

**Comment by lassoan** [comment]
Great! It seems that everything is coming together.

**Pull request merged**
