### PR TITLE
add StereoSlicer.s4ext

### PR DESCRIPTION
**Pull request by stawiskm**
# New extension

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Any known related patents must be mentioned in the extension description.
- [x] LICENSE.txt is present in the repository root. MIT  (https://choosealicense.com/licenses/mit/) or Apache (https://choosealicense.com/licenses/apache-2.0/) license is recommended. If source code license is more restrictive for users than MIT, BSD, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (main, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://raw.githubusercontent.com/user/repo/main/SomeIcon.png)
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [x] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/main/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [x] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)
- Hide unused features in the repository to reduce noise/irrelevant information:
  - [x] Click `Settings` and in repository settings uncheck `Wiki`, `Projects`, and `Discussions` (if they are currently not used)
  - [x] Click the settings icon next to `About` in the top-right corner of the repository main page and uncheck `Releases` and `Packages` (if they are currently not used)

### CODE REVIEW

**Comment by pieper** [comment]
From a quick look this seems nice and useful.

I did get a little thrown off by the name, since I thought it was something to do with stereo cameras or similar, so maybe SlicerStereotactic would be clearer, especially is you plan to support more methods in the future.

@lassoan may have more comments on how this fits with other IGT efforts.

**Comment by lassoan** [comment]
Could the new module be added to the existing [Stereotaxis extension](https://github.com/JBeninca/SlicerStereotaxia#readme)? 

@stawiskm could you contact @jbeninca either via discourse.slicer.org or in the extension's repository to see if you could work together?

**Comment by JBeninca** [comment]
Yes, please

**Comment by d-vogel** [comment]
@JBeninca I sent you an email so we can discuss the details of the collaboration.

**Comment by lassoan** [comment]
@d-vogel @JBeninca It would be great if you could submit a project for the upcoming Slicer Project Week - https://projectweek.na-mic.org/ You can participate remotely. You can submit a project description before the event, present it in 2 minutes on the first day, work on it during the week (between yourself, or also ask for help from experts, we could also organize a session during the week to bring together all people who are interested in doing stereotactic procedures in Slicer, etc.) and present the results on the last day in minutes.

**Comment by d-vogel** [comment]
Update: we are still waiting for an answer to the email I sent to @JBeninca on the 24th of may.
In this email we offered the following merge plan (**of course we are very open for discussion**):

- the name stereotaxia stays the same
- @JBeninca transfers the repo to our institute org (history of commits is conserved)
- we add our code there as a single commit (for the first release the modules from both teams live alongside, but then the first priority is to merge features in a sensible way)

The rationale here is that we are confident we can dedicate significant amount of resources into the extension in the coming 2-3 years in our current state-founded project and as an institute for medical informatics, have developers to affect to that project.

@lassoan Thanks for the suggestion, we first need the conditions of the collaboration to be clear before we can engage in the project week.

**Comment by stawiskm** [comment]
@pieper @lassoan Unfortunately, we seem to be facing a roadblock as we haven't received any response from @JBeninca regarding the merging process. I suggest we proceed with slicer stereotactic independently and publish it ourselves. Is this feasible? I would appreciate your input on this matter. This way, we can ensure progress and maintain momentum without relying on third person's involvement.

**Comment by lassoan** [comment]
I wrote to @JBeninca - see https://github.com/JBeninca/SlicerStereotaxia/issues/3

Let's give him some time to respond. If we don't hear from him then we may fork and take over maintenance&support of this repository.

**Comment by stawiskm** [comment]
Hi Everyone @pieper @lassoan,
Here is a quick update, we received a short answer from @JBeninca last Monday. However, we are currently a little disappointed because this leaves no room for planning or further development. He agrees to merge the projects, but still has some objections because he wants to work with other partners on a "similar" software for neuronavigation but not stereotaxy. It seems that he has not yet decided on any of the [options](https://github.com/JBeninca/SlicerStereotaxia/issues/3) described by you, @lassoan.

**Comment by JBeninca** [comment]
Yes. I want to aport in a work toguether. Sorry for delays but i am a
neurosurgeon full with a lot of work, with little time for taking the
developmet.
Anyway i ve made a little group of people that will follow the proyect.
They are ready for work
You can make contact at ***@***.***

There we can make a way of reviewing the code as you want (it was written
about 5 years ago ).

I ve read superficially yours and watched the.video. they are similar in
fact, butni dont know if we use the same approach and libraries.

Sorry again for delay.
 Yours.

Dr. Jorge Beninca.



Years ago)

**Comment by lassoan** [comment]
@JBeninca it is completely understandable that you have limited time to work on this and any contribution is highly appreciated. To avoid overwhelming you with requests but still allow us to proceed with integrating fixes or new features, could you grant write access to the few Slicer developers (@jcfr, @pieper, @lassoan) to the https://github.com/JBeninca/SlicerStereotaxia extension? (if you give use admin access then we can also take care of some of the questions/bug reports)

**Comment by stawiskm** [comment]
Hello everyone, Hi @JBeninca , We understand that your time is limited, and we apologize for any inconvenience caused. However, we would like to proceed with our project. Regarding your statement, I also briefly reviewed your code and noticed some differences in our approaches, including the libraries we use, but they are still compararble. Unfortunately, the email address you provided is not readable, so we are unsure if this was intentional. Nonetheless, we are comfortable with the last approach proposed by @lassoan  and would like to continue our project in that manner. Thank you for your understanding, and we are excited to collaborate further.

**Comment by lassoan** [comment]
@stawiskm we have been granted write access to the existing https://github.com/JBeninca/SlicerStereotaxia extension, so if you submit a pull request that adds your module to this extension then we can review and merge it - no need to wait for @JBeninca.

**Comment by JBeninca** [comment]
Hello.
I hope you can see the code.
If you ask me especific questions,  i can answer you.
I think the 2 mayor tips are:
1 - the way i get the x,y,z values from  the middle arm of fuducialls from
one ct scan image, and
2 -  then use this 3 values to registrate the whole volume.

**Comment by JBeninca** [comment]
hello.
there is another repository:
[https://github.com/JBeninca/StereotaxiaPath]
it works in the same way, but is simplier in the graphic manageement. Just a path drawed in the ct volume



I thought that the integration would be through the routines.
I haven't read yours yet.
i propose, not a simple "merge" but study the script and make them work together.

mi approach was: to calculate Z I have read Russell Brown's equations (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8301297/, https://www.researchgate.net/publication/283079129_The_Origin_and_History_of_the_N-Localizer_for_Stereotactic_Neurosurgery)

and implemented them in python, (first in excel).

the  obtained 3 points (the midpoints of each N locator) were plotted in a CTScan image.

Those points were fitted by mean squares to the equivalents of a "Micromar" framework model centered at zero. That transform is the one I use to register the volume. So each point marked in the Target, for example, is defined directly.
position, angles and path trajectory are obtained in the same way and plotted by the 3dslicer routines.

I hope this overview is useful.

yours. Jorge Beninca

**Comment by JBeninca** [comment]
I can comment in English each routine of the script if that is useful

**Pull request closed without merging**
