### PR TITLE
Add CollageRadiomics extension.

### PR DESCRIPTION
**Pull request by nathanhillyer**
- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [ ] Repository name is Slicer+ExtensionName. **We are keeping a single repo, and requesting an exception to this guideline**
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click "Manage topics" on your repository's main page, on the left, near the top (just below the repository description). To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [x] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/master/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [x] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)

### CODE REVIEW

**Comment by nathanhillyer** [comment]
> Install time may even exceed maximum module startup time, preventing loading of your module the first time you start the application after the extension installation.

Do you have any suggestions for working around this problem? I'm now realizing our pip packages are cached on our development boxes, hence we never ran into this issue. But I'm seeing this problem on an installation on a fresh computer. Are there any better patterns to follow or are we the first extension that uses python dependencies like this?

Thanks--

**Comment by fedorov** [comment]
In SlicerRadiomics we [install pyradiomics and its prerequisites](https://github.com/Radiomics/SlicerRadiomics/blob/master/SuperBuild/External_python-pyradiomics.cmake#L63-L70) as part of the superbuild process. Isn't this something that can be done here?

**Comment by nathanhillyer** [comment]
@fedorov Great idea. Not familiar with the superbuild process but we'll do some research. Do you have any suggestions for a starting point?

**Comment by fedorov** [comment]
For me the starting point is usually a piece of code that does something similar to what I want to do, and in this case it seems like SlicerRadiomics might be that piece. You can then follow up on the [Slicer Discourse](https://discourse.slicer.org) if you have specific questions. @lassoan may give a better pointers.

**Comment by nathanhillyer** [comment]
Thanks. I've started on the work here, following the pyradiomics patterns:
https://github.com/radxtools/collageradiomics/commit/f17f291ec99c66d86ab80b2332da90bc6ffeaa1a

Does anyone know a good way to test these super builds locally?

**Comment by lassoan** [comment]
If you already have wheels on PyPI then it is easier to pip install the package, as it is done here: https://github.com/ToothAndClaw/SlicerAuto3dgm/blob/13cd3d98607c4ecddb45c7bdc02cb76569dd89bc/Auto3dgm/Auto3dgm.py#L72-L77

Note that this is in the module widget's constructor, so it is not executed until the user switches to the module and a popup is displayed so the users knows what is going to happen and it may take time.

**Comment by nathanhillyer** [comment]
That looks good, as we do have wheels on PyPI. As always, we very much appreciate the help.

**Comment by fedorov** [comment]
@lassoan for my curiosity - what are the disadvantages to installing those via pip during superbuild, as we do in SlicerRadiomics?

**Comment by lassoan** [comment]
If you build a python package in the Slicer extension then it is one more thing that you need to maintain. If you already have your package in PyPI then you can get that from Slicer instead of building it again.

Another thing is that if the Python package depends on other packages and you want to bundle all those in your extension package then its size can become quite big.

I'm not sure what happens if a bundled Python package's version conflicts with another extension's requirements. There may be differences in how a package can be uninstalled and a different version reinstalled - @jcfr may know this.

The only advantage of bundling required Python packages with the extension is that it is more self-contained: after you downloaded and installed the extension you don't need internet connection for the first use of the extension.

**Comment by lassoan** [comment]
@nathanhillyer Have you finished with all the updates that were requested and you have planned to do?

**Comment by nathanhillyer** [comment]
@lassoan We had some things come up and have been working on integrating with other software projects the past couple weeks that were scheduled as higher priority, and we'll circle back to this one soon. Will ping when we get back to this!

**Comment by fedorov** [comment]
Someone brought it to my attention that CoLIAge is covered by this patent: https://patents.google.com/patent/US9483822B2/en.

How is this related to the implementation in this extension? I did not find any mention of the patent on the front page of https://github.com/radxtools/collageradiomics.

I believe Slicer license is very strict that any code contributed to the application should not be subject to any patent protection. I do not know if/how this applies to extensions. FWIF I did not see "patent" mentioned in https://www.slicer.org/wiki/Documentation/Nightly/Developers/FAQ/Extensions.

**Comment by pieper** [comment]
Thanks for raising this @fedorov, I was not aware of it either.

I agree it is very important to disclose any patents that may influence a user's ability to make use of the code.  And to the extent possible it is important to be explicit about terms of such use.  For example some people state that patents can be used royalty-free for research purposes but that commercial users would be expected to pay for a license.  It's only fair to make these kinds of conditions clear up front so that people can decide whether to make use of this extension or not in their work.

If this code were being contributed to the Slicer core, then the [patent terms would come into effect](https://github.com/Slicer/Slicer/blob/master/License.txt#L62-L71).  But since this is an extension and is made available under the BSD license the patent terms are not proscribed and should be explicitly called out.

I'll note that by making the extension available the authors are in effect encouraging people to use the patented material without claiming your IP.  You may wish to consult your lawyers about the impact on future ability to assert any control over that IP.

**Comment by nathanhillyer** [comment]
Thanks @pieper. The extension is being developed under the direction of the patent writers and I'll bring up these concerns.

**Comment by lassoan** [comment]
Agree, we don't impose any particular license on extensions (only on contributions to Slicer core).

However, we have been asking developers of all extension that used restrictive license (for example, GPL) to mention it explicitly in their extension description. We haven't asked developers about known related patents, but of course that should be disclosed in the extension description, too. I've added it to the [extension checklist](https://github.com/Slicer/ExtensionsIndex/blob/master/.github/PULL_REQUEST_TEMPLATE.md) now to make sure we don't forget about this.

**Comment by lassoan** [comment]
I think allowing businesses to distribute their offerings as Slicer extensions is good for everyone, as it allows fair comparison and competition of various tools. The only thing we need to pay attention to is not to mislead users to think that a certain tool is free (in every sense), while it is actually not. If more restrictively licensed/patented extensions show up then we may add a filtering option in the extension manager that makes is easier to users to find free solutions.

**Comment by fedorov** [comment]
@lassoan I agree. Also note that not disclosing the patent, while sharing code under a non-restrictive license may be a deterrent for the users who know about the patent, but do not know how to reconcile it with the license. When I learned about this today, I actually could not make sense of how the BSD license and patent co-exist. @pieper explanation helped understand that part somewhat! :-)

**Comment by lassoan** [comment]
I've been reviewing open pull request and noticed that this extension is stuck in review phase. Is there still an intention to make the CollageRadiomics available as a Slicer extension?

**Comment by lassoan** [comment]
I've been reviewing open pull request and noticed that this extension is stuck in review phase. Is there still an intention to make the CollageRadiomics available as a Slicer extension?

**Comment by lassoan** [comment]
Closing due to no response. Feel free to reopen if ready to submit the extension.

**Pull request closed without merging**
