### PR TITLE
ENH: Add Slicer-TrackerStabilizer extension

### PR DESCRIPTION
**Pull request by lchauvin**
Description:
Smooth Linear Transforms

Contributors:
Laurent Chauvin (BWH), Jayender Jagadeesan (BWH), Andras Lasso (Queen's
University)

### CODE REVIEW

**Comment by fedorov** [comment]
Can you put valid URLs for the documentation page and screenshots?

**Comment by lchauvin** [comment]
Oh yes, sorry, I will redirect the page to the previous version for now.

I will try to make a new page soon.

-Laurent

On Fri, May 15, 2015 at 4:29 PM, Andrey Fedorov <notifications@github.com>
wrote:

> Can you put valid URLs for the documentation page and screenshots?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Slicer/ExtensionsIndex/pull/959#issuecomment-102519338>
> .
>
> The information in this e-mail is intended only for the person to whom it
> is
> addressed. If you believe this e-mail was sent to you in error and the
> e-mail
> contains patient information, please contact the Partners Compliance
> HelpLine at
> http://www.partners.org/complianceline . If the e-mail was sent to you in
> error
> but does not contain patient information, please contact the sender and
> properly
> dispose of the e-mail.
>



-- 
Laurent Chauvin, MS
Surgical Navigation and Robotics Laboratory, Radiology Department
Brigham And Women's Hospital, Harvard Medical School
http://wiki.ncigt.org/index.php/User:Lchauvin

**Comment by lchauvin** [comment]
I added proper link to the homepage and screenshots.

**Comment by fedorov** [comment]
Thanks!

**Pull request merged**
