### PR TITLE
Add ColocZStats extension

### PR DESCRIPTION
**Pull request by ChenXiang96**
# New extension

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [ ] Any known related patents must be mentioned in the extension description.
- [x] If source code license is more restrictive for users than BSD, MIT, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (main, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://raw.githubusercontent.com/user/repo/main/SomeIcon.png)
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [ ] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/main/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [x] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)

### CODE REVIEW

**Comment by ChenXiang96** [comment]
>

**Comment by ChenXiang96** [comment]
> Thank you for your submission. I've tested the extension and it worked well. I particularly liked the colored 3D visualization. Documentation was also very nice and clear.
> 
> I've only noticed one concerning issue. You have chosen a a restrictive license that prohibits commercial use. This is highly unusual in the Slicer community (and more broadly in the Python community). Restrictive license essentially prohibit collaborations, because very few people would want to invest time into learning to use or contribute to a software that he is not allowed to use for any project. For example, I would be able to help you during the project week to make your module 10-100x faster to compute colocalization, but I would not invest time into this if I'm not sure if later I can use it for some projects due to licensing limitations. We don't outright reject extensions that come with restrictive licenses (although right now I think we have any extensions with restrictive licenses) and for the reasons described I would suggest to reconsider your choice of license.
> 
> A few minor improvements, tweaks that could be nice to address:
> 
> * You can remove VisibleOn.png VisibleOff.png icons, they are not used (these icons are found in built-in Slicer resources)
> * Upload sample data in your github repository as a release asset (create a new release, using any tag, and then upload the sample data file as a release asset)
> * Consider moving "Compute colocalization" button into a separate row, as it is amoung various visualization options now, where it is hard to find it
> * Tweak the tutorial:
>   
>   * describe that the CELL.tif file will appear as grayscale image until it is selected as Volume in ColozZstats module
>   * add a note that computation may take several minutes (it took much longer than 1 minute on my computer)
> * Computation could be greatly simplified and made faster (fraction of a second instead of minutes) by getting the thresholded segments once, and then just use numpy indexing to compute intersection of segments and get volume. If you are not sure how to do it then you can work on it with Slicer experts during the upcoming [Slicer project week](https://projectweek.na-mic.org/PW37_2022_Virtual/), starting on Monday (register, create a project page, present it in one minute on Monday)

Thanks a lot for your affirmation and helpful advice! First of all, I’ll get back to you after consulting with my supervisor about the license issue, and I’ll follow your tips to address those few tweaks. Also, I really willing to learn how to make the computation faster during the coming project week.

**Comment by lassoan** [comment]
MIT license added. Other findings are mostly suggestions for improvement. Therefore, this extension is ready to be added to the Extensions Index.

**Comment by jamesobutler** [comment]
@ChenXiang96 @lassoan https://github.com/ChenXiang96/SlicerColoc-Z-Stats/branches does not have "5.0" branch resulting in the following configure error making this extension unavailable for the latest Slicer Stable. https://slicer.cdash.org/build/2734157/configure

**Comment by ChenXiang96** [comment]
Hello @jamesobutler,
   Thank you for your reminder, so what should I do now? 
   Is it OK to create a new branch called '5.0' under my 'SlicerColoc-Z-Stats' repository to fix the error?  
   I just created it: [branches 5.0](https://github.com/ChenXiang96/SlicerColoc-Z-Stats/tree/5.0)
   Another thing is that now I can search my extension in the Preview Release of slicer's 'extension manager', but it has no icon and screenshot. How can I solve this?
   Thank you so much!

**Comment by jamesobutler** [comment]
https://github.com/ChenXiang96/SlicerColoc-Z-Stats/tree/5.0 will resolve the issue for the extension showing up for the latest Slicer stable. The extension will build successfully tonight and will be available tomorrow.

For icons and screenshots, you need to specify the raw githubusercontent link as shown below. You will need to commit these changes to both your `master` and `5.0` branch for the images to show up correctly for both the Slicer stable and Slicer preview.

https://github.com/ChenXiang96/SlicerColoc-Z-Stats/blob/6f14b49c5ec9334d392275c2dabe458da981e01b/CMakeLists.txt#L11-L12
```diff
- set(EXTENSION_ICONURL "https://github.com/ChenXiang96/SlicerColoc-Z-Stats/blob/main/ColocZStats/Resources/Icons/ColocZStats.png")
- set(EXTENSION_SCREENSHOTURLS "https://github.com/ChenXiang96/SlicerColoc-Z-Stats/blob/main/Images/Screenshots.png")
+ set(EXTENSION_ICONURL "https://raw.githubusercontent.com/ChenXiang96/SlicerColoc-Z-Stats/main/ColocZStats.png")
+ set(EXTENSION_SCREENSHOTURLS "https://raw.githubusercontent.com/ChenXiang96/SlicerColoc-Z-Stats/main/Images/Screenshots.png")
```

**Comment by ChenXiang96** [comment]
Hello @jamesobutler,
 I have made corresponding changes according to your prompts.
 Thank you so much!

**Pull request merged**
