### PR TITLE
Add SlicerTractParcellation extension

### PR DESCRIPTION
**Pull request by zhangfanmark**
# New extension

- [x] Repository name is Slicer+ExtensionName (except if the repository that hosts the extension can be also used without Slicer)
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Any known related patents must be mentioned in the extension description.
- [x] LICENSE.txt is present in the repository root and the name of the license is mentioned in extension homepage. We suggest you use a permissive license that includes patent and contribution clauses. This will help protect developers and ensure the code remains freely available. MIT (https://choosealicense.com/licenses/mit/) or Apache (https://choosealicense.com/licenses/apache-2.0/) license is recommended. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses. If source code license is more restrictive for users than MIT, BSD, Apache, or 3D Slicer license then describe the reason for the license choice and include the name of the used license in the extension description.
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (main, release, ...) instead of a specific git hash to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://raw.githubusercontent.com/user/repo/main/SomeIcon.png)
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Content of submitted json file is consistent with the top-level CMakeLists.txt file in the repository (dependencies, etc. are the same)
- Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Publication: link to publication and/or to PubMed reference (if available)
- Hide unused github features (such as Wiki, Projects, and Discussions, Releases, Packages) in the repository to reduce noise/irrelevant information:
  - [x] Click `Settings` and in repository settings uncheck `Wiki`, `Projects`, and `Discussions` (if they are currently not used).
  - [x] Click the settings icon next to `About` in the top-right corner of the repository main page and uncheck `Releases` and `Packages` (if they are currently not used)
- The extension is safe:
  - [x] Does not include or download binaries from unreliable sources
  - [x] Does not send any information anywhere without user consent (explicit opt-in is required)

### CODE REVIEW

**Comment by pieper** [comment]
@zhangfanmark thanks for putting this together.  Please do go through the checklist in this template and perform the steps.  It may seem like a lot but they should be quick for either you or Kening to do.  Things like including some screenshots and descriptive text to form a tutorial will really help anyone who wants to use your tutorial.  Also adding the `3d-slicer-extension` will make it easier for people to find.  Plus it will show off your work!

**Comment by zhangfanmark** [comment]
Hi @pieper Kening is working on the checklist and he will do a pull request later. Thank you!!!

**Comment by pieper** [comment]
Thanks Fan 👍   If Kening has any questions at all, let us know.

**Comment by JoshuaKening** [comment]
@pieper We have accomplished the extension, https://github.com/SlicerDMRI/SlicerTractParcellation, here is the link. Please let me know if there are any imperfections. And do we need to create a new pull request to refresh the version?

**Comment by lassoan** [comment]
@pieper do you think we can accept this extension as Tier 1 (due to lack of documentation)

**Comment by pieper** [comment]
I guess I'd hold off until we hear more from @zhangfanmark or @JoshuaKening -- if there's continued development then yes it's good to have a working extension for user testing, but if the project isn't going forward and it's not quite usable now it might be better to have it in an archive in case someone is able to pick it up in the future.  @ljod do you know the status?

**Comment by zhangfanmark** [comment]
Hi @pieper sorry that this was suspended. Kening has just picked it up and updated the repo for the checklist. The changes have been merged into SlicerTractParcellation. Can you please take a look and see if it is okay now? Thank you!!! 

@ljod @JoshuaKening

**Comment by lassoan** [comment]
It has some documentation/tutorial now, so tier 3 should be appropriate.

**Pull request merged**
