### PR TITLE
ENH: Add Slicer-Wasp extension

### PR DESCRIPTION
**Pull request by Tomnl**
Description:
A module to perform a series of ITK watershed segmentation (without
seeds) and then let the user create a label map out of selected
components.  An isosurface model will also be generated.

Contributors:
Thomas Lawson (MRC Harwell, Oxfordshire)

### CODE REVIEW

**Comment by jcfr** [comment]
Hi, thanks for contributing. To ensure your extension will be presented optimally. Could you.check that the icon is squared (for example 128x128px). Thks

**Comment by Tomnl** [comment]
Hi,

I have updated the image referenced in the link. It is now 128x128px. See
http://www.slicer.org/slicerWiki/images/5/5b/Slicer-Wasp.png.

Let me know if I need to do anything else.

Kind regards,
Tom

**Comment by jcfr** [comment]
Looks good. 
Thanks for your contribution :+1:

**Comment by Tomnl** [comment]
Thanks for that. Should the extension appear in the extension manager now?

**Comment by jcfr** [comment]
Hi Thomas,

See
http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Developers/FAQ#How_often_extensions_are_uploaded_on_the_extensions_server_.3F

That said, based on the workload of the build machines the extension will
most likely show up later tomorrow.

Hth
Jc

On Wed, Jan 7, 2015 at 4:30 PM, Thomas Lawson <notifications@github.com>
wrote:

> Thanks for that. Should the extension appear in the extension manager now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Slicer/ExtensionsIndex/pull/870#issuecomment-69095534>
> .
>



-- 
+1 919 869 8849

**Comment by Tomnl** [comment]
Great. Thanks for all the help.

**Pull request merged**
