### PR TITLE
update SlicerPathology to v1.2.4

### PR DESCRIPTION
**Pull request by tdiprima**

### CODE REVIEW

**Comment by lassoan** [comment]
I would recommend to just set a branch name and then factory machines get the latest version from that branch each night. That way there is no need to keep sending pull requests (we don't have the capacity to test the changes anyway).

**Comment by tdiprima** [comment]
Ok, thanks.  Was not aware.  Btw, the [build page](http://slicer.cdash.org/index.php?project=Slicer4&date=2017-04-24) shows SlicerPathology built on Linux and Mac but not Windows.  Did it not build _yet_, or... how should I interpret that?
Thanks.

**Comment by fedorov** [comment]
@tdiprima I believe this might be happening because the Windows build of Slicer failed, and it is required to build extensions against it.

image


You did notice that SlicerPathology fails to build on Mac, right: http://slicer.cdash.org/viewBuildError.php?buildid=1011406

**Comment by lassoan** [comment]
An experimental change was tested on perklab.factory. The primary factory machine (overload.kitware) has built Slicer successfully.

Something else happened, though as OpenCV was available for Windows yesterday:
http://slicer.cdash.org/index.php?project=Slicer4&date=2017-04-23&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=OpenCV

But not today:
http://slicer.cdash.org/index.php?project=Slicer4&date=2017-04-24&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=OpenCV

It seems that there was something wrong with the https://github.com/emily-hammond/Multi-LevelRegistration repository that broke the extension build process:
http://slicer.cdash.org/viewConfigure.php?buildid=1011290

Slicer build is in progress on perklab.factory. Once it is completed, I can have a look at how to fix Multi-LevelRegistration build (at least that much so that it doesn't break other extensions).

**Comment by tdiprima** [comment]
@fedorov OK [that](http://slicer.cdash.org/buildSummary.php?buildid=1011276) explains it, then.  (And yes, I did see that the [Mac](http://slicer.cdash.org/buildSummary.php?buildid=1011406) build failed, and I will fix it.)

@lassoan Great!  Thank you.  (So basically, the Slicer Windows build failure wasn't my fault then right?  Ok good. :)  I'm 99.9996% sure that my build will succeed this time.)

**Comment by fedorov** [comment]
@lassoan thanks for the heads up - I will revert integration of https://github.com/emily-hammond/Multi-LevelRegistration. It doesn't even build on my local machine due to this:

```
#include ".\ReadWriteFunctions.hxx"
#include ".\PreprocessingFunctions.hxx"
#include ".\itkRegistrationFramework.h"
#include ".\itkInitializationFilter.h"
#include ".\itkManageTransformsFilter.h"
#include ".\itkValidationFilter.h"
```

**Comment by fedorov** [comment]
Hopefully this will also bring back SlicerOpenCV extension...

**Pull request merged**
