### PR TITLE
update-TOMAAT

### PR DESCRIPTION
**Pull request by faustomilletari**

### CODE REVIEW

**Comment by faustomilletari** [comment]
this now refers to an new commit of the extension which has a disclaimer attached to it.

**Comment by fedorov** [comment]
Note that you can, if you like, point your s4ext to the master of the repo.

**Comment by faustomilletari** [comment]
I didn't know :( I will do that if there is a next update. I don't want to bother you right before Christmas (apropos, happy holidays!) with yet another update pull request...

**Comment by fedorov** [comment]
Thank you Fausto! But it is not a big deal, there's no problem.

Happy Holidays to you as well!

**Pull request merged**
