### PR TITLE
update exStone extension

### PR DESCRIPTION
**Pull request by qimo601**
fix bug: QAxOjbect
update new s4ext file

### CODE REVIEW

**Comment by jcfr** [comment]
@qimo601  To more effectively review the change, would you mind providing a compare link similar to what was done here: https://github.com/Slicer/ExtensionsIndex/pull/1379

Thanks
Jc

**Comment by qimo601** [comment]
Thanks JC

I have fixed these build errors in CDash and deleted the QAxObject class.
fatal error: 'ActiveQt/qaxobject.h' file not found

So I need update the new scmversion on exStone.s4ext.


Compare link: https://github.com/Slicer/ExtensionsIndex/compare/master...qimo601:add-exStone

**Comment by lassoan** [comment]
I fully agree, Slicer core and extensions built by official factory computers should be in English. Private factories could be set up for other languages.

**Comment by pieper** [comment]
Although we don't insist on it for extensions the way we do for core code,
it is best to follow the Style Guide:

https://www.slicer.org/wiki/Documentation/Nightly/Developers/Style_Guide

**Comment by fedorov** [comment]
@pieper note that the guidelines do not explicitly mention the use of English in the UI

https://www.slicer.org/wiki/Documentation/Nightly/Developers/Style_Guide#Text

**Comment by pieper** [comment]
Good point - I updated it to point to the section I was thinking of about
Naming:


https://www.slicer.org/wiki/Documentation/Nightly/Developers/Style_Guide#Naming


https://www.slicer.org/w/index.php?title=Documentation%2FNightly%2FDevelopers%2FStyle_Guide%2FUI&type=revision&diff=49330&oldid=32935

**Comment by fedorov** [comment]
@qimo601 do you plan to update your extension to address the concerns, or should we close this pull request?

**Pull request closed without merging**
