### PR TITLE
ENH: addition of AstmPhantomTest to the extensions index

### PR DESCRIPTION
**Pull request by atracsys-sbt**
# TODO list for submitting a new extension

[To make sure users can find your extension, understand what it is intended for and how to use it, please complete the checklist below. You do not need to complete all the item by the time you submit the pull request, but most likely the changes will only be merged if all the tasks are done. See more information about the submission process here: https://slicer.readthedocs.io/en/latest/developer_guide/extensions.html]

- [X] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [X] Repository name is Slicer+ExtensionName
- [X] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [X] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [X] Any known related patents must be mentioned in the extension description.
- [X] If source code license is more restrictive for users than BSD, MIT, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [X] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (main, master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [X] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://raw.githubusercontent.com/user/repo/main/SomeIcon.png)
- [X] Screenshot URLs (screenshoturls) are correct, contains at least one
- [X] Homepage URL points to valid webpage containing the following:
  - [X] Extension name
  - [X] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [X] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [X] Description of contained modules: at one sentence for each module
  - [X] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [X] Publication: link to publication and/or to PubMed reference (if available)
  - [X] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/master/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [X] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)

### CODE REVIEW

**Comment by atracsys-sbt** [comment]
So I changed my mind and changed the extension name to Slicer-AstmPhantomTest, so that I could pass all the checks.
Thank you for considering reviewing my PR now.

**Comment by lassoan** [comment]
Thank you for your contribution, this all looks great.

There are just a few things to address before the new extension can be added to the Extensions Index:

1. Extension name finalization

> So I changed my mind and changed the extension name to Slicer-AstmPhantomTest, so that I could pass all the checks.
> Thank you for considering reviewing my PR now.

Thank you, this make things more clear. We generally ask for removing the dash from the name (use `SlicerAstmPhantomTest` repository name instead of `Slicer-AstmPhantomTest`). It seems like a small detail, but having all extensions follow the same naming conventions help a lot for both manual lookup of the extension name (e.g., when we have a list of folder containing many extensions) and automatic processing (e.g., get extension name by removing `Slicer` prefix from the repository name).

2. Update extension metadata in https://github.com/Atracsys/Slicer-AstmPhantomTest/blob/256687d79db94b7841088588cab12f7d2c4648f7/CMakeLists.txt#L7-L13 in accordance with the s4ext file.

3. Suggestions for https://github.com/Atracsys/Slicer-AstmPhantomTest (these are not required for adding to the Extensions Index, just recommendations to consider)

- "download from the Latest Development Snapshot, as it includes new features necessary for the tests." -> specifying the version/date would allow the user to check if the correct version is used.
- "PLUS Toolkit offers a wrapper to a system SDK, but may not include the actual SDK, which needs to be installed separately on the computer" -> we include the SDK in most if not all cases; is there a specific SDK that you have in mind? It would be better to be more specific and tell which SDK is expected to be missing and tell what to do about it.
- "the configuration file example below" -> We could add this configuration in the example configurations in the Plus package. It would make things a bit more convenient for the user.
- "The option SendValidTransformsOnly has to be set to FALSE." - It would be nice if you could very briefly tell why this is important.
- "Atracsys trackers, the device parameter SymmetriseCoordinates="1" also needs to be set." - It would be nice if you could very briefly tell why this is important.
- "Adding the module" - don't forget to update these instructions after the extension is available in the Extensions Manager
- Are the parameters that you set (Tracker S/N, Pointer, Phantom, ...) saved into the scene? If yes, it would be nice to save the Plus configuration file into the scene as well (to have everything archived and reproducible in one place). You can then just load the scene, PlusServerRemote module starts the server with the saved configuration file, and all other settings are set up correctly in accordance with the Plus configuration.

**Comment by jamesobutler** [comment]
> We generally ask for removing the dash from the name (use `SlicerAstmPhantomTest` repository name instead of `Slicer-AstmPhantomTest`). It seems like a small detail, but having all extensions follow the same naming conventions help a lot 

@lassoan Should we drop some of the recommendations such as `Slicer-AstmPhantomTest`?
https://github.com/Slicer/ExtensionsIndex/blob/127eb748427207d3449ea12c5505d45684bc95b5/scripts/check_description_files.py#L86-L96

**Comment by lassoan** [comment]
> Should we drop some of the recommendations

It would be nice, but it would be hard to change the name of existing extensions. Maybe we should make the test more strict and add existing extension names as exceptions?

**Comment by atracsys-sbt** [comment]
>     1. Extension name finalization
I changed it to SlicerAstmPhantomTest.
>     2. Update extension metadata in https://github.com/Atracsys/Slicer-AstmPhantomTest/blob/256687d79db94b7841088588cab12f7d2c4648f7/CMakeLists.txt#L7-L13 in accordance with the s4ext file.
Done.
>     3. Suggestions for https://github.com/Atracsys/Slicer-AstmPhantomTest (these are not required for adding to the Extensions Index, just recommendations to consider)
>     * "download from the Latest Development Snapshot, as it includes new features necessary for the tests." -> specifying the version/date would allow the user to check if the correct version is used.
I clarified that.
>     * "PLUS Toolkit offers a wrapper to a system SDK, but may not include the actual SDK, which needs to be installed separately on the computer" -> we include the SDK in most if not all cases; is there a specific SDK that you have in mind? It would be better to be more specific and tell which SDK is expected to be missing and tell what to do about it.
I clarified that too.
>     * "the configuration file example below" -> We could add this configuration in the example configurations in the Plus package. It would make things a bit more convenient for the user.
Very good idea, I will create two examples (one Atracsys and one NDI), include those in PlusLibData and create the PR.
>     * "The option SendValidTransformsOnly has to be set to FALSE." - It would be nice if you could very briefly tell why this is important.
This is necessary to detect when a tool gets out of tracking. I clarified that in the ReadMe.
>     * "Atracsys trackers, the device parameter SymmetriseCoordinates="1" also needs to be set." - It would be nice if you could very briefly tell why this is important.
It's something that puzzles me with our trackers: without setting that option to "1", the origin of the coordinate system is set by default to the left camera and not at the device center like most other trackers. I clarified that in the ReadMe.
>     * "Adding the module" - don't forget to update these instructions after the extension is available in the Extensions Manager
Yes, I will update the ReadMe when the extension goes live and when the new config example files will be added to PlusLibData.
>     * Are the parameters that you set (Tracker S/N, Pointer, Phantom, ...) saved into the scene? If yes, it would be nice to save the Plus configuration file into the scene as well (to have everything archived and reproducible in one place). You can then just load the scene, PlusServerRemote module starts the server with the saved configuration file, and all other settings are set up correctly in accordance with the Plus configuration.
No, this information is not saved into the scene yet, but I will consider adding this suggestion to a future update for sure.

**Comment by atracsys-sbt** [comment]
All right, I've done all the necessary changes mentioned above. I think it's ready to integrate the extensions manager :)
I'll update the installation instructions in the ReadMe after the merge.

**Comment by lassoan** [comment]
Thank you, it all looks good. I've tested building and packaging on Windows, it worked well, too. So, this is indeed ready. I'll merge the pull request now.

**Pull request merged**
