### PR TITLE
ENH: Add RVXVesselnessFilters extension

### PR DESCRIPTION
**Pull request by Thibault-Pelletier**
# New extension

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Any known related patents must be mentioned in the extension description.
- [x] LICENSE.txt is present in the repository root. MIT  (https://choosealicense.com/licenses/mit/) or Apache (https://choosealicense.com/licenses/apache-2.0/) license is recommended. If source code license is more restrictive for users than MIT, BSD, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (main, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://raw.githubusercontent.com/user/repo/main/SomeIcon.png)
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [x] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/main/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [x] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)

### CODE REVIEW

**Review by pieper — APPROVED** [review]
I don't know if others want to comment but from a quick review this looks great to me.

**Comment by jcfr** [comment]
Thanks for the contribution :pray: 

Few comments:
* While reviewing the build-system and overall organization, I created a [few issues](https://github.com/R-Vessel-X/SlicerRVXVesselnessFilters/issues) that should be addressed.
* Reviewing the repository (https://github.com/JonasLamy/LiverVesselness) where the original implementation was adapted from, I couldn't find any license. Could this be addressed either in the upstream repo or could details about communication with the original author added to the README of the extension ?

**Comment by Thibault-Pelletier** [comment]
Thanks for the feedback!
I will be fixing the several Cxx and CMake issues today and I have just pinged Jonas and the other RVesselX partners regarding the links to the original repo and papers.

I will let you know when everything is taken into account!

**Comment by Thibault-Pelletier** [comment]
Hi @jcfr,

I have just updated the repo with the different feedbacks you addressed in your review.
Could you have another look and let me know if we are still missing things for the PR?

Best,
Thibault

**Comment by Thibault-Pelletier** [comment]
Hi @jcfr and @pieper,

Did you guys get the time to review the latest version of this PR?

Thanks in advance,
Best,
Thibault

**Comment by pieper** [comment]
@jcfr did you have any further concerns?  If not I'm fine to merge.

**Comment by lassoan** [comment]
This looks really nice, useful, clearly implemented and documented. I haven't checked the checklist in detail but it looks good to be merged.

I have only two comments:
- Creating a separate C++ CLI for each ITK filter is a significant development and maintenance overhead compared to having a single module with a method selector. See for example how [vtkITKImageThresholdCalculator](https://github.com/Slicer/Slicer/blob/main/Libs/vtkITK/vtkITKImageThresholdCalculator.h) bundles many threshold calculation methods. Having a single module would also allow users to try multiple methods more easily, as they would not need to set the inputs/outputs in each module.
- Consider adding the new methods to ITK in a remote module. ITK provides a very nice template with automatic testing, Python wrapping, etc. If it's in ITK then it can be used easily in Slicer but also in many other projects.

**Pull request merged**
