### PR TITLE
New Extension mp2rageBackgroundSuppression 

### PR DESCRIPTION
**Pull request by SamBrenny**
# New extension

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Any known related patents must be mentioned in the extension description.
- [x] LICENSE.txt is present in the repository root. MIT  (https://choosealicense.com/licenses/mit/) or Apache (https://choosealicense.com/licenses/apache-2.0/) license is recommended. If source code license is more restrictive for users than MIT, BSD, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (main, release, ...) instead of a specific git hash to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://raw.githubusercontent.com/user/repo/main/SomeIcon.png)
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [ ] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/main/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [x] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)
- Hide unused features in the repository to reduce noise/irrelevant information:
  - [x] Click `Settings` and in repository settings uncheck `Wiki`, `Projects`, and `Discussions` (if they are currently not used)
  - [x] Click the settings icon next to `About` in the top-right corner of the repository main page and uncheck `Releases` and `Packages` (if they are currently not used)
 If you have any questions or concerns let us know

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for the contribution :pray:

After a cursory review, here are some issues you should consider addressing:
* https://github.com/harellab/SlicerMp2rageBackgroundSuppression/issues/1
* https://github.com/harellab/SlicerMp2rageBackgroundSuppression/issues/2
* https://github.com/harellab/SlicerMp2rageBackgroundSuppression/issues/3
* https://github.com/harellab/SlicerMp2rageBackgroundSuppression/issues/4

Last, similarly to the `SlicerFreeSurfer` extension I am wondering if this extension should be called `SlicerMP2RAGE` ?

Or since this work seems to be done in the context of a larger initiative[^2] related deep brain stimulation (DBS), would it be sensible to add a new module to the `SlicerNetstim` extension (and may be having it renamed `SlicerDeepBrainSimulation` ?)

cc: @pieper @lassoan 

### Related

* https://dbsguidedocs.readthedocs.io
* https://github.com/wafiqsyed/dbsGuideDocs


[^1]: https://github.com/PerkLab/SlicerFreeSurfer
[^2]: https://movementdisorderslab.umn.edu/projects/udall-study
[^3]: https://github.com/netstim/SlicerNetstim

**Comment by hbraunDSP** [comment]
Thanks! We'll get to work on the issues you submitted.  Regarding changing the name, I tentatively support moving to `SlicerMP2RAGE`.  There is nothing dbs-specific about this feature, so I don't want to make it part of NetStim -- MP2RAGE is just a T1-weighted contrast, applicable anywhere a T1 image is needed but particularly useful at higher field strengths on Siemens scanners.

**Comment by jcfr** [comment]
> I tentatively support moving to `SlicerMP2RAGE`


cc: @pieper @lassoan

**Comment by pieper** [comment]
Having larger extensions that include a set of related modules is cleaner I think.  It's easier for users to manage just one extension and it's easier for us as extension maintainers if there's an team that "owns" a topic and can decide what to include.  Moving this into an existing extension would be preferred if there's a match.

**Comment by hbraunDSP** [comment]
I don't see a good match among the existing Slicer extensions, but feel free to suggest one if I missed it.  We've addressed the issues @jcfr submitted; We'll change the extension name to `SlicerMP2RAGE` and any future MP2RAGE-related tools can be added to it.

**Comment by SamBrenny** [comment]
The Slicer extension mp2rageBackgroundSupression has been renamed to SlicerMP2RAGE and updated documentation.  We believe this is ready to merge.

**Comment by hbraunDSP** [comment]
We'd like to get this merged, and as far as we know it's ready.  Are there any changes you'd like us to make?

**Comment by pieper** [comment]
Looking again I have a couple more comments:

* I see you have a non-module file in [this folder](https://github.com/harellab/SlicerMP2RAGE/tree/trunk/BackgroundNoiseSuppression) that should be in a subdirectory (like a Lib directory) so it won't be part of the module discovery process.
* The testing nrrd files in the repository are not a huge problem for a single tool like this, but generally they should be hosted another place, like in a release asset and the test should be configured to download them when they are needed (e.g. so that a user of the module could optionally run the test but the test data is not installed for every user).

**Comment by pieper** [comment]
Not sure why the lint check failed. https://github.com/Slicer/ExtensionsIndex/actions/runs/8209333331/job/22491632783?pr=1983

Doesn't look like a problem though, so I'll go ahead and merge this.

**Pull request merged**
