### PR TITLE
Remove duplicated extension CardiacAgastonMeasures

### PR DESCRIPTION
**Pull request by jcfr**
This commit removes extension `CardiacAgastonMeasures` (added in #706) that is a duplicate of `CardiacAgatstonMeasures` (added in #1011).

### CODE REVIEW

**Comment by jcfr** [comment]
Reported-by: @rkikinis

Cc: @jessicaforbes @hjmjohnson

**Comment by jcfr** [comment]
As soon this is reviewed/confirmed, I will integrate.

**Comment by jessicaforbes** [comment]
This looks correct to me. Thanks @jcfr

**Comment by jcfr** [comment]
Thanks for reviewing.

**Pull request merged**
