### PR TITLE
ENH: Add ROBEXBrainExtraction extension

### PR DESCRIPTION
**Pull request by acsenrafilho**
Description:
This extension aims to extract the brain from the skull. This tool was
intensively tested with T1 MRI images, but the pipeline could be applied
to any other structural MRI images, namely T2 and PD. This module is an
adaptation of ROBEX brain extraction tool, given by Iglesias, J. E. et
al (2011). Robust Brain Extraction Across Datasets and Comparison With
Publicly Available Methods. IEEE Transactions on Medical Imaging, 30(9).
DOI:10.1109/TMI.2011.2138152

Contributors:
Antonio Carlos da S. Senra Filho (University of Sao Paulo)

### CODE REVIEW

**Comment by acsenrafilho** [comment]
Hi @ihnorton and @lassoan 

I made the changes requested in previous submission (ENH: Add BrainExtractionTool extension #1369) regarding the license issues and I also renamed the extension in order to not create any confusion with the FSL-BET tool.

By the way, should I close the previous pull request ?

Thank you for all the help and suggestions.

**Comment by jcfr** [comment]
Cc: @ihnorton @lassoan

**Comment by ihnorton** [comment]
👍 LGTM

**Comment by ihnorton** [comment]
@acsenrafilho FYI, the build is [failing on Windows](http://slicer.cdash.org/viewBuildError.php?buildid=944780)  due to `#include <unistd.h>`, however your extension appears to build fine without that include, so it could be removed (possibly other build issues on Windows, I only checked on Mac).

**Comment by acsenrafilho** [comment]
Hi @ihnorton

Thank you for your advice. I've changed the includes, as you noticed, and checked that in Linux it works normally. I hope that this minor fix can give the right answer for Windows as well (at least pass the build process to the next point).
The pull request is the #1383 

Cheers

**Pull request merged**
