### PR TITLE
ENH: add BigImage extension s4ext file

### PR DESCRIPTION
**Pull request by gaoyi**
SlicerScope adds the function to view and process Giga-byte sized whole slide images through the openslide library and python scripted module.

# TODO list for submitting a new extension

To make sure users can find your extension, understand what it is intended for and how to use it, please complete the checklist below. You do not need to complete all the item by the time you submit the pull request, but most likely the changes will only be merged if all the tasks are done. See more information about the submission process [here](https://slicer.readthedocs.io/en/latest/developer_guide/extensions.html)

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Any known related patents must be mentioned in the extension description. No
- [x] If source code license is more restrictive for users than BSD, MIT, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description. N/A
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (main, master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://raw.githubusercontent.com/user/repo/main/SomeIcon.png)
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [ ] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set. Tutorial working in progress
  - [x] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/master/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [x] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)

[If you have any questions or comments then please describe them here.]

### CODE REVIEW

**Comment by jamesobutler** [comment]
> Add a license file to the repository. Github makes it quite easy: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

_Originally commented by @lassoan in https://github.com/Slicer/ExtensionsIndex/pull/1821#issuecomment-1115395134_

@gaoyi Can you provide a license in the repository? I currently do not know if this extension can be freely used for commercial purposes in various Slicer custom applications.

**Comment by gaoyi** [comment]
Thanks James, This is added. I copied Slicer's License file to the repository home folder.

**Comment by gaoyi** [comment]
> > Add a license file to the repository. Github makes it quite easy: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository
> 
> _Originally commented by @lassoan in [#1821 (comment)](https://github.com/Slicer/ExtensionsIndex/pull/1821#issuecomment-1115395134)_
> 
> @gaoyi Can you provide a license in the repository? I currently do not know if this extension can be freely used for commercial purposes in various Slicer custom applications.

Hi @jamesobutler, The license file is added. Please advice what i should do next for the merging. Thanks! yi

**Comment by lassoan** [comment]
Remaining tasks:
- I would like to learn more about it and try it on some data that is known to be compatible, but I have no idea what to do, where to start. Could you add a list of steps to the README.md file that I can follow (where to download a sample data set from, how can I load it into Slicer, what can I do with it) to try what the extension can do?
- Please also add the name and 1-2 sentences for each module that the extension provides (without that it is hard to find what modules I should look for).
- Please confirm that you want to write a git hash into the s4ext file. If you use a git hash instead of a branch name then you need to submit a new pull request here each time you update your extension and you want that change to be available for users. I would recommend replacing the git hash by the branch name (`main`).

**Comment by lassoan** [comment]
I've tested the extension and made a few improvements. Most notably, installation of OpenSlide happens automatically on Windows now.

https://github.com/gaoyi/SlicerBigImage/pull/2

Please merge the pull request and this extension should be ready for submission.

**Comment by lassoan** [comment]
The extension is now added to the index. Check out the [dashboard](https://slicer.cdash.org/index.php?project=SlicerPreview) and Extensions Manager tomorrow if everything looks good.

**Pull request merged**
