### PR TITLE
Add Geodesic extension

### PR DESCRIPTION
**Pull request by jcfr**
Thank you very much for considering sharing your extension with the Slicer community.

To make sure users can find your extension, understand what it is intended for and how to use it, please complete the checklist below. You do not need to complete all the item by the time you submit the pull request, but most likely the changes will only be merged if all the tasks are done.

- [X] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [X] Repository name is Slicer+ExtensionName
- [X] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [X] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [X] Extension icon URL is correct
- [X] Screenshot URLs (screenshoturls) are correct, contains at least one
- [X] Homepage URL points to valid webpage containing the following:
  - [X] Extension name
  - [X] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [X] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [X] Description of contained modules: at one sentence for each module
  - [X] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set

See more information about the submission process on the Slicer wiki: https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/BuildTestPackageDistributeExtensions

If you have any questions or comments then please describe them here.

Co-authored-by: FredericBr <32647431+FredericBr@users.noreply.github.com>

### CODE REVIEW

**Comment by jcfr** [comment]
@FredericBr @nourryan  Extension has been integrated and should be available with tomorrow nightly build.

If you would like the extension to be available with the latest release, consider submitting a similar pull-request against the 4.10 branch.

**Comment by FredericBr** [comment]
Thanks Jean-Christophe.
I will made a pull request against the 4.10 branch in a couple of day.
Best,
PS. it's not possible to change the name because the GNU license is submitted with this name...

**Comment by jcfr** [comment]
> because the GNU license is submitted with this name

To clarify, by GNU license, you mean the `CeCILL FREE SOFTWARE LICENSE AGREEMENT` ?

**Comment by FredericBr** [comment]
Yes, sorry.

**Comment by FredericBr** [comment]
A little question: If we have minor change (for example the "How to cite" section in python script), we just have to change our code in our github repository and 3Dslicer update it during his last release?

**Comment by jcfr** [comment]
Since a specific hash is listed in the description file, you will have to update the description file.

An other approach would be to specify master in the description file, that way it would always build the latest version.

**Comment by FredericBr** [comment]
Ok thanks. Thus in the GeodesicSlicer.s4ext
I have to replace:
# This is source code manager (i.e. svn)
-scmrevision e8c0459
+scmrevision master

**Comment by jcfr** [comment]
Exactly.

And when you will submit the PR against the 4.10 branch, you can do the same thing.

And ultimately, if the code to support both the latest release and the preview (aka nightly) release  diverge .. you can then have two branches: `master` and `master-4.10`

**Comment by FredericBr** [comment]
Ok. Thanks for all these explanations.

**Comment by lassoan** [comment]
Thanks for contributing this extension. Note that restrictive (copyleft) licenses are very uncommon in our community. Please highlight the limitations in all description of the extension (extension's short summary, module documentations, etc) to make sure users are aware.

**Comment by FredericBr** [comment]
Dear Andras,
I will highlight the description, but this license is not really restrictive (it is like a MIT license), but because it could imply some clinical patients (the extension could help in brain stimulation), we just want to clear us of all risk.

**Comment by lassoan** [comment]
The problem is that it is a copyleft license. You cannot use the extension in a software product because it would force developers publicly disclose the source code of the entire software. Cecill-C or Cecill-B would not be good.

**Comment by pieper** [comment]
Hi @FredericBr - Please read [this thread about GPL software](https://discourse.slicer.org/t/rpy2-pip-installation-fails/4883/15?u=pieper) for some background about why we are very careful about the license terms and avoid copyleft.  It's really important that people carefully consider the license terms of software they use, just like you'd want to know the price of a meal before you buy it.  Thanks!

**Comment by FredericBr** [comment]
To be honest, I create the software but my previous employer (university of Caen) was the owner of it, it is why it's my legal department that choose the license without me. I will get in touch with them to perhaps reconsider our license.
Thank you for your information.

**Comment by FredericBr** [comment]
@lassoan @pieper I have a made demands to my legal department, but if accepted, it will make a long time to switch the license. As I understand it, the only problem is just for the non public use, no?
@jcfr Thanks for the release in the nightly version. However, we do not see our extension icon (link broken?), do you know why?

**Comment by pieper** [comment]
@FredericBr it's a little unclear what the long term implications would be if you aren't able to switch the license. At the least there should be a prominent warning, as @lassoan pointed out so that people understand that the software licensing terms are different than the rest of Slicer.  

Also, we have never really been able to clarify what implications there are for making copyleft software available via Slicer extensions.  We wouldn't want the license from one extension to "infect" other extensions or the Slicer core.

**Comment by jcfr** [comment]
> Thanks for the release in the nightly version. However, we do not see our extension icon (link broken?), do you know why?

Extension has been built on all three platforms. See [dashboard](http://slicer.cdash.org/index.php?project=SlicerPreview&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=Geodesic)

The extension is also available on the server:

image

That said, the extension icon is incorrect. This is explained by the fact the `scmrevision` found in the description file is still https://github.com/nourryan/SlicerGeodesic/commit/e8c0459030563f623693d33470e4e67414ce5add, this would have to be changed to either `master` or the latest hash.

See https://github.com/Slicer/ExtensionsIndex/blob/master/GeodesicSlicer.s4ext#L10

**Comment by FredericBr** [comment]
@pieper Ok, I understand. Once again, the final decision depends on my legal department but I will try to clarify your position during the vote on our next legal committee.
@jcfr Indeed I spoke about the extension icon, sorry. Thanks for the update, I thought I had done the last friday.

**Pull request merged**
