### PR TITLE
TomoSAM extension

### PR DESCRIPTION
**Pull request by fsemerar**
# New extension

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Any known related patents must be mentioned in the extension description.
- [x] LICENSE.txt is present in the repository root. MIT  (https://choosealicense.com/licenses/mit/) or Apache (https://choosealicense.com/licenses/apache-2.0/) license is recommended. If source code license is more restrictive for users than MIT, BSD, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (main, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://raw.githubusercontent.com/user/repo/main/SomeIcon.png)
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [x] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/main/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [x] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)
- Hide unused features in the repository to reduce noise/irrelevant information:
  - [x] Click `Settings` and in repository settings uncheck `Wiki`, `Projects`, and `Discussions` (if they are currently not used)
  - [x] Click the settings icon next to `About` in the top-right corner of the repository main page and uncheck `Releases` and `Packages` (if they are currently not used)

### CODE REVIEW

**Comment by fsemerar** [comment]
Hi, I was wondering if I need to make the SlicerTomoSAM repo public in order for you to review it, or if I could add you or any other code reviewer as a contributor to the private git instead until it is accepted. I'm also currently in the process of submitting the related paper, which will still take a day or two to be online, which is why I would also prefer to keep the Github repo private until then. Thank you in advance for your help

**Comment by fsemerar** [comment]
Ok thank you. I am planning to make it public on Friday. In the meantime, I have added you three to the private repository in case you have time to start reviewing it.

**Comment by fsemerar** [comment]
I have just made it public @pieper @lassoan @jcfr. Thank you in advance for your help!

**Comment by pieper** [comment]
Good point @jamesobutler we should try to be consistent.  @fsemerar did you look through the previous discussions?  Maybe there's a way to unify the use of SAM?

**Comment by fsemerar** [comment]
@jamesobutler @pieper I did look through the discussions and I am aware of SAMM.  However, I would like to emphasize that we take a significantly different approach than their PyZMQ server approach. I also could not get their Slicer extension to work properly on my laptop, which is why we decided to implement our own (it probably works well for a machine with a dedicated GPU, I am not sure). 
TomoSAM splits the process between creating the embeddings on a GPU machine and then runs the Slicer extension easily on CPU. In addition, we have greatly reduced the number of dependencies that are needed to run. I hope you can review TomoSAM as we are proposing; thank you again for your help

**Comment by fsemerar** [comment]
By the way, if you want to have a quick look at how our extension works, we uploaded a [YouTube video tutorial](https://youtu.be/4nXCYrvBSjk)

**Comment by pieper** [comment]
Since it sounds like they are different approaches I don't see the harm in having both options available.  As far as I can see this extension is ready to go unless others have comments.

**Comment by lassoan** [comment]
Thanks a lot for your contribution, very nice work. A couple of things to fix before the extension is added to the index:
- Module logic should be in ...Lib folder, nothing should be installed when just importing a .py file - implemented in https://github.com/fsemerar/SlicerTomoSAM/pull/1
- Embedding instructions are way too complex. By looking at the instructions I did not even try to follow them. Nobody would risk spending even 5 minutes of his time to just try something that has a high chance to fail. The absolute minimum would be to add a button that downloads a sample data set and the correponding embedding (you can upload the files as release assets to github and download using SampleData as it is shown in the module template). If users like how everything works, then they maybe 10% of users invest 5-10 minutes to try it on their own data. If we want more users to try it on their own data then computing embedding must be done fully automatically.
- Do not download the several-GB SAM model file without displaying a message to (but preferable asking permission from) the user. The download takes a a few minutes on a fast internet connection and may take hours on a slow internet connection, so there is a high chance that the user assumes that the module is just broken and never tries it again.
- It would be better to download the several-GB SAM model into a folder that is accessible to all Slicer versions. For example, `qt.QStandardPaths.writableLocation(qt.QStandardPaths.DownloadLocation)`.
- curl may or may not be available on the system. Use urllib or SampleData for downloading the model file instead.
- New layouts must not be created for each layout change. Precreate the layouts and then just switch between them. Do not start at 500, because some examples use that. You can choose some random number over 10000 instead.
- Do not set tooltips in code (using `setToolTip`), do it in Qt Designer instead
- Avoid special characters in source code. Instead of trying to show some kind of plain-text bullet-point list using `•`, you can simply use HTML formatting.

**Comment by fsemerar** [comment]
Thank you for your comments and review. We will take care of each one of the bullets ASAP. We really appreciate your consideration

**Comment by fsemerar** [comment]
Hi, I have just finished fixing the last item from the code review @lassoan @jcfr @pieper @jamesobutler. 

These are our changes to address the comments above: 

- Merged the PR which separates the logic into the tomosamLib folder and deals with the installation of the required packages
- Simplified the embeddings instructions and added a button to the UI to directly generate the embeddings within the extension
- Added button to download the weights for SAM into `qt.QStandardPaths.writableLocation(qt.QStandardPaths.DownloadLocation)` and extra logic to check that the .pth file is not missing
- Replaced curl with urllib
- Only six layouts are created with IDs > 20000 and used to switch view
- Tooltips are now set in the tomosam.ui file, except for one which requires a variable string message
- Removed all special characters

Let me know if there is anything else that you would like us to address. We are excited to have TomoSAM as part of Slicer's Extension Manager!

**Comment by pieper** [comment]
@lassoan do you want to have another look?  I am fine with merging.

**Comment by jamesobutler** [comment]
@fsemerar Can you describe the issues you were running into that required you to revert the PyTorch >= 1.12 requirement (https://github.com/fsemerar/SlicerTomoSAM/commit/87bbeb81c1cbab0de830a93396e44a9e43c5cf28) that @lassoan added in https://github.com/fsemerar/SlicerTomoSAM/commit/f2008d710a036849be22bbd6ef26ce09d04b353c?

**Comment by fsemerar** [comment]
The minimum version was enforced on torch but nothing was enforced on torchvision. This meant that torchvision version 0.2.0 was installed by pip, which was missing several things that segment_anything needs (e.g. torchvision.ops). If instead no minimum version is enforced on torch, pip installs the latest torch and torchvision, both compatible with segment_anything. I was getting the same on both MacOS and Ubuntu, but removing the minimum version now works on both

**Comment by jamesobutler** [comment]
Does `segment-anything` or SlicerTomoSAM appropriately enforce dependencies related to the minimum required torch and torchvision version? 

There have been a lot of Slicer users running into issues with another project (TotalSegmentor) due to older torch versions not being compatible with the latest model. The enforcement of a minimum torch version helped make sure their torch dependencies were valid because otherwise they struggle to understand why things error out.

**Comment by fsemerar** [comment]
> Does `segment-anything` or SlicerTomoSAM appropriately enforce dependencies related to the minimum required torch and torchvision version?
> 
> There have been a lot of Slicer users running into issues with another project (TotalSegmentor) due to older torch versions not being compatible with the latest model. The enforcement of a minimum torch version helped make sure their torch dependencies were valid because otherwise they struggle to understand why things error out.

How do you suggest the enforce the minimum required torch and torchvision on the SlicerTomoSAM side? I don’t think `segment-anything` enforces any specific version, but that’s not something I can change.

What I see as the issue is that there is no way to enforce a minimum version on torchvision through [SlicerPyTorch](https://github.com/fepegar/SlicerPyTorch/blob/main/PyTorchUtils/PyTorchUtils.py)

**Comment by jamesobutler** [comment]
Yes if SlicerPyTorch only has support to specify a minimum for torch then it would seem logic for us to add support for a minimum version of torchvision as well. It appears Facebook Research [instructs](https://github.com/facebookresearch/segment-anything#installation) to have pytorch>=1.7 and torchvision>=0.8 in the readme, but they seemingly don't have an explicit requirements.txt.

It also appears you are pip installing `segment-anything` (see [here](https://github.com/fsemerar/SlicerTomoSAM/blob/87bbeb81c1cbab0de830a93396e44a9e43c5cf28/TomoSAM/tomosamLib/tomosamLogic.py#L56)), which would seemingly come from https://pypi.org/project/segment-anything/. This project is lacking many details and doesn't appear to have official ownership from facebook research. I mention this because torch recently had issues with packages being uploaded to pypi with the same names as some of their projects which resulted in security issues (https://pytorch.org/blog/compromised-nightly-dependency/). From Facebook research it appears they [instruct](https://github.com/facebookresearch/segment-anything#installation) to pip install the source directly `pip install git+https://github.com/facebookresearch/segment-anything.git` and make no mention of a pypi project which is why I'm suspicious of how you are currently installing segment-anything.

**Comment by fsemerar** [comment]
> Yes if SlicerPyTorch only has support to specify a minimum for torch then it would seem logic for us to add support for a minimum version of torchvision as well. It appears Facebook Research [instructs](https://github.com/facebookresearch/segment-anything#installation) to have pytorch>=1.7 and torchvision>=0.8 in the readme, but they seemingly don't have an explicit requirements.txt.
> 
> It also appears you are pip installing `segment-anything` (see [here](https://github.com/fsemerar/SlicerTomoSAM/blob/87bbeb81c1cbab0de830a93396e44a9e43c5cf28/TomoSAM/tomosamLib/tomosamLogic.py#L56)), which would seemingly come from https://pypi.org/project/segment-anything/. This project is lacking many details and doesn't appear to have official ownership from facebook research. I mention this because torch recently had issues with packages being uploaded to pypi with the same names as some of their projects which resulted in security issues (https://pytorch.org/blog/compromised-nightly-dependency/). From Facebook research it appears they [instruct](https://github.com/facebookresearch/segment-anything#installation) to pip install the source directly `pip install git+https://github.com/facebookresearch/segment-anything.git` and make no mention of a pypi project which is why I'm suspicious of this pypi project.

Ok, I can change the instruction to point to git+https://github.com/facebookresearch/segment-anything.gitget instead of segment-anything. Would you recommend any other change on our side?

**Comment by lassoan** [comment]
I don't think adding a minimum version requirement would install older torch version. Maybe installing without light-the-torch installs the latest version but then you would need to figure out the install url based on your hardware and cuda version

You can specify torch version requirement in current slicerpytorch extension. If it is a problem that vision version cannot be specified then it would be great if you could send a pull request to slicerpytorch to add it (it would look very similar as the last commit that adds torch version specifier).

**Comment by fsemerar** [comment]
Ok no problem, I will open a PR soon then

**Comment by lassoan** [comment]
See example of installing torch using slicerpytorch here: https://github.com/lassoan/SlicerTotalSegmentator/blob/4a9386634e90b4a1fb541d4fa016cbdde22ba96b/TotalSegmentator/TotalSegmentator.py#L571

**Comment by fsemerar** [comment]
I have just opened a PR for SlicerPyTorch: https://github.com/fepegar/SlicerPyTorch/pull/12
After it is approved, I will update TomoSAM to add a minimum version for both torch and torchvision

**Comment by fsemerar** [comment]
Would it be possible to have this wrapped up by next Wednesday morning? I have a presentation at work and would love to have the extension released for it.

**Comment by pieper** [comment]
I think the main thing is to be ready to answer if people run into installation issues.  Our experience with TotalSegmentator, MONAI Label, and similar code is that these driver and dependency issues eat up a lot of support time.  As long as you are ready to handle these questions @fsemerar I see no reason not to go ahead.

Maybe adding some warnings to the README that this is all new and evolving and that there may be dependency issues, and information about how to troubleshoot, could help people adjust their expectations.

**Comment by jamesobutler** [comment]
I made an additional comment yesterday at https://github.com/fsemerar/SlicerTomoSAM/commit/b06aa4312c309e02c281d6c9e0e7ec8df5c67a64#r120364661, that would be quick to change. Not sure if you saw that one.

**Comment by fsemerar** [comment]
@jamesobutler sorry I had missed your comment, I've just tested and updated the command as per your suggestion. 

@pieper I am committed to follow up on potential users' issues. I can update the README with the new installation instructions as soon as this PR is accepted and will add some extra troubleshooting information as they arise.

**Comment by pieper** [comment]
I'll go ahead and merge then.  We can see if any issue crop up next week.  Thanks for this cool extension and everyone for the reviews!

**Pull request merged**
