### PR TITLE
Add Liver Anatomy Annotation extension

### PR DESCRIPTION
**Pull request by Thibault-Pelletier**
* Add LiverAnatomyAnnotation extension. The extension is a plugin for Slicer3D which aims at easing the segmentation of liver, liver vessels and liver tumor from DICOM data for annotation purposes. The exported segmentations will then be used in research.

Thank you for contributing to 3D Slicer!

- **To add a new extension with this pull request**: Please keep content of "TODO list for submitting a new extension" section and put an 'x' character in the brackets for each todo item to indicate that you have accomplished that prerequisite.

- **To update an existing extension with this pull request**: Please delete all text in this template and just describe which extension is updated and optionally tell us in a sentence what has been changed. To make extension updates easier in the future (so that you don't have to submit a new pull request after each change in your extension), you may consider replacing specific git hash in your s4ext file by a branch name (for example: `master` or `release` for nightly version; `(majorVersion).(minorVersion)` such as `4.10` for stable Slicer version).

# TODO list for submitting a new extension

[To make sure users can find your extension, understand what it is intended for and how to use it, please complete the checklist below. You do not need to complete all the item by the time you submit the pull request, but most likely the changes will only be merged if all the tasks are done. See more information about the submission process here: https://slicer.readthedocs.io/en/latest/developer_guide/extensions.html]

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Any known related patents must be mentioned in the extension description.
- [x] If source code license is more restrictive for users than BSD, MIT, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://github.com/user/project/raw/main/path/to/icon.png)
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [x] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/master/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [x] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)

[If you have any questions or comments then please describe them here.]

### CODE REVIEW

**Comment by lassoan** [comment]
Thank you for your contribution, this looks really nice. We'll review the submission in detail, but in the meantime please work on the followings:
- Currently the extension [only works on Windows](https://github.com/R-Vessel-X/SlicerLiverAnatomyAnnotation/blob/main/RVesselXLiverSegmentationEffect/RVesselXLiverSegmentationEffect.py#L62). Please use https://github.com/fepegar/SlicerPyTorch extension to install pytorch in a robust and platform-independent way.
- Extension name: "anatomy annotation" is referred to as "segmentation" in [Slicer terms](https://slicer.readthedocs.io/en/latest/user_guide/getting_started.html#glossary). Also, there are other liver segmentation tools (for example in MONAILabel, NVidiaAIAA, etc.), therefore we need something in the name that clearly distinguishes your extension. What do you think about renaming the extension to RvxLiverSegmentation (repository name: SlicerRvxLiverSegmentation)?

**Comment by Thibault-Pelletier** [comment]
@lassoan thank you for your feedback!

I have renamed the extension name to RVXLiverSegmentation  and the repository to SlicerRVXLiverSegmentation  as you suggested.

I have also fixed the PyTorch install to make use of the PyTorch extension if available (the fallback will be the default pip torch in case the PyTorch extension is not available for backward compatibility with Slicer 4.11).

Please don't hesitate to let me know if you have any further feedback on this extension.

**Comment by lassoan** [comment]
Thank you for the updates!

I've tried to test your extension but I got stuck because the tutorial did not provide any data set. Ideally, you would register a custom data set (upload it as a release asset to the github repository and register a download link into the SampleData module - see example [here](https://github.com/rbumm/SlicerLungCTAnalyzer/blob/master/LungCTAnalyzer/LungCTAnalyzer.py#L40-L76)).

**Comment by Thibault-Pelletier** [comment]
@lassoan thank you for your feedback (and sorry for the delayed answer).
I have updated the plugin and added a link to one of the 3D-IRCAD volumes to test the plugin.

Please let me know if you have further feedback on the plugin!

**Comment by lassoan** [comment]
This works great. The liver segmentation is particularly impressive - very quick and looks very nice to me.

I'll merge this pull request now and if everything goes well then the extension should show up in the extensions manager tomorrow.

A few notes for future improvements:
- On Liver tab, make Segment CT Liver effect easier to find. You can set the order of effects (effectNameOrder) on the segment editor widget so that Segment CT Liver is the first in the list. You can even list those effects that you think users should see there and hide the rest (unorderedEffectsVisible) to keep the GUI simpler overall.
- You may want to hide the Segment CT Liver effect in other workflow steps.
- We'll integrate a big improvement of markups today. It allows you to create a list of markup points with undefined position and during point placement always the next undefined point will be offered for placement. This may simplify the bookkeeping in your module, but there is also a chance that some of these features will interfere with how you implemented your module. Let us know on discourse.slicer.org if you run into any issues.
- I had trouble following the point vessel point placement. I just don't have the anatomical knowledge. It would be very helpful to include a sketch (something like [this](https://pubs.rsna.org/cms/10.1148/radiographics.22.5.g02se161063/asset/images/medium/g02se16c3b.jpeg)) of the vessel tree with the points marked on it (one or few pictures for the portal veins and IVC veins)

**Comment by Thibault-Pelletier** [comment]
Hi @lassoan,
Thank you very much for the merge and your feedback on using the plugin. I will add your suggestions to our backlog.

I will also have a look at the markups improvement when the new preview version is built and let you know how it goes.

**Pull request merged**
