### PR TITLE
4.8

### PR DESCRIPTION
**Pull request by idhamari**
Adding SlicerCochlea

### CODE REVIEW

**Comment by pieper** [comment]
No, that's not right - just add your own file 😄

**Comment by idhamari** [comment]
How should I do this? shall I create a new fork from the 4.8 branches?

**Comment by pieper** [comment]
You can just check out the 4.8 branch of the main repo, add your file and then push to a 4.8 branch on your repo, then do the pull request from your 4.8 to the main 4.8 with just the added file.

**Comment by idhamari** [comment]
ok, I will try this!

**Comment by idhamari** [comment]
done! 

please delete this request!

**Comment by pieper** [comment]
👍

**Pull request closed without merging**
