### PR TITLE
add Multi-LevelRegistration

### PR DESCRIPTION
**Pull request by emily-hammond**
New extension that repeatedly performs rigid registration at multiple levels beginning at the global image and focusing in on a specific region of interest.

### CODE REVIEW

**Comment by jcfr** [comment]
@emily-hammond  Thanks for your contribution

Before we can integrate, you would have to make sure your extension has a CMakeLists.txt at the top level, otherwise the build server will not be able to build and package.

Consider also providing an icon and valid screenshot urls

**Comment by emily-hammond** [comment]
I have made the appropriate changes. Let me know if there are still issues I must resolve.

**Comment by emily-hammond** [comment]
@jcfr Sorry this took so long. Just checked and confirmed that the appropriate changes have been made. I have made the extension it's own repository and added screenshots/urls

**Comment by fedorov** [comment]
I am not sure why this was not merged earlier, sorry about that.

**Pull request merged**
