### PR TITLE
ENH: Add ShapeVariationAnalyzer extension

### PR DESCRIPTION
**Pull request by pdedumast**

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for the contribution, to help potential better understand the purpose of this extension. 

I suggest to:
* [ ] Update the reference to the homepage and/or create the [corresponding wikipage](http://slicer.org/slicerWiki/index.php/Documentation/Nightly/Extensions/ShapeViarationAnalyzer)
* [ ] associated a valid icon
* [ ] Remove this invalid screenshot url `https://www.slicer.org/w/index.php?title=Special:Upload&wpDestFile=ShapeVariationAnalyzer_Logo.png`

After updating [the CMakeLists](https://github.com/DCBIA-OrthoLab/ShapeVariationAnalyzer/blob/6e8a812a2f828c81833ad18b75ef934ddde7fdf5/CMakeLists.txt#L7-L12) with valid metatdata, the description file can be generated in the build directory.

Using the extension wizard to contribute the updated description file is also an option.

It would also be neat to provide a [screenshot](https://www.slicer.org/wiki/File:FullView_ShapeVariationAnalyzer.png) including visualization of shapes ...

Reading the README file, it is mentioned that `extensions uses TensorFlow` .. what are the requirement to have a working extension ?

**Comment by pdedumast** [comment]
I updated the metadata and screenshots that should all be correct now. 

Regarding TensorFlow, I found a way to create a virtualenv when launching the extension for the first time, and install TensorFlow in it using pip. There is no specific requirement to have a working extension.

**Comment by jcfr** [comment]
Thanks.

> I found a way to create a virtualenv when launching the extension for the first time, and install TensorFlow in it using pip.

Nice.  Well done, look like few minor tweaks and should be good to do.

The good news is that few weeks ago we integrated pip directly in Slicer.

* [ ] It means the following code (that wouldn't work (by default) on windows because of `bash` requirement) can be removed: https://github.com/DCBIA-OrthoLab/ShapeVariationAnalyzer/blob/28d242fe83f64445013454c907dbf3f934aeba25/src/ShapeVariationAnalyzer/ShapeVariationAnalyzer.py#L1425

* [ ] Similarly `source` used [here](https://github.com/DCBIA-OrthoLab/ShapeVariationAnalyzer/blob/28d242fe83f64445013454c907dbf3f934aeba25/src/ShapeVariationAnalyzer/ShapeVariationAnalyzer.py#L1470) is not available on windows.

* [ ] An alternative would be to add a `External_python-tensorflow.py` similar to what is done here: https://github.com/Radiomics/SlicerRadiomics/blob/master/SuperBuild/External_python-pyradiomics.cmake

* [ ] `findWidget` used [here](https://github.com/DCBIA-OrthoLab/ShapeVariationAnalyzer/blob/28d242fe83f64445013454c907dbf3f934aeba25/src/ShapeVariationAnalyzer/ShapeVariationAnalyzer.py#L1522) can be removed. `slicer.util.findChildren` (or `slicer.util.findChild`) can be used instead. See [here](https://github.com/Slicer/Slicer/blob/ccf66718aa15fc3a95df098cd629464d62ecfbd9/Base/Python/slicer/util.py#L157)

* [ ] for UI loading [here](https://github.com/DCBIA-OrthoLab/ShapeVariationAnalyzer/blob/28d242fe83f64445013454c907dbf3f934aeba25/src/ShapeVariationAnalyzer/ShapeVariationAnalyzer.py#L76-L88), I suggest to make use of `slicer.util.loadUi`

* [ ] prefer using `print` as a function instead of statement. It will facilitate the transition to python 3. `print("something")` instead of `print "something"`

* [ ] I suggest to add documentation of function as docstring instead of comments. For example, see [here](https://github.com/Slicer/Slicer/blob/ccf66718aa15fc3a95df098cd629464d62ecfbd9/Base/Python/slicer/util.py#L392-L400)

* [ ] some of the ivar are not written in english (e.g `fichier`)

It would also suggest to add some basic self tests. (download some sample data, train a model, etc ... )

Addressing these issues will facilitate the maintenance of the code and facilitate its transition to Qt5 and python3.

**Comment by lassoan** [comment]
Majority of Slicer users are on Windows, so it is important to make all submitted extensions work on this operating system, but as a general rule, all extension should run on Windows, Linux, and Mac. If we started accepting extensions that work only on selected operating systems it would fragment our user base.

It should be easy to add a simple test that checks that all components are properly set up. I can help with testing/troubleshooting on Windows. Let me know if you need help.

**Comment by pdedumast** [comment]
Thanks for the feedbacks! 

I made few changes as suggested above by JC. They are available only in [my repository](https://github.com/pdedumast/ShapeVariationAnalyzer) for now, and not yet on the DCBIA-OrthoLab one.

I wasn't able to fix the installation for the 2 following points:
> Similarly source used here is not available on windows.
> 
>  An alternative would be to add a External_python-tensorflow.py similar to what is done here: https://github.com/Radiomics/SlicerRadiomics/blob/master/SuperBuild/External_python-pyradiomics.cmake

Regarding the activation of the virtualenv with `source`, I found the corresponding command to do it on Windows. (`path-to-env/Scripts/activate` instead of `source path-to-env/bin/activate`). I couldn't try it yet (reason below), but it should be good.

The problem I am facing now is to install virtualenv on Windows using pip, due to permission denied. 
I'm not sure I well understand the point of adding a `External_python-tensorflow.py`. 
Is it to avoid all the code for the [virtualenv installation and setup](https://github.com/pdedumast/ShapeVariationAnalyzer/blob/master/src/ShapeVariationAnalyzer/ShapeVariationAnalyzer.py#L1434-L1521), and to do it only once, when the extension is installed?
Is this something that can solve the permission problem on Windows?

Thank you for your help!

**Comment by pdedumast** [comment]
Hello, 

I haven't heard back from you about Windows installation. Since this time, we've been working on the possibility to run the independent processes as CLI. 
To do so, we moved the installation code into this [file](https://github.com/pdedumast/ShapeVariationAnalyzer/blob/master/src/ShapeVariationAnalyzer/Wrapper/envTensorFlowWrapper.py)

Do you have any advice about the Windows installation of virtualenv? 

Thanks!

**Comment by lassoan** [comment]
I've tried to build this on Windows but got the following error:

```
CMake Error at src/CMakeLists.txt:2 (add_subdirectory):
  The source directory

    C:/D/ShapeVariationAnalyzer/src/CLI/SurfaceFeaturesExtractor

  does not contain a CMakeLists.txt file.
```

Could you please add the files as regular files in the directory instead of referring to another repository?

**Comment by lassoan** [comment]
I continued the build attempt by copying the files manually from the remote module.
Build is then failed due to dirent.h not being available on Windows.
Probably the best would be to avoid depending on dirent.h (and maybe use kwsys instead, as kwsys is already bundled with ITK), or include a Windows implementation.

I could make the build succeed by copying this file into src\CLI\SurfaceFeaturesExtractor: https://raw.githubusercontent.com/tronkko/dirent/master/include/dirent.h

**Comment by lassoan** [comment]
After making the above changes, building and packaging is successful.

ShapeVariationAnalyzer module shows up in the module list but fails with this error:

```
Traceback (most recent call last):
  File "C:/Users/msliv/AppData/Roaming/NA-MIC/Extensions-26035/ShapeVariationAnalyzer/lib/Slicer-4.7/qt-scripted-modules/ShapeVariationAnalyzer.py", line 51, in setup
    self.logic = ShapeVariationAnalyzerLogic(self)
  File "C:/Users/msliv/AppData/Roaming/NA-MIC/Extensions-26035/ShapeVariationAnalyzer/lib/Slicer-4.7/qt-scripted-modules/ShapeVariationAnalyzer.py", line 1503, in __init__
    fichier = open(google_init, "w")
IOError: [Errno 2] No such file or directory: u'C:/Users/msliv/AppData/Local/Temp/Slicer\\env-tensorflow\\lib\\python2.7\\site-packages\\google\\__init__.py'
```

**Comment by lassoan** [comment]
By default, Slicer is installed in C:\Program Files\..., which can be only modified with administrator access. Run Slicer as administrator may help with permission issues.

**Comment by pdedumast** [comment]
Thanks for following up! 

I've replaced the git submodule SurfaceFeaturesExtractor by the real files, and included an alternative to dirent.h on Windows system. (https://github.com/pdedumast/ShapeVariationAnalyzer)

For a common user who doesn't have access to an admin account on his machine, there won't be any way to use this extension?

**Comment by lassoan** [comment]
If you don't have rights to install any application then you won't be able to install Slicer. If you do, then you should be able to install Slicer the same way as any dependencies, such as Python, Anaconda, or Docker.

**Comment by pdedumast** [comment]
That's right. 
In my case, I am working on the University's machine. IT service gave permission to install Slicer, but not for permanent use. I assume that the utilization of Slicer is similar for a lot of users.

I think I've fixed the error you've got with google/__init__.py, but can't test it yet, as I don't have admin rights.
Considering this, what's missing for this extension to be available?

**Comment by bpaniagua** [comment]
@lassoan @jcfr, could you please review @pdedumast PR and let her know what else is needed. This work is time sensitive as we are about to submit a request to renew our work.
Thank you!

**Comment by lassoan** [comment]
@pdedumast Have you been able to test it on Windows? I may try to find some time to test this tomorrow, but the best would be if you could try it yourself (and make any fixes if needed).

**Comment by lassoan** [comment]
@bpaniagua If it's important to make this extension show up for reporting/administrative reasons then it should not be a problem, but for to make the extension useful to users it should be functional on all platforms. You can ask users to install download&prerequisite software manually if that's simpler than implementing an automatic mechanism for that.

**Comment by ClementMirabel** [comment]
@pdedumast and I tried to solve that issue on a Windows machine with admin permissions. 
Basically, we corrected all the path related issues and were able to automatically create a virutalenv and install dependencies.
But all those corrections just led us to a big technologic issue: On Windows, Tensorflow can only be installed with Python 3.5.x. (https://www.tensorflow.org/install/install_windows) As the virutalenv creation is done by SlicerPython, which is Python 2.7.x, we just can't use Tensorflow in Slicer on Windows for now.

We previously moved all the installation process in a wrapper for the use of the neural network only, so the other features of the module (compute group average, preprocess data, create files for the network, ..) are working fine on Windows.
One option can be to pop-up a window for Windows users, saying that this feature is not available for now and redirect them to the other Slicer extension we created in our Lab, which can compute remotely any Slicer CLI.

Do you have any other suggestions?

**Comment by fedorov** [comment]
Why don't you just have your component that requires Tensorflow in a docker container with all the prerequisites, and communicate to the Slicer application via files?

You could even take it one step further and make your component accessible from the [DeepInfer](http://www.deepinfer.org/) extension to (potentially) broaden the user reach.

**Comment by ClementMirabel** [comment]
This solution has already been mentioned in the developer list (http://slicer-devel-archive.65872.n3.nabble.com/Importing-external-library-TensorFlow-into-Slicer-td4038362.html) but as said, installing Docker can be tough on some configurations. 

I have to say that most of the user interested in the tools we are developing in the DCBIA-Lab are for clinicians, with for some of them absolutely no computer science knowledge.

**Comment by fedorov** [comment]
It can be, but it can be a good compromise, considering the (lack of too many) options. Or it can be

**Comment by pieper** [comment]
@jcfr has reported that python3 support is in the works for Slicer so hopefully this will ease the problem.

**Comment by bpaniagua** [comment]
@fedorov why was this PR closed?

**Comment by fedorov** [comment]
I am sorry, it was a mistake! I don't know how it happened. Really sorry.

**Comment by jcfr** [comment]
> has reported that python3 support is in the works for Slicer so hopefully this will ease the problem.

Indeed, the order for major updates is as follow:

1. Qt5  and VTK8  (we should have both integrated in a month or so)
2. Python 3: No timeline yet. (Ideally in the next 4 to 5 months)

**Comment by jcfr** [comment]
Python can now easily be installed with on windows, linux and macosx.

On windows, it may be reasonable to ask your user to install tensorflow within a python explicitly installed on windows.

For example, one windows, you could use this one liner (tested on Windows 7) to install the official python, pip and virtual env: http://scikit-ci-addons.readthedocs.io/en/latest/addons.html#install-python-36-x64-ps1

For more details, see http://python-guide-pt-br.readthedocs.io/en/latest/

**Comment by ClementMirabel** [comment]
**_Good news:_** 

- Based on @jcfr answer, we adapted a powershell command to install Python3, pip and virtualenv on user's machine as a first step. This only requires to Run Slicer as admin the first time the training button is clicked and then it works fine.
So, the virutalenv is now created with Python3, so we were able to install tensorflow and run the neural network on a Windows machine. 

- The make package sometimes fails because it builds ComputeMeanLib before ComputeMean, but the packaging is ok on Windows too now.


**_Bad news/need help:_**

- We wanted to try if the fixes had some influence on the Unix version. Packaging is doing ok but when trying to use the CLIs, it fails and return that kind of error:

> dyld: Library not loaded: @rpath/lib/Slicer-4.7/libitkhdf5_cpp_debug.1.dylib

So, I cheked with `otool`:
```
otool -L /Users/mirclem/Desktop/work/Slicer-Extensions/ShapeVariationAnalyzer-build/_CPack_Packages/Darwin/TGZ/d140149-macosx-amd64-ShapeVariationAnalyzer-gitb423a6e-2017-06-16/Slicer.app/Contents/Extensions-d140149/ShapeVariationAnalyzer/lib/Slicer-4.7/hidden-cli-modules/computemean
/Users/mirclem/Desktop/work/Slicer-Extensions/ShapeVariationAnalyzer-build/_CPack_Packages/Darwin/TGZ/d140149-macosx-amd64-ShapeVariationAnalyzer-gitb423a6e-2017-06-16/Slicer.app/Contents/Extensions-d140149/ShapeVariationAnalyzer/lib/Slicer-4.7/hidden-cli-modules/computemean:
	@rpath/lib/Slicer-4.7/libITKFactoryRegistration.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/lib/Slicer-4.7/libITKIOGDCM-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libitkgdcmMSFF-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libitkgdcmDICT-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libitkgdcmIOD-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKEXPAT-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libitkgdcmDSED-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libitkgdcmCommon-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKIOGIPL-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKIOJPEG-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKIOLSM-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKIOTIFF-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libitktiff-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libitkjpeg-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKIOMINC-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libitkminc2-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKIOMRC-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKIOMeta-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKMetaIO-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKIONIFTI-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKniftiio-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKznz-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKIONRRD-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKNrrdIO-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKIOPNG-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libitkpng-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKIOStimulate-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKIOTransformHDF5-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libitkhdf5_cpp_debug.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libitkhdf5_debug.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKIOTransformInsightLegacy-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKIOTransformMatlab-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKIOTransformBase-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKTransformFactory-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKTransform-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKIOVTK-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libitkMGHIO-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKIOImageBase-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKCommon-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libitkdouble-conversion-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libitksys-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libITKVNLInstantiation-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libitkvnl_algo-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libitkvnl-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libitkv3p_netlib-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libitknetlib-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	@rpath/lib/Slicer-4.7/libitkvcl-4.12.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)


```
```
otool -l /Users/mirclem/Desktop/work/Slicer-Extensions/ShapeVariationAnalyzer-build/_CPack_Packages/Darwin/TGZ/d140149-macosx-amd64-ShapeVariationAnalyzer-gitb423a6e-2017-06-16/Slicer.app/Contents/Extensions-d140149/ShapeVariationAnalyzer/lib/Slicer-4.7/hidden-cli-modules/computemean | grep -A 3 LC_RPATH | grep path
          path @loader_path/../../../ (offset 12)
          path @loader_path/../../../../../ (offset 12)
          path /Users/mirclem/Applications/Slicer/build/Slicer-build/teem-build/bin (offset 12)
          path /Users/mirclem/Applications/Slicer/build/Slicer-build/qRestAPI-build (offset 12)
```

That seems ok to me. 

The CLI part was working 3 days ago, but we can't find which modifications could fail. 
Do you have any thoughts?

**Comment by pdedumast** [comment]
Hello! 

All the linking errors are now fixed! The solution was to double-check the settings of CMake variables and reorganize the repository. 

Now, everything works correctly on both Unix and Windows systems!

**Comment by bpaniagua** [comment]
@pdedumast @ClementMirabel Great job getting all these problems solved!

@lassoan @jcfr could you please revise their changes and check what else is needed? Still being pressed by a renewal deadline.

Thank you!!

**Pull request merged**
