### PR TITLE
Add SlicerRegularizedFastMarching extension

### PR DESCRIPTION
**Pull request by lrisser**
[To make sure users can find your extension, understand what it is intended for and how to use it, please complete the checklist below. You do not need to complete all the item by the time you submit the pull request, but most likely the changes will only be merged if all the tasks are done. See more information about the submission process here: https://slicer.readthedocs.io/en/latest/developer_guide/extensions.html]

- [X ] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [X ] Repository name is Slicer+ExtensionName
- [ X] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [X ] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [X ] Any known related patents must be mentioned in the extension description.
- [X ] If source code license is more restrictive for users than BSD, MIT, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [X ] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [ X] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://github.com/user/project/raw/main/path/to/icon.png)
- [X ] Screenshot URLs (screenshoturls) are correct, contains at least one
- [X ] Homepage URL points to valid webpage containing the following:
  - [ X] Extension name
  - [X ] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [X ] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [X ] Description of contained modules: at one sentence for each module
  - [X ] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [ X] Publication: link to publication and/or to PubMed reference (if available)
  - [ X] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/master/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [ X] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)

### CODE REVIEW

**Comment by lassoan** [comment]
Thank you for your submission. This is a nice example of implementing a segmentation workflow and quantification in a single module for a specific use case.

I had to reorganize the source files to allow the extension package to build - see this pull request: https://github.com/AldrickF/SlicerRegularizedFastMarching/pull/1. If you merge it then the extension should be ready to be added to the extension index!

There are a lot of small things that could be improved in term of usability, speed, and coding style. You may get some inspiration from this lung segmentation module: https://github.com/rbumm/SlicerLungCTAnalyzer

**Comment by lassoan** [comment]
@lrisser I had to reorganize the source files to allow the extension package to build - see this pull request: AldrickF/SlicerRegularizedFastMarching#1. If you merge this pull request (takes two clicks from you) then the extension should be ready to be added to the extension index!

**Comment by lassoan** [comment]
The [pull request](https://github.com/nicholasnguyennc/SlicerVolumeProjection) is still open. Without you merging it (by two clicks) it is not possible to add this s4ext file to the extensions manager. I close this issue now to make sure that active submissions are not lost in the noise, but @lrisser feel free to reopen anytime if you have time to merge the pull request.

**Comment by lrisser** [comment]
Dear Andras,

thank you for your messages! I have now merged the commits and believe 
that everything should be OK (I admit that I'm not as familiar with the 
use of github tools as Aldrick Faure, who developed the code).  Please, 
do not hesitate to go back to me if something is still missing.

best regards, thanks again,
Laurent



Le 2021-05-28 17:21, Andras Lasso a écrit :

**Comment by lassoan** [comment]
The extension is now added to the extensions index. Check out the Extensions Manager in the latest Slicer Preview Release - it should appear tomorrow or the day after. If it does not then check the [dashboard](https://slicer.cdash.org/index.php?project=SlicerPreview) for errors.

**Pull request merged**
