### PR TITLE
add auto3dgm.s4ext

### PR DESCRIPTION
**Pull request by hkirvesl**
- [X] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [X] Repository name is Slicer+ExtensionName
- [X] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click "Manage topics" on your repository's main page, on the left, near the top (just below the repository description). To learn more about topics, read https://help.github.com/en/articles/about-topics
- [ ] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [X] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [X] Extension icon URL is correct
- [X] Screenshot URLs (screenshoturls) are correct, contains at least one
- [X] Homepage URL points to valid webpage containing the following:
  - [X] Extension name
  - [X] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [X] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [X] Description of contained modules: at one sentence for each module
  - [X] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [X] Publication: link to publication and/or to PubMed reference (if available)
  - [X] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/master/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work.
Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.

### CODE REVIEW

**Comment by lassoan** [comment]
Thanks a lot for this contribution. It will be great to have this tool available in 3D Slicer!

There are a couple of things to sort out before adding the new extension:
- [ ] Fix package and build errors by merging this pull request: https://github.com/ToothAndClaw/SlicerAuto3dgm/pull/1
- [ ] Error occurred when I've tried to run the algorithm by following instructions on the "how-to-use" page. When I clicked "Run all steps" button, I got this error:

```
Traceback (most recent call last):
  File "C:/D/SlicerAuto3dgm_R/lib/Slicer-4.11/qt-scripted-modules/Auto3dgm.py", line 262, in allStepsButtonOnLoad
    Auto3dgmLogic.runAll(self.Auto3dgmData, self.reflectionCheckBox.checked)
  File "C:/D/SlicerAuto3dgm_R/lib/Slicer-4.11/qt-scripted-modules/Auto3dgm.py", line 446, in runAll
    Auto3dgmLogic.subsample(Auto3dgmData,[Auto3dgmData.phase1SampledPoints,Auto3dgmData.phase2SampledPoints],Auto3dgmData.datasetCollection.datasets[0])
AttributeError: 'NoneType' object has no attribute 'datasets'
```

- [ ] Fix landing page (https://toothandclaw.github.io/SlicerAuto3dgm/) it now shows a link (not even clickable) to the real page (https://toothandclaw.github.io/). Having the actual documentation there would be much better (or at least an automatic redirect with an optional clickable link).
- [ ] Add download link to "downsampled gorilla skull dataset" (referenced on https://toothandclaw.github.io/how-to-use/)?
- [ ] Add a tutorial sample data set that is not 6GB (few hundred megabytes are OK). I have quite good internet connection but still takes a while to download it from box (and did not succeed the first time). You can lose potential users if you force the to go through such inconveniences.
- [ ] Extension description is insufficient ("The auto3dgm Slicer Extension")
- [ ] Quality of the current extension icon (http://www2.stat.duke.edu/~hmk16/auto3dgm/auto3dgmlogo.png) is highly misleading, it discourages users from considering trying the extension, it does not relect quality of the extension and its documentation
- [ ] Add screenshot that is more representative of what the module does (http://www2.stat.duke.edu/~hmk16/auto3dgm/auto3dgmscreenshot.png shows and empty module GUI)
- [ ] Update installation instructions at https://toothandclaw.github.io/installations/ (you can keep the manual installation instructions at the bottom of the page, but by default advise users to install it in Slicer, using Extension Manager)

**Comment by sshanshans** [comment]
Hi Andras, thank you so much for your feedback during the first round of revision. The changes you made/suggested have greatly improved the quality of our code. We have indicated the changes we have made according to your previous comments listed as follows. 

> 
> * [x]  Fix package and build errors by merging this pull request: [ToothAndClaw/SlicerAuto3dgm#1](https://github.com/ToothAndClaw/SlicerAuto3dgm/pull/1)
> * [x]  Error occurred when I've tried to run the algorithm by following instructions on the "how-to-use" page. When I clicked "Run all steps" button, I got this error:
> 
> ```
> Traceback (most recent call last):
>   File "C:/D/SlicerAuto3dgm_R/lib/Slicer-4.11/qt-scripted-modules/Auto3dgm.py", line 262, in allStepsButtonOnLoad
>     Auto3dgmLogic.runAll(self.Auto3dgmData, self.reflectionCheckBox.checked)
>   File "C:/D/SlicerAuto3dgm_R/lib/Slicer-4.11/qt-scripted-modules/Auto3dgm.py", line 446, in runAll
>     Auto3dgmLogic.subsample(Auto3dgmData,[Auto3dgmData.phase1SampledPoints,Auto3dgmData.phase2SampledPoints],Auto3dgmData.datasetCollection.datasets[0])
> AttributeError: 'NoneType' object has no attribute 'datasets'
> ```
> 
Did you click the "Load Data" button after you choose the input and output folders? We have updated our tutorials on the webpage to make sure it is clear for the users as well. 
> 
> * [x]  Fix landing page (https://toothandclaw.github.io/SlicerAuto3dgm/) it now shows a link (not even clickable) to the real page (https://toothandclaw.github.io/). Having the actual documentation there would be much better (or at least an automatic redirect with an optional clickable link).
> * [x]  Add download link to "downsampled gorilla skull dataset" (referenced on https://toothandclaw.github.io/how-to-use/)?
> * [x]  Add a tutorial sample data set that is not 6GB (few hundred megabytes are OK). I have quite good internet connection but still takes a while to download it from box (and did not succeed the first time). You can lose potential users if you force the to go through such inconveniences.
>
Thanks for pointing this out! We have now added on the tutorial page a link to a much smaller sample data. 
>
> * [x]  Extension description is insufficient ("The auto3dgm Slicer Extension")
> * [x]  Quality of the current extension icon (http://www2.stat.duke.edu/~hmk16/auto3dgm/auto3dgmlogo.png) is highly misleading, it discourages users from considering trying the extension, it does not relect quality of the extension and its documentation
> * [x]  Add screenshot that is more representative of what the module does (http://www2.stat.duke.edu/~hmk16/auto3dgm/auto3dgmscreenshot.png shows and empty module GUI)
> * [x]  Update installation instructions at https://toothandclaw.github.io/installations/ (you can keep the manual installation instructions at the bottom of the page, but by default advise users to install it in Slicer, using Extension Manager)

**Comment by sshanshans** [comment]
Hi @lassoan -- it has been a while since we heard from you. We have finished the changes as you suggested during the last round of review. Could you kindly let us know what would be the next step for us to add the auto3dgm extension to Slicer? 

Thank you so much for your time and help!

**Comment by lassoan** [comment]
Thanks for all your work on this and sorry for the delayed review. I have reviewed your changes and they all look good, so I add your extension to the extensions index now.

I have just two minor findings:
- On https://toothandclaw.github.io/installations/ page there is no need for `pip_install('mosek')`, the module takes care of this automatically now (https://github.com/ToothAndClaw/SlicerAuto3dgm/blob/31656c120451e77b827007cd84587a7e07bd8503/Auto3dgm/Auto3dgm.py#L69-L75)
- Typo at https://toothandclaw.github.io/how-to-use/ : specifiy

I have also noticed that you are using a web browser to display models, which can be a bit clunky and limited compared to viewing models directly in Slicer. You can show a "gallery" layout by copy-pasting this few ten lines of Python script into your module:
https://www.slicer.org/wiki/Documentation/Nightly/ScriptRepository#Show_comparison_view_of_all_model_files_a_folder

image

**Comment by lassoan** [comment]
The extension is now added to the index. Check out the [dashboard](http://slicer.cdash.org/index.php?project=SlicerPreview) tomorrow to see if it has built and packaged correctly on all platforms.

Thank you for your contribution!

**Comment by sshanshans** [comment]
Hi @lassoan, thank you so much for approving our package to be added as an extension in Slicer, and thanks so much for the feedback as well! I have fixed the typos in the tutorial webpage as you suggested, and will look into the gallery view option in Slicer. We shall be able to update the auto3dgm package with the gallery view option in slicer very soon. Thanks again for your invaluable feedback!

**Comment by sshanshans** [comment]
Hi @lassoan, we are so happy to see that auto3dgm is now available to download from the Slicer extension catalogue. However, when we tried to test the package today, we found the following error: 

> `
Traceback (most recent call last):
  File "/Applications/Slicer.app/Contents/Extensions-29130/Auto3dgm/lib/Slicer-4.11/qt-scripted-modules/Auto3dgm.py", line 189, in onLoad
    self.Auto3dgmData.datasetCollection=Auto3dgmLogic.createDataset(self.meshFolder)
  File "/Applications/Slicer.app/Contents/Extensions-29130/Auto3dgm/lib/Slicer-4.11/qt-scripted-modules/Auto3dgm.py", line 455, in createDataset
    from auto3dgm_nazar.dataset.datasetfactory import DatasetFactory
ModuleNotFoundError: No module named 'auto3dgm_nazar'
`
I have checked that the source code contains the 'auto3dgm_nazar' module, and the package works alright when installed directly with GitHub code. But the dowloaded version doesn't seem to have 'auto3dgm_nazar' in any of its subfolder.

Screen Shot 2020-06-12 at 10 51 05 PM

Could you give me some insights about what went wrong here? Also, any advice on how to fix this on our end would be greatly appreciated!

Thanks so much for your help!

**Comment by lassoan** [comment]
You need to list all files that you want to include in the package in MODULE_PYTHON_SCRIPTS variable in the CMakeLists.txt file.

I've also found that you have accidentally added this file to revision control, it should be removed: https://github.com/ToothAndClaw/SlicerAuto3dgm/tree/master/Auto3dgm/__pycache__

**Comment by sshanshans** [comment]
Thank you so much @lassoan  for your reply! Also, thank you so much @jamesobutler for helping us fix the error! It has been tremendously helpful. I have merged the pull request  [ToothAndClaw/SlicerAuto3dgm#2](https://github.com/ToothAndClaw/SlicerAuto3dgm/pull/2). 

Would the package be rebuilt automatically? Shall I do another pull request to Slicer/ExtentionsIndex to update the package?

Thanks again for your help!

**Comment by lassoan** [comment]
Since you have "scmrevision master" in the submitted s4ext file, there is no need to do anything - the nightly build always uses the latest master.

**Comment by sshanshans** [comment]
@lassoan Got it! Thank you so much again for your help!

**Pull request merged**
