### PR TITLE
Add tomaat

### PR DESCRIPTION
**Pull request by faustomilletari**
Add TOMAAT extension. This extension aims at providing cloud-based DL-based segmentation capabilities into Slicer.

### CODE REVIEW

**Comment by fedorov** [comment]
Thank you for your contribution!

At the basic level of checks, we usually require to have at least some basic documentation. There is none currently, from what I can see. Can you address this?

**Comment by faustomilletari** [comment]
absolutely! I will add more to the readme of the repository "tomaat-slicer". would that be sufficient?

**Comment by fedorov** [comment]
How about you add documentation as you planned, and then we will review what you have there and decide? I don't think there is any formal description of what is required from documentation.

While you are working to finalize your extension and documentation, I am going to rename the PR name to have "WIP" (work in progress) prefix. Once you feel you are done and everything is ready for review, please rename it back to remove WIP to signal developers it is ready for the review.

**Comment by faustomilletari** [comment]
Hello,

thanks for you help. I have just added a readme in the repository of TOMAAT slicer with a schematic representation of what we are trying to do and also a description of the interfaces used to communicate with remote hosts etc.

Thanks for your feedback and your help!

**Comment by fedorov** [comment]
Do you have a public server instance, or perhaps another app to run that server locally, and some example DL tools running on that server showing how this can be put to work?

If you are distributing this to set the stage for the next steps of what you want to do, or to support your internal app server, what you share makes sense. 

But I don't think as is (based on the documentation) this extension would be easy to put to work for the end user (someone who wants to try TOMAAT-interfaced tools on their data) or to the developer (someone who has a DL tool they want to integrate into TOMAAT).

Either way is fine, I have no objections if this is integrated, just wanted to provide my perspective. Let me know what you think.

**Comment by faustomilletari** [comment]
Hello,
right now I am trying to open source 
1) this extension (and also, separately, a CLI to run batch jobs in a similar way)
2) a python module that provides TOMAAT server: TOMAAT server will be just a package that wraps dl models and makes them accessible through HTTP using this interface. Ideally an user would put all of that in a docker container and access it either a) directly, specifying the URL of the server that hosts it that can be local or remote,  or b) announce it (needs api key I provide to them) and have not only themselves but anyone out there be able to reach the server and get prediction
3) The announcement service code itself. so that they can run their own announcement service locally in their organization or even on the cloud (they could replace TOMAAT announcement). For this reason nothing is hardcoded (in terms of URLs) in the extension. 

I am planning to commit to this for a while, running the announcement service at least and the website. There is one inference endpoint active right now, but it's on a pretty expensive machine on the cloud that I won't be really able to keep running for too long. I have many friends in organizations though and I work at NVIDIA so I'm fairly sure that I will be able to convince them to run some of this services in their servers with public IP (I'm the author of V-net and my collaborators in Munich are eager to have the work gain even more visibility by deploying it on the cloud. right now we have even more modalities we segment, so we think about having a collection of endpoints which get all executed in the end in one server that is slower (because at every execution loads the model from scratch and then unloads it) but can do many many different inferences.) all of this is possible with this infrastructure that is starting right now but I think will evolve much especially server side.

**Comment by fedorov** [comment]
This helps in understanding the bigger picture, thank you! Look forward to it! Thanks again for your contribution, I am glad you are joining the community of Slicer extension developers - welcome!

**Comment by faustomilletari** [comment]
The only thing we need to confirm is the ability to run on Slicer > 4.8 and Nightly build the following code snippet.

It works well on slicer = 4.8, but what about nightly?

```
try:
  import requests
except:
  import pip
  pip.main(['install','requests'])
  import requests
  pass
```

**Comment by faustomilletari** [comment]
thank you! I wish you a nice day and happy holidays. this helps a lot the effort of trying to make this project real!

**Comment by fedorov** [comment]
Oh, one (very important) thing I forgot - can you please add the license to the TOMAAT repository?

**Comment by faustomilletari** [comment]
yes. Will do right now!

**Comment by fedorov** [comment]
> The only thing we need to confirm is the ability to run on Slicer > 4.8 and Nightly build the following code snippet.

I tried it, and it runs in the nightly I have installed on my machine.

**Comment by fedorov** [comment]
By the way, in case you are not aware, we are going to have our 27th Project week event in Boston this January. To state the obvious, many people will be doing DL there and should be interested in this work. You are most welcome to join! 

https://na-mic.github.io/ProjectWeek/PW27_2018_Boston/

**Comment by faustomilletari** [comment]
Thanks for the info. I think it's doable for me to come there.

**Comment by pieper** [comment]
Hi @faustomilletari welcome and thanks for the new extension 👍   I saw that you had the demo at RSNA but didn't get a chance to catch up with you.  Hope you can join us at Project Week.

**Comment by fedorov** [comment]
I've just installed it, used the discovery server, and ran it on a (public) dataset I had handy. The segmentation was not perfect, but I could do all of the above (and below) in just minutes (segmentation itself in seconds). Nice work!

Did you consider applying the segmentation threshold on the client?

image

**Comment by faustomilletari** [comment]
Yes, I will shift that thresholding operation to client soon. I’m not doing that yet just because of my lack of experience with making a smooth image a label etc. I have to develop that part more

The model that runs there is a V-Net which I think can be improved much by the way. This one was trained without really normalizing intensities properly and without some other augmentation techniques I have employed more recently. We can now do 512x512x64 in V-Net which is impressive. The model you got there in the prostate endpoint is 256x256x128 though at 0.5, 0.5, 1 mm resolution I think…

By the way, should I be able to see the extension in the extension manager already? Or will that take time? (I’m running nightly built now).

I hope that through this package both server and client side people will just take their old Tesla k40 cards that are really too slow for anything and put them to predict for the masses using their own models…



Best regards and thanks for the feedback,

Fausto

**Comment by faustomilletari** [comment]
@pieper thanks for writing. I'm currently using some of my personal time in these vacations to make this project happen :) I rewrote most of it and filled the blanks when needed (announcement service etc...) hopefully it will be useful. I will try to get to Boston to meet you guys in person!

**Comment by fedorov** [comment]
> By the way, should I be able to see the extension in the extension manager already? Or will that take time? (I’m running nightly built now).

No, but you don't need it to try it out. You can use nightly binary, and add the path to the folder with TOMAAT.py in `Edit > Application settings > Modules > Additional module paths`. You will see extension after restart (that is what I did to test it).

**Comment by faustomilletari** [comment]
Oh yeah. That’s how I’m doing it right now to develop. Will it be shown in extension manager at a point?


Fausto

**Comment by fedorov** [comment]
No, to appear in the extension manager you need to wait for the next nightly, this is the easiest.

**Pull request merged**
