### PR TITLE
ENH: Add SlicerITKUltrasound extension

### PR DESCRIPTION
**Pull request by thewtex**
Description: Ultrasound image formation, processing, and analysis. Interfaces
built off the ITKUltrasound library.

Contributors: Matt McCormick (Kitware, Inc.), Mark Palmeri (Duke University),
Stephen Aylward (Kitware, Inc.), Jean-Christophe Fillion-Robin (Kitware, Inc.)

CC: @mlp6 @aylward @jcfr

### CODE REVIEW

**Comment by thewtex** [comment]
@pieper @fedorov Thanks for the reviews!

> I am also confused about the documentation. it is very unclear if that is a documentation for the classes, or for the module. Some screenshots, sample datasets, use cases would be very helpful.

Improved documentation on the module screenshots and how to reproduce them has been added here:
  https://github.com/KitwareMedical/SlicerITKUltrasound/commit/36cf0f95c554f7b3af33e90d5f4b77835103538c

> Would be helpful if the relationship to PLUS library was discussed. Does this library/extension provide any improvements over PLUS? Or is this just another way to do things?

Good idea. A link to PLUS was added here, along with an explanation that it complementary -- while PLUS does very well with tracking and synchronization, this focuses on ultrasound image formation with ITK.

  https://github.com/KitwareMedical/SlicerITKUltrasound/commit/6437f75ec2e184d490d9126708ead346176dd7c1

**Comment by fedorov** [comment]
@thewtex thanks for the update!

> while PLUS does very well with tracking and synchronization, this focuses on ultrasound image formation with ITK.

Still not quite sure what are the differences - I used PLUS for image reconstruction, b-mode image formation, hole filling - these are all operations supported by PLUS (see section F. of Lasso A., Heffter T., Rankin A., Pinter C., Ungi T., Fichtinger G. 2014. PLUS: open-source toolkit for ultrasound-guided intervention systems. IEEE transactions on bio-medical engineering 61:2527–2537. DOI: 10.1109/TBME.2014.2322864).

I don't mean to stall the merge, these are just suggestions from a confused user perspective. Feel free to integrate as needed based on your priorities.

**Comment by thewtex** [comment]
@fedorov We are generating and working with new types of images beyond B-Mode images, like Ultrasound Spectroscopy and Acoustic Radiation Force Imaging (ARFI) images, which benefit from being placed in an itk::SpecialCoordinatesImage. In the future, these could also be integrated into PLUS to fuse with trackers and network transmission.

But having this in the Extension Index will help us move toward that goal.

Merging with an eye towards additional improvements in the future :-).

**Comment by jcfr** [comment]
Congrats to @thewtex for his first extension :fireworks: 

Thanks @fedorov @pieper @ihnorton for the review. 

Does the last comment of @thewtex help clarified things ?

**Comment by pieper** [comment]
Yes, the compare and contrast between the features of PLUS and the new
extension make good sense to me.

But I think the lingering confusion about the documentation is that the
documentation pages [1] describe features exposed from the CLI module XML
[2] but that linkage is not obvious at first glance (not to me anyway).
It would maybe be more obvious if there was a screen shot of the CLI
interface so that once could see the Resampling Method option.  I don't
recall if a <string-enumeration> ends up as a radio button group or as a
menu but either way it would make it clear what the documentation is
describing.

Also, now that I look closer the layout of the documentation is confusing.
Starting from the table of contents [3] I think there's one module called
"Scan Conversion" but there's no real description about the inputs and
outputs, only a list of implementation methods.  The only link to
"ScanConvertSliceSeries", the actual module that corresponds to the CLI, is
at the bottom under "Probe Geometries" section (not sure why it's listed
under that heading).

Anyway I hope you can see where the confusion is coming from.  Docs look
nice and very detailed, so I think it's just an organizational issue.

Cheers!
Steve

[1]
https://kitwaremedical.github.io/SlicerITKUltrasoundDoc/Modules/ScanConversion/index.html

[2]
https://github.com/KitwareMedical/SlicerITKUltrasound/blob/master/ScanConvertSliceSeries/ScanConvertSliceSeries.xml

[3] https://kitwaremedical.github.io/SlicerITKUltrasoundDoc/

**Comment by lassoan** [comment]
Relationship with Plus is not defined at this point, they have been mostly independent efforts. We have recently got R01 funding for this with Kitware and others, so I guess one of the first tasks will be to come up with a strategy.

**Comment by thewtex** [comment]
@pieper Thanks for the suggestion. There are three CLI modules that share a common set of options (the resampling methods). A screenshot and additional explanation has been added here:

  https://github.com/KitwareMedical/SlicerITKUltrasound/commit/3e6e117399dd7f3b7d62c90e8f0fee0acf0c6916


@lassoan looking forward to discussing with integration strategies.

**Comment by pieper** [comment]
Aha, I understand better now!

LGTM

**Pull request merged**
