### PR TITLE
Added ModelCropper.s4ext

### PR DESCRIPTION
**Pull request by sebastianandress**
A simple extension allowing to crop a model along a roi annotation. Applied transformations are respected.

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [ ] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/master/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work.
Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.

### CODE REVIEW

**Comment by pieper** [comment]
Nice - thanks for the contribution!

Can you add a License and update the checklist?  We suggest just copying the [Slicer License](https://github.com/Slicer/Slicer/blob/master/License.txt) file if you have no other preference.

It might also be good to think about how this could be integrated with the [SurfaceToolbox](https://github.com/Slicer/SlicerSurfaceToolbox) to make it easier for users to find and use.

**Comment by sebastianandress** [comment]
ok, I added the license by copying the Slicer License.
Sure, it would be also easy to integrate it in the SurfaceToolbox. Is it allowed to just update an existing extension, created by another developer? I couldn't find it on the internet.

**Comment by lassoan** [comment]
Thank you, this will be very useful!

@jcfr @bpaniagua What do you think about adding this module to the revamped surface toolbox extension?

**Comment by bpaniagua** [comment]
👍 Sounds like a great idea!

**Comment by jcfr** [comment]
Thanks for the contribution. 

This could indeed be added as a module in the new [SlicerSurfaceToolbox](https://github.com/Slicer/SlicerSurfaceToolbox) project.

The idea is to have SlicerSurfaceToolbox integrated into the official Slicer distribution, that way feature like model cropping would be available by default without the need to install the extension.

To learn more about the plan for this project, see https://discourse.slicer.org/t/surface-toolbox-revamp/7113

One idea is to have the features available as Python based CLI (see https://github.com/Slicer/SlicerSurfaceToolbox/pull/1#issue-296667888) 

@wilson-ben is currently working on improving the SlicerSurfaceToolbox, after he has made more progress, we will reach out to make some more concrete plan. This is now tracked by https://github.com/Slicer/SlicerSurfaceToolbox/issues/2

**Comment by sebastianandress** [comment]
Thanks for working on the interesting SurfaceToolbox Extension. It's always nice (especially for physicians) to have all tools integrated in one software, and this tool is quite helpful for preparing 3D prints. For myself, it is not too important that the extension is distributed as a standalone in the meantime since I installed it manually, but depending on your workload you can decide how you want to proceed.

**Pull request merged**
