### PR TITLE
ENH: Add new extension - SlicerAugmentator

### PR DESCRIPTION
**Pull request by ciroraggio**
# New extension

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Any known related patents must be mentioned in the extension description.
- [x] LICENSE.txt is present in the repository root. MIT  (https://choosealicense.com/licenses/mit/) or Apache (https://choosealicense.com/licenses/apache-2.0/) license is recommended. If source code license is more restrictive for users than MIT, BSD, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (main, release, ...) instead of a specific git hash to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://raw.githubusercontent.com/user/repo/main/SomeIcon.png)
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [x] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/main/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [x] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)
- Hide unused features in the repository to reduce noise/irrelevant information:
  - [x] Click `Settings` and in repository settings uncheck `Wiki`, `Projects`, and `Discussions` (if they are currently not used)
  - [x] Click the settings icon next to `About` in the top-right corner of the repository main page and uncheck `Releases` and `Packages` (if they are currently not used)

### CODE REVIEW

**Comment by ciroraggio** [comment]
@lassoan @jcfr

**Comment by lassoan** [comment]
- [ ] Extension name: Repository name starting with `Slicer` is good. The extension name should not start with Slicer just because it is a Slicer extension - because then all Slicer extension names would start with Slicer and it would be harder to find anything. If the extension is only expected to augment images then I would recommend to rename the extension to `ImageAugmentator` (or something similar) and rename the repository to `SlicerImageAugmentator`.
- [ ] The extension package is empty, because you have not listed the module in the top-level CMakeLists.txt file.
- [ ] You only include 7 of the 8 .py files of SlicerAugmentatorLib in the package. Is this intentional?
- [ ] No Python package should be installed at the file scope - `slicer.util.pip_install("monai[itk]")` is only allowed to be executed when the user clicks preview or start button. You can have a look at SlicerMONAIAuto3DSeg extension as an example of how to install MONAI.
- [ ] Provide a sample data folder: use public image data; have one example for hierarchical, another one for flat; you can upload them to the github repository as release assets (you can create a release corresponding to any version of the repository, name it TestData, and drag-and-drop the zip file containing the desired directory structure)
- [ ] I'm not sure what "Slicer Preview" refers to. If you mean that to preview in the application then it would be more clear to just use "Preview"
- [ ] I would recommend to remove https://github.com/ciroraggio/SlicerAugmentator/blob/main/docs/changelog.md. Nobody would trust a manually maintained changelog.

I'll provide more feedback once I have a chance to try with the test data you provide.

**Comment by ciroraggio** [comment]
@lassoan Thank you for your feedback. I have made the requested changes, you can also find the sample data associated with the v1.0 release.

**Comment by lassoan** [comment]
Sorry, I've just realized the grammatical error in the name - it should be ImageAugmenter. ImageAugmentor is a recognized variant, too, but "augmenter" word is used [4x more frequently](https://www.oed.com/dictionary/augmentor_n?tab=factsheet#33397195), so ImageAugmenter would be probably a better choice.

**Comment by cpinter** [comment]
> grammatical error

I assumed they wanted to be associated to the TotalSegmentator brand :)

**Comment by ciroraggio** [comment]
That was the idea! Is it a problem to keep the name ImageAugmentator?

**Comment by ciroraggio** [comment]
Sorry, just to avoid misunderstanding and the fourth refactoring, when @cpinter commented I had already changed the repository name and all the code in the develop branch, I was ready to make a new release, so now you will find the repository in a transitional state. I am waiting to hear from you on whether to do the release with the new name or undo the changes in the develop branch and redo the release with the old name.

**Comment by lassoan** [comment]
Considering the huge number of image augmentation libraries, it could make sense to use a grammatical error to obtain a unique name. However, this error is not obviously intentional, so - similarly to TotalSegmentator - people may think that you just have poor language skills. I also don't find this error very original (due to TotalSegmentator) and a bit worried that this could become a trend and people would genuinely think that segmentator, augmentator, registrator, visualizator, quantificator, ... words are acceptable variants.

@pieper @sjh26 what do you think as native English speakers?

**Comment by jamesobutler** [comment]
I’m no English grammar expert, but I speak English as a first language. To try and break down what are the correct terms I have written out the below things:

Noun: Segmentation
Verb(in this situation): Segment (to segment)
Agent Noun that carries out the verb: Segmenter

Noun: Augmentation
Verb(in this situation): Augment (to augment)
Agent Noun that carries out the verb: Augmenter

If the verb ends in -ate, -ct, -it then “or” is used instead of “er”. Investigate -> Investigator

Of course English is a difficult language because there appears to always be an exception to rules, but the general case is what I have posted which I believe applies here in this situation. I always found “Segmentator” to be the incorrect name choice and I would sometimes catch myself writing it as “TotalSegmenter” and then having to rewrite it to match how the author named it so there was no confusion. I never thought more about why it didn’t seem right, but after this exercise it seems to explain why.

**Comment by cpinter** [comment]
> a bit worried that this could become a trend and people would genuinely think that segmentator, augmentator, registrator, visualizator, quantificator, ... words are acceptable variants.

This is a valid concern. I think that strictly speaking, TotalSegmentator is not a grammatical error, because it is not in English but in German. However, the international community speaks English, and it is not so far away from the proper English term that it is obviously in another language and not an error (in Hungarian it could be "TotálisSzegmentáló", obviously not English). That said, TotalSegmentator is now in the terminology of a narrow community, and Augmentator alludes (to me at least) to a connection to TotalSegmentator. The decision is not easy here, but I'd lean towards granting this liberty to the creators if they wish.

**Comment by lassoan** [comment]
@ciroraggio I see that the Python package name that you developed and make available in Slicer via this extension is called [AugmentedDataLoader](https://github.com/ciroraggio/AugmentedDataLoader). A common practice is to use the same name as the Python package name as extension name (repository name has the `Slicer` prefix added).

I would recommend to consider all the comments above and choose a name that you will use as Python package name on PyPI and as extension name in Slicer's Extensions Index. When you update all the names of the repositories, filenames, etc. then let us know here that everything is ready for a final review.

**Comment by ciroraggio** [comment]
Thank you all for your feedback! After reading the various comments, I decided to go ahead with the name "ImageAugmenter" to respect the grammar as suggested. 

@lassoan it would not be correct in my opinion to call it "AugmentedDataLoader" because, yes, the idea for Slicer comes from that project but it does not use that specific dataloader library, designed for a different purpose and it does not even follow the same logic.

I have remade a new release with sample data and updated code. I look forward to new feedback from you!

**Review by lassoan — APPROVED** [review]
OK, thank you. It looks good to me.

**Comment by lassoan** [comment]
A few small things:
- you can remove `slicer.util.pip_install("SimpleITK")` line, because SimpleITK is already bundled with Slicer
- ["Examples" link](https://github.com/ciroraggio/SlicerImageAugmenter/tree/main?tab=readme-ov-file#examples) takes to a nicely written tutorial. I think it would be better to rename the link to "Tutorial"
- Add a sample data download link to the tutorial

**Pull request merged**
