### PR TITLE
remove HoughTransform-CLI 

### PR DESCRIPTION
**Pull request by gpernelle**
houghTransform CLI is not used for the moment and needs to be updated to be compatible with VTK6

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks Guillaume

When you will be working on converting to VTK6, do not hesitate to ask you have any question. It may be as simple as switching `SetInput` with `SetInputData` ...

**Comment by gpernelle** [comment]
Thanks JC, I will try that later if we need this feature again.

**Comment by jcfr** [comment]
Sounds goods.

Do you think you could you also remove the extension from the 4.4 branch ?

Thanks
Jc

On Fri, Jan 9, 2015 at 9:12 AM, Guillaume Pernelle <notifications@github.com
> wrote:

> Thanks JC, I will try that later if we need this feature again.
>
>
> > On 09 Jan 2015, at 07:10, Jean-Christophe Fillion-Robin <
> notifications@github.com> wrote:
> >
> > Thanks Guillaume
> >
> > When you will be working on converting to VTK6, do not hesitate to ask
> you have any question. It may be as simple as switching SetInput with
> SetInputData ...
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/Slicer/ExtensionsIndex/pull/878#issuecomment-69338257>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Slicer/ExtensionsIndex/pull/878#issuecomment-69338460>
> .
>



-- 
+1 919 869 8849

**Comment by gpernelle** [comment]
of course! Let me do it now.

**Pull request merged**
