### PR TITLE
ENH: Add GROUPS extension

### PR DESCRIPTION
**Pull request by allemangD**
- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [ ] Repository name is Slicer+ExtensionName
  - **Since other projects (SlicerSALT) already depend on this, I don't think changing the repository name is appropriate.**
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [ ] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Any known related patents must be mentioned in the extension description.
- [x] If source code license is more restrictive for users than BSD, MIT, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [ ] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://github.com/user/project/raw/main/path/to/icon.png)
  - **There is no existing icon associated with this extension**
- [ ] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [ ] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [ ] Description of contained modules: at one sentence for each module
  - [ ] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [x] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/master/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [x] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)

----

This extension provides the RigidAlignment module, which will be included in the SlicerCMF extension bundle.

See more info here: https://github.com/NIRALUser/RigidAlignment

### CODE REVIEW

**Comment by bpaniagua** [comment]
@allemangD it seems there are some CI problems, do you need any help with this?

**Comment by bpaniagua** [comment]
@jcfr care to comment?

**Comment by lassoan** [comment]
We not enforce "Slicer" as a prefix if the repository can be built by itself or as a Slicer extension. Can this repository built as a standalone library or application or it can only be used as a Slicer extension?

**Comment by jcfr** [comment]
> I started to put together a prototype to illustrate an alternative approach, should be ready in few minutes.

This is ready for review and testing. See https://github.com/DCBIA-OrthoLab/SlicerCMF/pull/25

With the proposed approach there is no need to create a dedicated extension when the associated code is not ready for distribution or general use outside of a very specific context.

For now, there is duplication between CMake code in Slicer and the SlicerCMF extension, once we are done with QA, let's create an issue in Slicer tracker to document this.

**Comment by allemangD** [comment]
Closing, since we are instead bundling GROUPS with SPHARM-PDM.

**Pull request closed without merging**
