### PR TITLE
ENH: Update ShapePopulationViewer extension [master]

### PR DESCRIPTION
**Pull request by jcfr**
This updates the ShapePopulationViewer extension to 23d1746edf8a3decf3a81f0bfdc770268d5ef137.

See https://github.com/NIRALUser/ShapePopulationViewer/compare/6e451df295edfce147d1502870467f60826a496a...23d1746edf8a3decf3a81f0bfdc770268d5ef137 to view changes to the extension.

### CODE REVIEW

**Comment by sjh26** [comment]
This apperas to be killing the windows extension build:

http://slicer.cdash.org/viewConfigure.php?buildid=1884181

@jcfr

**Comment by jcfr** [comment]
Thanks for the ping, I will have a look tomorrow at the latest

**Comment by sjh26** [comment]
So, my local build is progressing fine, this may just have been a one-off.

**Comment by jcfr** [comment]
I suggest we re-assess tomorrow then.

**Pull request merged**
