### PR TITLE
Update margin calculator 4.4

### PR DESCRIPTION
**Pull request by kevinwangcanada**
Please merge the new extension "MarginCalculator". thanks.

### CODE REVIEW

**Comment by fbudin69500** [comment]
It seems that you committed the wrong branch to update your code. Did you commit your master instead of the 4.4 branch?

**Comment by cpinter** [comment]
It seems to me that this request aims to merge a modified 4.4 branch to the master. Please confirm and issue the request to 4.4 branch if it is the case.

**Comment by fbudin69500** [comment]
Indeed, I misread and thought is was the other way around. But there is an error anyway.

**Comment by kevinwangcanada** [comment]
sorry, please discard this pull request. I have created a new pull request and please integrate that one.

**Pull request closed without merging**
