### PR TITLE
BUG: Adding of ShapeQuantifier dependencies

### PR DESCRIPTION
**Pull request by jbvimort**
ShapeQuantifier need CMFReg ShapepopulationViewer and ModelToModelDistance extensions to work properly

### CODE REVIEW

**Comment by jcfr** [comment]
Note: I will merge after addressing issue related to building extension with dependencies.

**Comment by jbvimort** [comment]
Hello! 

Is it possible to have this pull request accepted?
My internship is ending in a week and I would like to check that everything is working before?

Thanks in advance

**Comment by jcfr** [comment]
As soon as this topic is completed and the build of dependent fixed, it will be integrated.

On going work: https://github.com/jcfr/Slicer/tree/validate-extension-description-file

Integrating now, would only cause the extension to report it failed

**Comment by jcfr** [comment]
Thanks for your patience.

**Pull request merged**
