### PR TITLE
BUG: fix logging

### PR DESCRIPTION
**Pull request by naucoin**
Needed to import the logging package for the round trip test to pass.
Fixes: ReportingRoundTripTest

### CODE REVIEW

**Comment by naucoin** [comment]
Fixed the DICOM Seg tests.
The Reporting Round Trip test is failing due to a crash on exit tracked back to the Data Probe module parameter node, it needs to be debugged outside of Reporting, so the current commits should be good to merge for now.

**Comment by fedorov** [comment]
@naucoin just wanted to point out that the convention for the topic names for ExtensionIndex updates is "update <ExtensionName>". Sorry I was too busy when you submitted and didn't have a chance to tel you about this or update the topic.

**Comment by jcfr** [comment]
See http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Developers/Tutorials/Contribute_Extension_Description_File#Requesting_an_extension_update

**Comment by jcfr** [comment]
I guess, we shouldn't prevent user from having more explicit topic name if they want.

**Comment by fedorov** [comment]
I agree, but then it should be something  like
```
update Reporting: fix logging
```
anyway, just wanted to help. I am fine either way.

**Comment by jcfr** [comment]
Are we talking about the topic name or the commit message ?

For the topic name, would prefer not having spaces or semicolons.

Instead of 
```
update Reporting: fix logging
```

 the following would be better (and machine friendly)

```
update-Reporting_fix-logging
```

**Comment by fedorov** [comment]
I was talking about the title of the pull request that shows on top of this page

**Comment by jcfr** [comment]
I see.  Makes sense in that case.

**Comment by naucoin** [comment]
Ah, sorry about the confusion, I was trying to be clear and not re-use a former branch name, I didn't notice  that the pull request would take the commit message rather than the branch name.

**Pull request merged**
