### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by RivettiLuciano**
Thank you for contributing to 3D Slicer!

- **To add a new extension with this pull request**: Please keep content of "TODO list for submitting a new extension" section and put an 'x' character in the brackets for each todo item to indicate that you have accomplished that prerequisite.

- **To update an existing extension with this pull request**: Please delete all text in this template and just describe which extension is updated and optionally tell us in a sentence what has been changed. To make extension updates easier in the future (so that you don't have to submit a new pull request after each change in your extension), you may consider replacing specific git hash in your s4ext file by a branch name (for example: `master` or `release` for nightly version; `(majorVersion).(minorVersion)` such as `4.10` for stable Slicer version).

# TODO list for submitting a new extension

[To make sure users can find your extension, understand what it is intended for and how to use it, please complete the checklist below. You do not need to complete all the item by the time you submit the pull request, but most likely the changes will only be merged if all the tasks are done. See more information about the submission process on the Slicer wiki: https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/BuildTestPackageDistributeExtensions]

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click "Manage topics" on your repository's main page, on the left, near the top (just below the repository description). To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [x] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/master/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work.
Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.

[If you have any questions or comments then please describe them here.]

### CODE REVIEW

**Comment by lassoan** [comment]
Thank you for your contribution, this looks great. There are just a few small issues to address and it should be ready to go:

-[ ] homepage, repository, icon, screenshot URLs in the pull request are not up-to-date (it should be https://github.com/RivettiLuciano/SlicerT1_ECVMapping), both in the pull request and in the CMakeLists.txt in the repository
-[ ] typo in README.md: stadistics (multiple times)
-[ ] delete temporary folder __pycache__ from the repository
-[ ] hard to download sample data sets - create a new release on github "SampleData" and upload the data sets as a single zip file.

**Comment by RivettiLuciano** [comment]
> Thank you for your contribution, this looks great. There are just a few small issues to address and it should be ready to go:
> 
> * [ ]  homepage, repository, icon, screenshot URLs in the pull request are not up-to-date (it should be https://github.com/RivettiLuciano/SlicerT1_ECVMapping), both in the pull request and in the CMakeLists.txt in the repository
> * [ ]  typo in README.md: stadistics (multiple times)
> * [ ]  delete temporary folder **pycache** from the repository
> * [ ]  hard to download sample data sets - create a new release on github "SampleData" and upload the data sets as a single zip file.

Thank you. It is already done.

**Comment by lassoan** [comment]
Thank you. __pycache__ is indeed deleted now. The other tasks have not been completed yet. Let me know if you need more clarification for any of them.

**Comment by RivettiLuciano** [comment]
> Thank you. **pycache** is indeed deleted now. The other tasks have not been completed yet. Let me know if you need more clarification for any of them.

Sorry, my mistake. Check if it is OK, If not I will need more clarification in the first.

**Comment by lassoan** [comment]
You are getting close.

Set scm revision to `master` in the submitted file so that you don't need to keep sending pull requests here when you update your extension.

Also, test data is still not in a Release asset. Create a new release by clicking clicking on "Releases" in your repository, then create a new one, and upload test data zipped into a single file to the release.

**Comment by RivettiLuciano** [comment]
> master

Ok. Thank you for taking the time to help me. I think it's done.

One more question. I submitted a request to the Slicer wiki in order to create an account and develop the page of this module in the wiki. The instructions claims that I should have received a mail but I din't. Do you know what can I do?

**Comment by lassoan** [comment]
Thank you, it is all good now. I've merged it now. Check the dashboard and extension manager tomorrow to see if it is available on all platforms and can be installed correctly.

**Comment by lassoan** [comment]
> I submitted a request to the Slicer wiki in order to create an account and develop the page of this module in the wiki. The instructions claims that I should have received a mail but I din't. Do you know what can I do?

Earlier developers used Slicer's documentation, issue tracking, source code hosting, etc. but since these are now all easily and freely available, we now recommend to users to take advantage of these: use github for all these.

Where did you find the recommendation to document your extension on the Slicer wiki?

**Comment by jamesobutler** [comment]
https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/BuildTestPackageDistributeExtensions#Step-by-step:_How_to_create.2C_publish.2C_distribute_and_maintain_an_extension_.3F

links to

https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/DocumentExtension#Extension_page

There is also this mention on the above page link which surprisingly has no history of being added.

> When Slicer 4.12 will be released, the set of "Nightly" pages will be copied into "4.12" then the nightly pages will continue to evolve until the next release.

**Comment by RivettiLuciano** [comment]
> > I submitted a request to the Slicer wiki in order to create an account and develop the page of this module in the wiki. The instructions claims that I should have received a mail but I din't. Do you know what can I do?
> 
> Earlier developers used Slicer's documentation, issue tracking, source code hosting, etc. but since these are now all easily and freely available, we now recommend to users to take advantage of these: use github for all these.
> 
> Where did you find the recommendation to document your extension on the Slicer wiki?

I Found it in the Web page cited by jamesobutler in the last reply.

**Comment by RivettiLuciano** [comment]
> Thank you, it is all good now. I've merged it now. Check the dashboard and extension manager tomorrow to see if it is available on all platforms and can be installed correctly.

I checked the dashboard but the module doesn't appear. http://slicer.cdash.org/index.php?project=Slicer4&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=T1_ECVMapping. It isn't available in the extension manager. Does it usually take more than a day?

**Comment by lassoan** [comment]
You have checked the Slicer-4.10 release dashboard, but you only submitted to the latest master branch.

It is available on all platforms for the latest Slicer Preview Release:
http://slicer.cdash.org/index.php?project=SlicerPreview&date=2020-05-24&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=T1_ECVMapping

It should be also available for download in the extension manager of the most recent Slicer Preview Release.

**Pull request merged**
