### PR TITLE
Add MUST-segmenter extension

### PR DESCRIPTION
**Pull request by kyliekeijzer**
# New extension

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Any known related patents must be mentioned in the extension description.
- [x] If source code license is more restrictive for users than BSD, MIT, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (main, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://raw.githubusercontent.com/user/repo/main/SomeIcon.png)
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [x] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/main/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [x] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)

### CODE REVIEW

**Comment by lassoan** [comment]
Thank you very much, the extension looks amazing and the tutorial is very nice and detailed, too.

I could not try the extension because there was no download link to sample data and I don't have time to dig out suitable data sets. So, I just provide comments based on reviewing the code and will provide more feedback when I get to try the module.

- [ ] It would be useful to have a name that gave a hint that it is for PET SUV segmentation. For example, **PET-MUST-Segmentation** would allow many more users to discover your extension just by browsing the extensions manager.
- [ ] Icon URLs must have the format prescribed in the checklist (e.g., https://raw.githubusercontent.com/kyliekeijzer/Slicer-MUST-segmenter/master/Slicer-MUST-segmenter.png)
- [ ] You have many nice images. Add more to the list of EXTENSION_SCREENSHOTURLS
- [ ] Installing Python packages in the body of the script is not allowed because that is executed at every application startup. It would make the first application startup very slow (even if the the additional package did not get used), and would add some additional slowdown at every startup. Instead, install any additional Python package when it is first used. Also ask the user for confirmation if it is not just a really tiny Python-only package. See example [here](https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#install-a-python-package).
- [ ] Pyradiomics is already available via the SlicerRadiomics extension. If you pip-install it then that version may clash with the version that someone may have from pyradiomics. So, if pyradiomics is not found then install the SlicerRadiomics extension instead of installing via pip. See example for the latest Slicer Preview Release (it will be the new stable within a few days) [here](https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#download-and-install-extension). Or you can just ask the user to install that extension.
- [ ] Add download link to sample data that is used in the tutorial. Without that, I (and many other users) will have trouble following the tutorial (if something is not working as expected then it is not clear if it is because of the different data or I'm doing something wrong)
- [ ] Remove the TBD from the documentation. For Slicer download and extension install instructions you can refer to the Slicer documentation (https://slicer.readthedocs.io/en/latest/user_guide/getting_started.html#installing-3d-slicer and https://slicer.readthedocs.io/en/latest/user_guide/extensions_manager.html#install-extensions). Video tutorial - when you have the video then add the link - no need to put a tbd there (if it is a note for yourself then enter an issue in the issue tracker instead).

**Comment by kyliekeijzer** [comment]
Dear @lassoan,

Thank you again for your feedback! 
I have changed the following:

- The repository name and the display name for the extensions manager now contains 'PET', resulting in 'PET-MUST-segmenter'
- Icon urls are in the correct format
- More images are added to the screenshot urls
- Python packages installation moved to where the extension is loaded
- Requirement of SlicerRadiomics extension is now mentioned in the tutorial and in the script (when trying to import)
- "TBD" removed from documentation

It is understandable that I need to provide the sample data. However, due to convidential patient information from University Medical Center Groningen (UMCG, The Netherlands), several steps are required before I can provide the sample data. Discussion with responsible clinicians/researchers on how to properly anonymize it will be performed later. Afterwards, a sample dataset can be provided. Is this possible?

**Comment by pieper** [comment]
@kyliekeijzer thanks for your work on this and making it available.  Regarding sample data, could you use publicly available data, e.g. from [TCIA](https://www.cancerimagingarchive.net/)?  There are many PET/CT studies available and in addition to being useful for tutorials, it would demonstrate the generalizability of your work to apply it to data not from your home institution.

**Comment by kyliekeijzer** [comment]
@pieper very good suggestion, thank you! I provided a sample dataset (.zip) here: https://github.com/kyliekeijzer/Slicer-PET-MUST-segmenter/tree/master/Sample%20Data 
Please let me know if other/more sample datasets are required, I can explore the TCIA.

**Comment by kyliekeijzer** [comment]
@pieper I will look into it and let you know when I created a SelfTest!

**Comment by kyliekeijzer** [comment]
@pieper I have created a SelfTest that utilizes the sample data, and is available under the SelfTests.

**Comment by kyliekeijzer** [comment]
@pieper I have added some updates to the extension. Are you able to test it using test data and the SelfTest?

**Comment by pieper** [comment]
I just got a chance to test @kyliekeijzer - the SelfTest worked pretty well, but it gave a message that SlicerRadiomics wasn't installed even though it is.  As you can see, I was able to run the Radiomics module independently using the segmentations generated by the SelfTest so I think there's some incorrect logic in the module.

image

**Comment by kyliekeijzer** [comment]
@pieper I am not able to reproduce the error. If I install SlicerRadiomics, the pyradiomics package is installed and I can import it using my extension. Even if I reinstall Slicer and the SlicerRadiomics extension (then restart again). 
image
Do you have any suggestion what may have caused the issue?

**Comment by kyliekeijzer** [comment]
@pieper @lassoan Do you maybe have any updates regarding the extension?

**Comment by pieper** [comment]
Since there were no objections I merged this.  Let's keep an eye on the builds and tests and see if there are further tweaks required.  Thanks for the contribution and your patience 👍

**Comment by kyliekeijzer** [comment]
@pieper Thank you! And please let me know when alterations are needed

**Comment by pieper** [comment]
I think the main thing will be to just try the extension tomorrow, ideally on a couple different platforms, to make sure it's behaving as you expect.  we can take if rom there if there's anything unexpected.

**Comment by kyliekeijzer** [comment]
@pieper Ok perfect! I can test it on multiple devices.

**Comment by jamesobutler** [comment]
@kyliekeijzer Currently your extension is only available in Slicer Preview 5.3 builds. If you would like your extension to be available for current Slicer stable 5.2.1, create a new branch based off of https://github.com/Slicer/ExtensionsIndex/tree/5.2, add a commit with your same .s4ext file, then issue a PR targeting the https://github.com/Slicer/ExtensionsIndex/tree/5.2 branch. All .s4ext files in the `5.2` branch will be built for Slicer 5.2.x stable releases.

**Comment by kyliekeijzer** [comment]
@jamesobutler Thank you! I've created a new PR: https://github.com/Slicer/ExtensionsIndex/pull/1901

**Pull request merged**
