### PR TITLE
Request to add Arduino Controller extension

### PR DESCRIPTION
**Pull request by pzaffino**
Hi,
we added the code developed in Gran Canaria to link Arduino and Slicer.
Right now there is just the connection part wrote by @lassoan but, on top of this, we will add additional features (e.g what happens if the device gets disconnected) and additional modules (eg. gesture control).

Thanks,
Paolo

# TODO list for submitting a new extension

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [ ] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To learn more about topic, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [x] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/master/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work.
Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.

### CODE REVIEW

**Comment by lassoan** [comment]
Thank you Paolo, the checklist is almost completed, just associate the repository with "3d-slicer-extension" as described above (click "Manage topics" on https://github.com/pzaffino/SlicerArduinoController page, on the left, near the top).

**Comment by pzaffino** [comment]
@lassoan done!

**Comment by jcfr** [comment]
Thanks

Could you update the description in the README to describe the meaning of "connect", what type of information is sent to Slicer ? What can you control in Slicer using the Arduino?

**Comment by pzaffino** [comment]
@jcfr README edited

**Comment by lassoan** [comment]
Rebased and merged.

**Pull request closed without merging**
