### PR TITLE
ENH: Update Slicer-AirwaySegmentation extension

### PR DESCRIPTION
**Pull request by PietroNardelli**

### CODE REVIEW

**Comment by jcfr** [comment]
@PietroNardelli Seems there is already an description file named `AirwaySegmentation.s4ext`, should it be removed ? See https://github.com/Slicer/ExtensionsIndex/blob/master/AirwaySegmentation.s4ext

**Comment by PietroNardelli** [comment]
Yes, please. Sorry for that!

2015-04-29 18:37 GMT+01:00 Jean-Christophe Fillion-Robin <
notifications@github.com>:

**Comment by jcfr** [comment]
No problem.

What should we do for the one associated with 4.4 ? See https://github.com/Slicer/ExtensionsIndex/blob/4.4/AirwaySegmentation.s4ext

If you plan on also updating it, I could remove it too. Let me know.

**Comment by PietroNardelli** [comment]
Yes, I will update that too!! Thank you very much!

2015-04-29 19:44 GMT+01:00 Jean-Christophe Fillion-Robin <
notifications@github.com>:

**Pull request merged**
