### PR TITLE
Add GridSurface extension

### PR DESCRIPTION
**Pull request by cpinter**
[To make sure users can find your extension, understand what it is intended for and how to use it, please complete the checklist below. You do not need to complete all the item by the time you submit the pull request, but most likely the changes will only be merged if all the tasks are done. See more information about the submission process here: https://slicer.readthedocs.io/en/latest/developer_guide/extensions.html]

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Any known related patents must be mentioned in the extension description.
- [x] If source code license is more restrictive for users than BSD, MIT, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (main, master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://github.com/user/project/raw/main/path/to/icon.png)
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [X] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [X] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [X] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [x] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/master/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [x] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)

### CODE REVIEW

**Comment by lassoan** [comment]
This is great, thank you. We should just brainstorm a bit more on the name. The extension can create an editable surface from scratch or by fitting to an existing model and then edit that. The current name does not indicate this.

Here are a few words or name fragments to start the brainstorming:

Surface patch
Surface patch editor
Curved plane edit
Plane warp
Surface warp
Point grid to surface
Points to surface
Grid to surface

(I would reserve surface editor and model editor names to the future Segment-Editor-like editir that we will introduce at some point.)

**Comment by cpinter** [comment]
Instead of edit/editor maybe we can just use the word markup at the end to indicate it is a control point based markup type. I assume most Slicer users know what markups are.

I like Surface patch.

Would you consider grid based surface?

**Comment by lassoan** [comment]
I would prefer "Surface patch" over "Grid based surface", "Grid based surface markup", or "Grid surface markup". 

Could you upload a video to youtube (unlisted) to show what the extension can do and ask for naming suggestions in the https://discourse.slicer.org/t/extending-the-markups-module/14882/11 topic? (because for example I could not @mention Rafael here)

**Comment by pieper** [comment]
I think Curved Surface would be a pretty common term for this, with Surface Patch as my second choice.  Do you plan to make stitched surfaces with common control points on the shared edges?  If so then Patch would be a little better term.

**Comment by cpinter** [comment]
Thanks for the input! I'll make the video when I'm not working from remote desktop.

> Do you plan to make stitched surfaces with common control points on the shared edges?

Yes we plan to support shared edges.

**Comment by cpinter** [comment]
I wonder why don't we simply call it Surface Markup? It is a markup type just as Curve, Closed curves, Line, etc, and its goal is to represent and edit surfaces.

**Comment by lassoan** [comment]
I like both CurvedSurface and SurfaceMarkup names.

**Comment by cpinter** [comment]
I renamed the extension to SurfaceMarkup. Let me know if there is anything else. Thanks!

**Comment by lassoan** [comment]
Almost perfect. Just update the text in the https://github.com/cpinter/SlicerSurfaceMarkup/blob/master/SurfaceMarkupLogo_128.png and it should be good to go. It would be nice if you could include the source image file (xcf?) in the repository.

**Comment by cpinter** [comment]
Shoot, I forgot about the logo, thanks for the heads-up. I'll include the xcf as well.

**Comment by cpinter** [comment]
@lassoan Done

**Pull request merged**
