### PR TITLE
ENH: Add SlicerCMF extension [master]

### PR DESCRIPTION
**Pull request by jcfr**
Description:
Dental image analysis to support patient-specific decision making and
assessment of the disease progression via registration of serial images.

Contributors:
Lucia Cevidanes (University of Michigan), Beatriz Paniagua (Kitware),
Jean-Christophe Fillion-Robin (Kitware)

# TODO list for submitting a new extension

[To make sure users can find your extension, understand what it is intended for and how to use it, please complete the checklist below. You do not need to complete all the item by the time you submit the pull request, but most likely the changes will only be merged if all the tasks are done. See more information about the submission process on the Slicer wiki: https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/BuildTestPackageDistributeExtensions]

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click "Manage topics" on your repository's main page, on the left, near the top (just below the repository description). To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [x] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/master/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work.
Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.

### CODE REVIEW

**Comment by bpaniagua** [comment]
> Short description: 1-2 sentences, which summarizes what the extension is usable for

SlicerCMF is the dissemination vehicle of powerful dental image analysis methodology based on 3D Slicer open-source software. SlicerCMF include registration, segmentation and quantification functionality modules that can support patient-specific decision making and assessment of the disease progression.

**Comment by bpaniagua** [comment]
> Publication: link to publication and/or to PubMed reference (if available)
http://cmf.slicer.org/citations/

**Comment by bpaniagua** [comment]
> At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
Screen Shot 2020-04-08 at 1 53 38 PM
With credits to Yatabe M, Gomes L, Ruellas AC, et al. Challenges in measuring angles between craniofacial structures. J Appl Oral Sci. 2019;27:e20180380. Published 2019 Jun 3. doi:10.1590/1678-7757-2018-0380

**Comment by bpaniagua** [comment]
> Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set

https://www.youtube.com/user/DCBIA

**Comment by lassoan** [comment]
This will be great!

You may find useful for this extension the new plane markups widget that we have recently added in Slicer Preview. A nice interactive plane editing feature is being added right now (https://github.com/Slicer/Slicer/pull/4800). It would be nice if you could try how it works for you and provide any suggestions (you can write your comments to the [pull request](https://github.com/Slicer/Slicer/pull/4800))

**Comment by bpaniagua** [comment]
> Description of contained modules: at one sentence for each module

Done (i think this took me forever to figure out) http://cmf.slicer.org/

**Comment by jcfr** [comment]
> > Short description: 1-2 sentences, which summarizes what the extension is usable for

> SlicerCMF is the dissemination vehicle of powerful dental image analysis methodology based on 
> 3D Slicer open-source software. SlicerCMF include registration, segmentation and quantification 
> functionality modules that can support patient-specific decision making and assessment of the 
> disease progression.

I suggest this description instead:

SlicerCMF is a 3D Slicer extension providing registration, segmentation and quantification modules for dental images that may support patient-specific decision making and assessment in the context of disease progression.

**Comment by jcfr** [comment]
> > Description of contained modules: at one sentence for each module

> Done (i think this took me forever to figure out) http://cmf.slicer.org/

This is great.

Please, review these additional changes: https://github.com/slicercmf/slicercmf.github.io/pull/5

**Comment by jcfr** [comment]
> > At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.

I also added the screenshot to the homepage. See https://github.com/slicercmf/slicercmf.github.io/pull/5#issuecomment-611475146

**Pull request merged**
