### PR TITLE
ENH: Add DatabaseInteractor extension.

### PR DESCRIPTION
**Pull request by ClementMirabel**
This extension contains multiple panels that allow the user to manage data from a web database. The data displayed in this extension dynamically reacts with user local folders and online database. The user should login with the same credentials as the server entered as input.

### CODE REVIEW

**Comment by fedorov** [comment]
The repo URL does not work - did you forget to make it public?

https://github.com/NIRALUser/DatabaseInteractorExtension

**Comment by fedorov** [comment]
Also, can you clarify what you mean by "a web database"?

**Comment by ClementMirabel** [comment]
@fedorov 
1) Ok, I corrected the repository URL, did a confusion between 2 labs accounts.
2) I am developing that tool to access an Apache-CouchDB database

**Comment by fedorov** [comment]
> I am developing that tool to access an Apache-CouchDB database

It would help if you add a description of what database it will be able to connect. Is it off-the-shelf product that users should be able to install and configure on their own? Or is it something that exists in a centralized location and the extension is expected to interact with that specific instance? Is there a pointer to the documentation for that web database?

**Comment by pieper** [comment]
@ClementMirabel this sounds promising!

Just as a suggestion about extensions, we prefer to have more public information about the intended use and functionality of the modules provided by the extension.  As distributors of Slicer the core developers need to have a reasonable sense of what we are offering to users.  That's why we ask all these questions and we encourage extension developers to write informative wiki pages.

**Comment by fedorov** [comment]
@pieper thank you for the clarification. Indeed, I understand that some extension developers may be in a mindset that they provide extension to the specific community that has its own conventions and workflows. However, since the extension will be visible and accessible to everybody in the broader community of Slicer users, it is very important to make sure you document your extension appropriately. Alternatively, if you are focusing on a narrow group of users, perhaps it might be ok to just add a disclaimer "This extension is developed specifically for [group details] and is not intended for general use".

**Comment by ClementMirabel** [comment]
I did a PR to the repository indicated with a better documentation than the one on the repository.
Based on your feedback, I will work on giving a better explanation of the project. (https://github.com/ClementMirabel/DatabaseInteractorExtension/blob/master/README.md and https://www.slicer.org/wiki/Documentation/Nightly/Modules/DatabaseInteractor)

Basically what will be added is:
- This extension has been developed to work with this website:
https://ec2-52-42-49-63.us-west-2.compute.amazonaws.com:8180/DCBIA-OrthoLab/public/
- The user will need to know the server URL and have an account on the website relative to the server URL indicated.

As the extension has been designed for a project, some functionalities will be restricted to the CouchDB architecture created on this website. So, I really need to clarify that in the documentation to prevent users trying it whatever the database they have.

**Comment by fedorov** [comment]
@ClementMirabel excellent, this is exactly the kind of clarification I was looking for! 

Also, when you document the database interaction, please indicate whether there is a public account to experiment with the functionality, or if there is a procedure to request an account, or neither.

Thank you!

**Comment by ClementMirabel** [comment]
Reading my own documentation, I need to figure out one point. This extension is working with a python library not included in Slicer (requests). So, the extension would probably not be able to be packaged.

**Comment by fedorov** [comment]
You could investigating addition of requests to the list of Slicer external modules, as it was done for pydicom and many other things. At least from the description, it sounds like a package of general interest. I don't know what are the dependencies and complexities of adding that specific package into Slicer.

**Comment by pieper** [comment]
I've heard good things about the requests package too.  If the dependencies are all pure python (as in pydicom) which I think they are then adding it is pretty simple.  As a starting point looking at bundling the python code into your extension is a place to get started.

**Comment by ClementMirabel** [comment]
So, I updated a bit my documentation and added requests files into my repository.
Thank you for the feedbacks and the help.

**Comment by fedorov** [comment]
> I updated a bit my documentation and added requests files into my repository

Documentation is great, thanks, but I don't see requests in your repo. The package is imported here, so I don't see how this module will work, since this import will fail:

https://github.com/DCBIA-OrthoLab/DatabaseInteractorExtension/blob/master/DatabaseInteractor/myLib.py#L1

**Comment by ClementMirabel** [comment]
I still waiting my PR to be accepted here: https://github.com/DCBIA-OrthoLab/DatabaseInteractorExtension/pull/1
I'm the main developer of that tool but we need to store it on our Lab Github to be maintained where I'll leave. 
So, you can check here (https://github.com/ClementMirabel/DatabaseInteractorExtension) for the changes.

**Comment by fedorov** [comment]
Sounds good - please update this discussion when things are ready on your end and you consider this PR ready to merge.

**Comment by ClementMirabel** [comment]
Pull request accepted on the other side, so that should be ready here.

**Comment by fedorov** [comment]
@ClementMirabel I don't see what would package requests into the extension package. But I am fine to merge and see what happens so you can proceed with debugging. 

If you would prefer to merge as is, I will let @jcfr to decide if this is ready to merge or not.

**Comment by fedorov** [comment]
@jcfr - I don't know if this is supposed to work this way or not, but I am unable to add reviewers to this PR.

**Comment by ClementMirabel** [comment]
Oh I see what you mean. First, because of my CMakeLists, the files won't be packaged. If I include them that will probably create an error like "Cannot read class requests".

**Comment by ClementMirabel** [comment]
I set the requests package as a resource for the scripted module, it seems it just copy those files and doesn't try to interpret them (just like an image). I did a make package and it installed well on a nightly version.

**Pull request merged**
