### PR TITLE
Add clever seg

### PR DESCRIPTION
**Pull request by JonathanRamos**
Thank you for contributing to 3D Slicer!

- **To add a new extension with this pull request**: Please keep content of "TODO list for submitting a new extension" section and put an 'x' character in the brackets for each todo item to indicate that you have accomplished that prerequisite.

- **To update an existing extension with this pull request**: Please delete all text in this template and just describe which extension is updated and optionally tell us in a sentence what has been changed. To make extension updates easier in the future (so that you don't have to submit a new pull request after each change in your extension), you may consider replacing specific git hash in your s4ext file by a branch name (for example: `master` or `release` for nightly version; `(majorVersion).(minorVersion)` such as `4.10` for stable Slicer version).

# TODO list for submitting a new extension

[To make sure users can find your extension, understand what it is intended for and how to use it, please complete the checklist below. You do not need to complete all the item by the time you submit the pull request, but most likely the changes will only be merged if all the tasks are done. See more information about the submission process on the Slicer wiki: https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/BuildTestPackageDistributeExtensions]

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [ ] Extension icon URL is correct
- [ ] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [ ] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/master/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work.
Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.

[If you have any questions or comments then please describe them here.]
I intend to make available the images tutorials, usage, etc using the 3DSlicer wiki while in the process of making the extension available, is that possible?

### CODE REVIEW

**Comment by lassoan** [comment]
Thank you for the submission!

How does the effect differ from "Grow from seeds" effect in Segment Editor?

We plan to remove the legacy Editor module in the next major release of Slicer. Would you consider adding a Segment Editor effect? You can build your effect on the AuroComplete base class, which provides live preview, automatic updates based on modified seeds, etc. which should greatly simplify implementation of the effect.

**Comment by JonathanRamos** [comment]
> Thank you for the submission!
> 
> How does the effect differ from "Grow from seeds" effect in Segment Editor?
> 
> We plan to remove the legacy Editor module in the next major release of Slicer. Would you consider adding a Segment Editor effect? You can build your effect on the AuroComplete base class, which provides live preview, automatic updates based on modified seeds, etc. which should greatly simplify implementation of the effect.

CleverSeg grows in a balanced manner, considering the average between old and new strengths and does not depend on any parameter setting. This should be more clear as I release the paper at arxiv.

Thanks for letting me know about that. I had no knowledge about it. 
Sure, I am going to consider adding a Segment Editor effect and use AutoComplete. Is there a template or something?

One question, is it possible to work with labels greater than short (1 byte), I couldn't figure out how to do it.

**Comment by lassoan** [comment]
Try Grow from seeds and Watershed effects (in SegmentEditorExtraEffects extension) and have a look at their source code.

https://github.com/Slicer/Slicer/blob/master/Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorGrowFromSeedsEffect.py

https://github.com/lassoan/SlicerSegmentEditorExtraEffects/tree/master/SegmentEditorWatershed

These should answer your questions but if not then feel free to ask.

**Comment by JonathanRamos** [comment]
> Try Grow from seeds and Watershed effects (in SegmentEditorExtraEffects extension) and have a look at their source code.
> 
> https://github.com/Slicer/Slicer/blob/master/Modules/Loadable/Segmentations/EditorEffects/Python/SegmentEditorGrowFromSeedsEffect.py
> 
> https://github.com/lassoan/SlicerSegmentEditorExtraEffects/tree/master/SegmentEditorWatershed
> 
> These should answer your questions but if not then feel free to ask.

Thank you very much! I will take a very careful look at it.
I will be sending an improved version (FastCleverSeg) soon as well.
However, the doctors need this one ready to go asap so that they can proceed with their research.

**Comment by JonathanRamos** [comment]
Hey, hi
I am implementing the codes for the segment editor.

The autocomplete class I use in the python code or in the c codes?

Sorry for the lame question, I am really confused about it

**Comment by lassoan** [comment]
AutoComplete base class is implemented in Python, so the easiest is to implement your GUI in Python. From this Python class, you can call methods implemented in C++ for doing the actual processing (this is done like this in both Grow from seeds and Fill between slices effects).

**Comment by JonathanRamos** [comment]
Thanks, I am on my way.

I downloaded the WatershedEffect as example and just renamed it to CleverSegmentation

I am getting the following error from the autocomplete class:
Traceback (most recent call last):
  File "/Users/jramos/MyProjects/Slicer-Build/Slicer-build/lib/Slicer-4.11/qt-scripted-modules/SegmentEditorEffects/AbstractScriptedSegmentEditorAutoCompleteEffect.py", line 252, in onPreview
    self.preview()
  File "/Users/jramos/MyProjects/Slicer-Build/Slicer-build/lib/Slicer-4.11/qt-scripted-modules/SegmentEditorEffects/AbstractScriptedSegmentEditorAutoCompleteEffect.py", line 445, in preview
    self.computePreviewLabelmap(mergedImage, outputLabelmap)
  File "/Users/jramos/MyProjects/CleverSegBuild/lib/Slicer-4.11/qt-scripted-modules/SegmentEditorCleverSegmentationLib/SegmentEditorEffect.py", line 92, in computePreviewLabelmap
    import vtkSlicerSegmentationsModuleLogicPython as vtkSlicerSegmentationsModuleLogic
ImportError: dlopen(/Users/jramos/MyProjects/Slicer-Build/Slicer-build/lib/Slicer-4.11/qt-loadable-modules/vtkSlicerSegmentationsModuleLogicPython.so, 1): no suitable image found.  Did find:
	/Users/jramos/MyProjects/Slicer-Build/Slicer-build/lib/Slicer-4.11/qt-loadable-modules/./vtkSlicerSegmentationsModuleLogicPython.so: malformed mach-o: load commands size (32800) > 32768
	/Users/jramos/MyProjects/Slicer-Build/Slicer-build/lib/Slicer-4.11/qt-loadable-modules/vtkSlicerSegmentationsModuleLogicPython.so: malformed mach-o: load commands size (32800) > 32768
	/Users/jramos/MyProjects/Slicer-Build/Slicer-build/lib/Slicer-4.11/qt-loadable-modules/vtkSlicerSegmentationsModuleLogicPython.so: malformed mach-o: load commands size (32800) > 32768
	/Users/jramos/MyProjects/Slicer-Build/Slicer-build/lib/Slicer-4.11/qt-loadable-modules/vtkSlicerSegmentationsModuleLogicPython.so: malformed mach-o: load commands size (32800) > 32768


I have no ideia how to fix it (I looked it up on the internet and found nothing to solve it)
I am running on macbook pro

**Comment by pieper** [comment]
@JonathanRamos that error happens when the path names get too long - easiest workaround is to build in someplace like `/sb` or similar (e.g. `mkdir /sb; sudo chown jramos /sb`)

**Comment by JonathanRamos** [comment]
> @JonathanRamos that error happens when the path names get too long - easiest workaround is to build in someplace like `/sb` or similar (e.g. `mkdir /sb; sudo chown jramos /sb`)

Thank you! xD

**Comment by JonathanRamos** [comment]
I dont understand where the growCutFilter.Update() function comes from in the SegmentEditorGrowFromSeedsEffect.py

I looked in every file in the Slicer/Modules/Loadable/Segmentations and could find it.

**Comment by lassoan** [comment]
It is calling Update in vtkImageAlgorithm base class, which calls Execute... methods in the filter: https://github.com/Slicer/Slicer/blob/master/Modules/Loadable/Segmentations/Logic/vtkImageGrowCutSegment.cxx

**Comment by JonathanRamos** [comment]
> It is calling Update in vtkImageAlgorithm base class, which calls Execute... methods in the filter: https://github.com/Slicer/Slicer/blob/master/Modules/Loadable/Segmentations/Logic/vtkImageGrowCutSegment.cxx

Thank you!

It is working now.

However, I made inside of the slicer tree under the segmentations/logic module (segmentEditorCleverSegSegment).

I tried the extension wizard (scripted) but I couldnt figure out how to make it work with my c++ files (segmentEditorCleverSegSegment)

**Comment by lassoan** [comment]
> However, I made inside of the slicer tree under the segmentations/logic module (segmentEditorCleverSegSegment).

You can add a loadable module to your segmentation. You can make the module hidden (and even delete all widget classes from the template) and put the new class in this loadable module.

**Comment by JonathanRamos** [comment]
> > However, I made inside of the slicer tree under the segmentations/logic module (segmentEditorCleverSegSegment).
> 
> You can add a loadable module to your segmentation. You can make the module hidden (and even delete all widget classes from the template) and put the new class in this loadable module.

Thank you! I it worked!

**Comment by sjh26** [comment]
Closed with #1658

**Pull request closed without merging**
