### PR TITLE
Add LesionSpotlight Extension

### PR DESCRIPTION
**Pull request by acsenrafilho**
This extension provides an recent image segmentation and enhancement approaches in order to highlight abnormal white matter voxels in magnetic resonance images. At moment, there are available the LS Segmenter module (specific for hyperintense Multiple Sclerosis lesion segmentation on T2-FLAIR images) and LS Contrast Enhancement Module (specific to increase the contrast of abnormal voxels of the same T2-FLAIR images). The LS Segmenter module implements a hyperintense T2-FLAIR lesion segmentation based on a hybrid segmentation algorithm, published by Senra Filho, A.C. (http://dx.doi.org/10.1007/s11517-017-1747-2). In addition, a simple implementation of another recent MS lesion segmentation algorithm is provided, being the method described in Cabezas M. et al. (http://dx.doi.org/10.1016/j.cmpb.2014.04.006)

Further details in the wiki page: http://slicer.org/slicerWiki/index.php/Documentation/Nightly/Extensions/LesionSpotlight

### CODE REVIEW

**Comment by acsenrafilho** [comment]
Hi @jcfr 
Is my extension able to be merged into the Extension Manager? Do I need to fix something?

Thanks

**Comment by jcfr** [comment]
It looks good to me.

Cc: @pieper  @lassoan

**Comment by lassoan** [comment]
Looks good to me, too.

**Comment by jcfr** [comment]
Thanks @acsenrafilho

**Comment by acsenrafilho** [comment]
Thank you all!

**Pull request merged**
