### PR TITLE
Add files via upload ( + extension Calculator )

### PR DESCRIPTION
**Pull request by fredericpanthier**
Hello,  this is a new extension, it consists in a volumetric evaluation of kidney stones and also provides information on surgical duration. Moreover, it provides the estimated time of lithotripsy and consequently the operative time. It provides in a few seconds a 3D view of the stone(s) and axial, coronal and sagittal views with CT-scan DICOMs.
Br

Thank you for contributing to 3D Slicer!

- **To add a new extension with this pull request**: Please keep content of "TODO list for submitting a new extension" section and put an 'x' character in the brackets for each todo item to indicate that you have accomplished that prerequisite.

- **To update an existing extension with this pull request**: Please delete all text in this template and just describe which extension is updated and optionally tell us in a sentence what has been changed. To make extension updates easier in the future (so that you don't have to submit a new pull request after each change in your extension), you may consider replacing specific git hash in your s4ext file by a branch name (for example: `master` or `release` for nightly version; `(majorVersion).(minorVersion)` such as `4.10` for stable Slicer version).

# TODO list for submitting a new extension

[To make sure users can find your extension, understand what it is intended for and how to use it, please complete the checklist below. You do not need to complete all the item by the time you submit the pull request, but most likely the changes will only be merged if all the tasks are done. See more information about the submission process on the Slicer wiki: https://www.slicer.org/wiki/Documentation/Nightly/Developers/Tutorials/BuildTestPackageDistributeExtensions]

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [ ] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/master/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work.
Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.

[If you have any questions or comments then please describe them here.]

### CODE REVIEW

**Comment by pieper** [comment]
Thanks for the contribution @fredericpanthier 👍 

A few small things:

The name is pretty generic - Could the module be named something more specific, like KidneyStoneCalculator.  Then the repository would be SlicerKidneyStoneCalculator. (or maybe it should be called LithotripsyPlanning and SlicerLithotripsyPlanning).

Usually it's good for extension modules to declare their own submenu in the modules menu named the same as the extension, which you do by giving it a `category` in [the module class](https://github.com/fredericpanthier/Slicer-Calculator/blob/master/calculator/calculator.py#L19).  Otherwise it's hard to find. 

I like the extension icon!

**Comment by fredericpanthier** [comment]
Thanks for the replay, I changed the name as you proposed (KidneyStoneCalculator), Calcul is Stone in French :o) , so we thinked to the pun "Calcul-ator", but as you say Calculator is actually quite generic. I will submitted a new Pull request.
have a nice day (or night ?)

**Comment by fredericpanthier** [comment]
Hello and Thank you for your advice, we have made some modifications according to your remarks,
Please let us know if it is ok for the extension catalog?

Regards, 

Frédéric Panthier

**Comment by pieper** [comment]
Looks really good to me.  @lassoan or @jcfr any further suggestions?

**Comment by fredericpanthier** [comment]
Hello again and many thanks for your help.
Is it possible to Add kidney stone calculator to thé extension catalog?

Best regards,

Frédéric Panthier

**Comment by pieper** [comment]
Didn't hear any further comments so I merged.  Should show up in tomorrow's builds.  Thanks for the contribution 👍

**Comment by lassoan** [comment]
I've noticed a number of typos and would have many comments to improve the code but did not have time to write them up. I'll send them later. There is nothing that should hold up the submission.

**Comment by fredericpanthier** [comment]
Many thanks for your answer.
Glad to ear about the adjuction to the extension catalog.

Best regards,

Frédéric Panthier

**Pull request merged**
