### PR TITLE
Add Pipeline extension

### PR DESCRIPTION
**Pull request by Connor-Bowley**
See https://github.com/KitwareMedical/SlicerPipelines#readme

# TODO list for submitting a new extension

[To make sure users can find your extension, understand what it is intended for and how to use it, please complete the checklist below. You do not need to complete all the item by the time you submit the pull request, but most likely the changes will only be merged if all the tasks are done. See more information about the submission process here: https://slicer.readthedocs.io/en/latest/developer_guide/extensions.html]

- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Any known related patents must be mentioned in the extension description.
- [x] If source code license is more restrictive for users than BSD, MIT, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (main, master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://raw.githubusercontent.com/user/repo/main/SomeIcon.png)
- [x] Screenshot URLs (screenshoturls) are correct, contains at least one
- [x] Homepage URL points to valid webpage containing the following:
  - [x] Extension name
  - [x] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [x] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [x] Description of contained modules: at one sentence for each module
  - [x] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [x] Publication: link to publication and/or to PubMed reference (if available)
  - [x] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/master/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [x] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)

### CODE REVIEW

**Comment by sjh26** [comment]
lgtm, will merge today if no one has any objections

**Comment by jcfr** [comment]
Currently reviewing, already few small pull-request submitted.

**Comment by jcfr** [comment]
Here is a pull updating the `README.md and consolidating the information.
See https://github.com/KitwareMedical/SlicerPipelines/pull/14

After reviewing and integrating the pull request, I also suggest to:
* delete the existing wiki page and disable it. 
* update the extension description file and `CMakeLists.txt` to reference the GitHub repository

Cc: @Connor-Bowley

**Comment by Connor-Bowley** [comment]
@jcfr Why do you recommend deleting the wiki?

**Comment by jcfr** [comment]
> Why do you recommend deleting the wiki?

Since all the content would be in the README (or ultimately readthedocs), keeping the current wiki home page, you would have to maintain the same information twice.

If not disabling the wiki, the current page should then be updated to include something like this (adapted from the Slicer wiki):

```
Welcome

These pages store information about the SlicerPipelines project management and are not tied to a specific extension version.

All other documentation are available in the [SlicerPipelines manual in the README](https://github.com/KitwareMedical/SlicerPipelines#readme).

User and developer support and various other discussions take place on the [3D Slicer forum](https://discourse.slicer.org).

For more information on 3D Slicer, go to the [3D Slicer main page](https://www.slicer.org).
```

I will provide additional comment on the opened SlicerPipelines pull request

**Comment by jcfr** [comment]
Thanks so much for review and providing update :pray: , the changes have been integrated.

**Pull request merged**
