### PR TITLE
Add SlicerAblationPlanner extension

### PR DESCRIPTION
**Pull request by naterex23**
Thank you for contributing to 3D Slicer!

- **To add a new extension with this pull request**: Please keep content of "TODO list for submitting a new extension" section and put an 'x' character in the brackets for each todo item to indicate that you have accomplished that prerequisite.

- **To update an existing extension with this pull request**: Please delete all text in this template and just describe which extension is updated and optionally tell us in a sentence what has been changed. To make extension updates easier in the future (so that you don't have to submit a new pull request after each change in your extension), you may consider replacing specific git hash in your s4ext file by a branch name (for example: `master` or `release` for nightly version; `(majorVersion).(minorVersion)` such as `4.10` for stable Slicer version).

# TODO list for submitting a new extension

[To make sure users can find your extension, understand what it is intended for and how to use it, please complete the checklist below. You do not need to complete all the item by the time you submit the pull request, but most likely the changes will only be merged if all the tasks are done. See more information about the submission process here: https://slicer.readthedocs.io/en/latest/developer_guide/extensions.html]

- [X] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [X] Repository name is Slicer+ExtensionName
- [X] Repository is associated with `3d-slicer-extension` GitHub topic so that it is listed [here](https://github.com/topics/3d-slicer-extension). To edit topics, click the settings icon in the right side of "About" section header and enter `3d-slicer-extension` in "Topics" and click "Save changes". To learn more about topics, read https://help.github.com/en/articles/about-topics
- [X] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [X] Any known related patents must be mentioned in the extension description.
- [X] If source code license is more restrictive for users than BSD, MIT, Apache, or 3D Slicer license then the name of the used license must be mentioned in the extension description.
- [X] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [X] Extension icon URL is correct (do not use the icon's webpage but the raw data download URL that you get from the download button - it should look something like this: https://github.com/user/project/raw/main/path/to/icon.png)
- [X] Screenshot URLs (screenshoturls) are correct, contains at least one
- [X] Homepage URL points to valid webpage containing the following:
  - [X] Extension name
  - [X] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [X] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [X] Description of contained modules: at one sentence for each module
  - [X] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set
  - [X] Publication: link to publication and/or to PubMed reference (if available)
  - [X] License: We suggest you use a permissive license that includes patent and contribution clauses.  This will help protect developers and ensure the code remains freely available.  We suggest you use the [Slicer License](https://github.com/Slicer/Slicer/blob/master/License.txt) or the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0). Always mention in your README file the license you have chosen.  If you choose a different license, explain why to the extension maintainers. Depending on the license we may not be able to host your work. Read [here](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) to learn more about licenses.
  - [X] Content of submitted s4ext file is consistent with the top-level CMakeLists.txt file in the repository (description, URLs, dependencies, etc. are the same)

[If you have any questions or comments then please describe them here.]
This is my first time trying to publish code. Please have mercy! I've tried to follow resources available online but it's very possible I messed something up. I submitted a few questions on the forum at https://discourse.slicer.org/t/troubleshooting-extension-build-process-manually-building-an-extension/14836 , please feel free to give me feedback here or there.

### CODE REVIEW

**Comment by lassoan** [comment]
Sorry, this pull request somehow fell through the cracks and just realized that we did not merge it when I got the notification about closing the pull request.

I had a quick look and the extension looks great! A few questions/suggestions:
- I could not follow the "Ablation Planning Workflow":
  - I was not sure what to choose as "probe segment". I selected the tumor segment and it created copies of the tumor. I then realized that it is the probe model that needs to be loaded as a segmentation. This needs to be documented more clearly. (maybe just the order of steps need to be tuned)
  - I selected the tumor segment, but then could not figure out how to compute margins. I clicked "Evaluate Tumor Margins" but then I just got an error (Traceback (most recent call last): File "C:/D/SlicerAblationPlanner/AblationPlanner/AblationPlanner.py", line 641, in convertSegmentToModel   displayNode = folder.GetDisplayNode()  AttributeError: 'NoneType' object has no attribute 'GetDisplayNode')
- A few suggestions: we can help you implementing these improvements
  - it would be nice to use markups lines instead of points
  - since update of transforms is instantaneous, you could implement live update of probes as you move the lines
  - Probe segment actually selects an entire segmentation. It would be better to use a segment selector widget (`qMRMLSegmentSelectorWidget`). You could store all the probe models in a single segmentation and just select a segment from the list.
- Trivial findings:
  - make the extension icon (https://raw.githubusercontent.com/naterex23/SlicerAblationPlanner/main/AblationPlanner/Resources/Icons/AblationPlanner.png) square shaped to make it nicely aligned in the Extension manager
  - I've noticed in the .ui file that you used default object names - you could make your code more readable by giving meaningful name to each widget (e.g., rename `PushButton` to `ProbeButton`)

**Comment by lassoan** [comment]
I think we have missed your submission (and kept overlooking it) because the pull request was submitted with the default "Add files via upload" title (that I've now changed). It is easy to miss such a generic title when it arrives into our inbox and it makes your pull request very well hidden in the clutter in the pull request list.

**Comment by naterex23** [comment]
Hey Andras,

Thanks for getting back to me! I’ve made a few changes to the extension
after using it in our OR a few times. I’ll happily incorporate your
suggestions and update the read me appropriately!

Regards,

Nate Rex

**Comment by cpinter** [comment]
A quick comment: the scmurl has the https protocol twice (`https://https://github.com/naterex23/SlicerAblationPlanner`)

**Comment by naterex23** [comment]
Andras,

I've finally found some time to consider some approaches to your
recommendations... With regards to your "ablation planning workflow"
comments I'll be sure to outline some more specifics. I believe that error
you got was likely due to a segmentation not being selected in what of the
input fields, but will try to reproduce this to make sure.

Regarding your suggested improvements:
I agree the markup line is a nice touch! I think I should be able to figure
this one out on my own (theoretically)

Is there an extension that comes to mind that might be a good example of
"implement[ing] live updates of probes? I'm not sure I know of any
extensions that incorporate a nice feature like this. My lab loves the
idea!

I like your idea of including all of the probe models in a segmentation...
I'll see if I can work this out.

Trivial stuff:
I'll happily reformat the widget image and make some changes to the ui file
as well.

Looking forward to some recommendations regarding the improvements!

**Comment by lassoan** [comment]
Thank you! I'll merge it as is and fix the repository URL in a follow-up commit (as @cpinter noted above). The extension should appear in the extension manager on Friday or Saturday.

**Pull request merged**
