### PR TITLE
ENH: Added DeepInfer extension.

### PR DESCRIPTION
**Pull request by mehrtash**
Added DeepInfer Extension

### CODE REVIEW

**Comment by fedorov** [comment]
The documentation page is empty. 

You commented out this line https://github.com/DeepInfer/Slicer-DeepInfer/blob/master/CMakeLists.txt#L11 - I don't know if it is required, it might be safer to uncomment it and set to an empty string if you don't have any screenshots.

**Comment by jcfr** [comment]
Thanks for the contribution :+1: 


Few comments:
* Would be nice to associate one or two screenshots
* http://www.deepinfer.org/ seems to be down
* wiki page http://www.slicer.org/slicerWiki/index.php?title=Documentation/Nightly/Extensions/DeepInfer is incomplete


Additionally, it would be nice to:
* generalize the current CLIWidget to allow their reuse from python
* to strandardize how docker expose associated algorithm to Slicer, look at `cli_list_entrypoint.py` provided by `slicer_cli_web`. See:
* https://github.com/girder/slicer_cli_web/blob/master/server/cli_list_entrypoint.py
* https://github.com/DigitalSlideArchive/HistomicsTK/blob/9a433e55b93973729a99a174cd533d5dbd4882ea/Dockerfile#L44

**Comment by fedorov** [comment]
@mehrtash when do you plan to address the minor issues regarding documentation so that this can be integrated? A published paper claims that this extension is already available, so this task is overdue.

**Comment by lassoan** [comment]
@mehrtash There are people that I'm helping that would be interested in trying this extension. If you address these remaining small issues then they will try your software. If not available, then they have to go and find something else.

**Comment by mehrtash** [comment]
@fedorov @lassoan I'm planning to integrate the extension early next week.

**Comment by fedorov** [comment]
@mehrtash I think this is a high priority task to have this extension available in Slicer ASAP. This task is long overdue.

**Comment by mehrtash** [comment]
a new pull request #1401 was made.

**Pull request closed without merging**
