### PR TITLE
Add SlicerDcm2nii extension

### PR DESCRIPTION
**Pull request by ihnorton**
- [x] Extension has a reasonable name (not too general, not too narrow, suggests what the extension is for)
- [x] Repository name is Slicer+ExtensionName
- [x] Extension description summarizes in 1-2 sentences what the extension is usable (should be understandable for non-experts)
- [x] Extension URL and revision (scmurl, scmrevision) is correct, consider using a branch name (master, release, ...) instead of a specific git has to avoid re-submitting pull request whenever the extension is updated
- [x] Extension icon URL is correct
- [ ] Screenshot URLs (screenshoturls) are correct, contains at least one
- [ ] Homepage URL points to valid webpage containing the following:
  - [ ] Extension name
  - [ ] Short description: 1-2 sentences, which summarizes what the extension is usable for
  - [ ] At least one nice, informative image, that illustrates what the extension can do. It may be a screenshot.
  - [ ] Description of contained modules: at one sentence for each module
  - [ ] Tutorial: step-by-step description of at least the most typical use case, include a few screenshots, provide download links to sample input data set

### CODE REVIEW

**Comment by ihnorton** [comment]
This extension build dcm2niix binary as part of the Slicer superbuild. See [this discussion](https://discourse.slicer.org/t/convert-single-files-into-one-nii/5407/12?u=ihnorton) for background.

> A quick but useful initial step could be to provide dcm2niix based DICOM plugin in an extension.

**Comment by fedorov** [comment]
Thanks Isaiah! I personally would add it as a DICOM plugin, but I am not the one doing the work, so have no right to complain!

**Comment by pieper** [comment]
Yes, this looks like a great step in the right direction. 👍

**Comment by lassoan** [comment]
Thank you Isaiah, nice work!

> I personally would add it as a DICOM plugin, but I am not the one doing the work, so have no right to complain!

Fully agree. Ultimately, this will have to be exposed as a DICOM plugin, but the DICOM plugin can be implemented as a Python script that uses a CLI. This is how CreateDICOMSeries CLI is used in the scalar volume plugin for data export.

**Comment by ihnorton** [comment]
> I personally would add it as a DICOM plugin, but I am not the one doing the work, so have no right to complain!

I agree, I just don't have time to do it right now and need to prioritize making it available for DWI-specific use for a collaborator.

We would be happy to have the functionality in this repo, or transfer the repo to another organization if that makes sense. For the time being, I added @fedorov @lassoan @hjmjohnson as admins on this repo.

**Comment by ihnorton** [comment]
Seeing no objections or failures, I'm going to go ahead and merge this to get CI tonight.

**Comment by fedorov** [comment]
@ihnorton 💯 👍 

I greatly appreciate the effort! Thank you for this contribution.

**Pull request merged**
